// Code generated by pigeon; DO NOT EDIT.

// Package movements implements a Pigeon parser for unit movements.
package movements

// I'm not happy with the abstraction here, but...
//
// Movement captures a series of "wants" and "results."
// The unit wants to move N and here are the results.
//
// Step is one piece of that movement. It captures the hex where
// the unit started (From), the direction, and the result (where
// the unit ended up (which could be where it started!), reasons
// why the step failed (it was blocked by an edge feature, it was
// blocked by the destination's terrain (water or mountains?), or
// didn't have enough movement points. Maybe even something like
// wagons can't enter a swamp hex. If the step failed because of a
// lack of movement points, we'll usually be told what the terrain
// type of the would-be destination hex it. If the step succeeded,
// we'll be told the terrain type and (usually) details about the
// edges, too. I don't think that occupants are mentioned when
// moving; that's reserved for scouting.

// STEPS is STEP (SPACE SPACE?)? BACKSLASH STEP)*
// STEP  is DIRECTION DASH TERRAIN STUFF
// STUFF is OCEAN_EDGES? RIVER_EDGES? FORD_EDGES? SETTLEMENT?
// OCEAN_EDGES is COMMA SPACE SPACE     OCEAN SPACE DIRECTION ((SPACE SPACE?) DIRECTION)*
// RIVER_EDGES is COMMA (SPACE SPACE?)? RIVER SPACE DIRECTION (SPACE DIRECTION)*
// FORD_EDGES  is COMMA SPACE           FORD  SPACE DIRECTION (SPACE DIRECTION)*
// SETTLEMENT  is COMMA SPACE SPACE     SETTLEMENT_NAME

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"math"
	"os"
	"sort"
	"strconv"
	"strings"
	"sync"
	"unicode"
	"unicode/utf8"

	"github.com/mdhender/ottomap/domain"
)

type stepSucceeded struct {
	Direction domain.Direction
	Found     struct {
		Terrain domain.Terrain
		Edges   struct {
			Ford  []domain.Direction
			Lake  []domain.Direction
			Ocean []domain.Direction
			River []domain.Direction
		}
		Settlement string
	}
}

type stepBlocked struct {
	Direction domain.Direction
	BlockedBy domain.Terrain
}

type stepExhaustedMP struct {
	Direction domain.Direction
	Terrain   domain.Terrain
}

type fordEdges []domain.Direction
type lakeEdges []domain.Direction
type oceanEdges []domain.Direction
type riverEdges []domain.Direction

func toAnySlice(v any) []any {
	if v == nil {
		return nil
	}
	return v.([]any)
}

var g = &grammar{
	rules: []*rule{
		{
			name: "Step",
			pos:  position{line: 76, col: 1, offset: 2308},
			expr: &choiceExpr{
				pos: position{line: 76, col: 9, offset: 2316},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 76, col: 9, offset: 2316},
						run: (*parser).callonStep2,
						expr: &seqExpr{
							pos: position{line: 76, col: 9, offset: 2316},
							exprs: []any{
								&labeledExpr{
									pos:   position{line: 76, col: 9, offset: 2316},
									label: "d",
									expr: &ruleRefExpr{
										pos:  position{line: 76, col: 11, offset: 2318},
										name: "DIRECTION_CODE",
									},
								},
								&litMatcher{
									pos:        position{line: 76, col: 26, offset: 2333},
									val:        "-",
									ignoreCase: false,
									want:       "\"-\"",
								},
								&labeledExpr{
									pos:   position{line: 76, col: 30, offset: 2337},
									label: "t",
									expr: &ruleRefExpr{
										pos:  position{line: 76, col: 32, offset: 2339},
										name: "TERRAIN_CODE",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 76, col: 45, offset: 2352},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 76, col: 47, offset: 2354},
									label: "edges",
									expr: &zeroOrMoreExpr{
										pos: position{line: 76, col: 53, offset: 2360},
										expr: &ruleRefExpr{
											pos:  position{line: 76, col: 53, offset: 2360},
											name: "Edges",
										},
									},
								},
								&ruleRefExpr{
									pos:  position{line: 76, col: 60, offset: 2367},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 76, col: 62, offset: 2369},
									label: "si",
									expr: &zeroOrOneExpr{
										pos: position{line: 76, col: 65, offset: 2372},
										expr: &ruleRefExpr{
											pos:  position{line: 76, col: 65, offset: 2372},
											name: "Settlement",
										},
									},
								},
								&ruleRefExpr{
									pos:  position{line: 76, col: 77, offset: 2384},
									name: "_",
								},
								&zeroOrMoreExpr{
									pos: position{line: 76, col: 79, offset: 2386},
									expr: &seqExpr{
										pos: position{line: 76, col: 80, offset: 2387},
										exprs: []any{
											&litMatcher{
												pos:        position{line: 76, col: 80, offset: 2387},
												val:        ",",
												ignoreCase: false,
												want:       "\",\"",
											},
											&ruleRefExpr{
												pos:  position{line: 76, col: 84, offset: 2391},
												name: "_",
											},
										},
									},
								},
								&ruleRefExpr{
									pos:  position{line: 76, col: 88, offset: 2395},
									name: "EOF",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 107, col: 5, offset: 3343},
						run: (*parser).callonStep23,
						expr: &seqExpr{
							pos: position{line: 107, col: 5, offset: 3343},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 107, col: 5, offset: 3343},
									val:        "Can't Move on Ocean to ",
									ignoreCase: false,
									want:       "\"Can't Move on Ocean to \"",
								},
								&ruleRefExpr{
									pos:  position{line: 107, col: 31, offset: 3369},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 107, col: 33, offset: 3371},
									label: "d",
									expr: &ruleRefExpr{
										pos:  position{line: 107, col: 35, offset: 3373},
										name: "DIRECTION_CODE",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 107, col: 50, offset: 3388},
									name: "_",
								},
								&litMatcher{
									pos:        position{line: 107, col: 52, offset: 3390},
									val:        "of HEX",
									ignoreCase: false,
									want:       "\"of HEX\"",
								},
								&ruleRefExpr{
									pos:  position{line: 107, col: 61, offset: 3399},
									name: "_",
								},
								&ruleRefExpr{
									pos:  position{line: 107, col: 63, offset: 3401},
									name: "EOF",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 112, col: 5, offset: 3535},
						run: (*parser).callonStep33,
						expr: &seqExpr{
							pos: position{line: 112, col: 5, offset: 3535},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 112, col: 5, offset: 3535},
									val:        "Not enough M.P's to move to ",
									ignoreCase: false,
									want:       "\"Not enough M.P's to move to \"",
								},
								&ruleRefExpr{
									pos:  position{line: 112, col: 36, offset: 3566},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 112, col: 38, offset: 3568},
									label: "d",
									expr: &ruleRefExpr{
										pos:  position{line: 112, col: 40, offset: 3570},
										name: "DIRECTION_CODE",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 112, col: 55, offset: 3585},
									name: "_",
								},
								&litMatcher{
									pos:        position{line: 112, col: 57, offset: 3587},
									val:        "into",
									ignoreCase: false,
									want:       "\"into\"",
								},
								&ruleRefExpr{
									pos:  position{line: 112, col: 64, offset: 3594},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 112, col: 66, offset: 3596},
									label: "t",
									expr: &ruleRefExpr{
										pos:  position{line: 112, col: 68, offset: 3598},
										name: "TERRAIN_LONG",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 112, col: 81, offset: 3611},
									name: "_",
								},
								&ruleRefExpr{
									pos:  position{line: 112, col: 83, offset: 3613},
									name: "EOF",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "DIRECTION_CODE",
			pos:  position{line: 119, col: 1, offset: 3753},
			expr: &actionExpr{
				pos: position{line: 119, col: 19, offset: 3771},
				run: (*parser).callonDIRECTION_CODE1,
				expr: &choiceExpr{
					pos: position{line: 119, col: 20, offset: 3772},
					alternatives: []any{
						&litMatcher{
							pos:        position{line: 119, col: 20, offset: 3772},
							val:        "NE",
							ignoreCase: false,
							want:       "\"NE\"",
						},
						&litMatcher{
							pos:        position{line: 119, col: 27, offset: 3779},
							val:        "SE",
							ignoreCase: false,
							want:       "\"SE\"",
						},
						&litMatcher{
							pos:        position{line: 119, col: 34, offset: 3786},
							val:        "SW",
							ignoreCase: false,
							want:       "\"SW\"",
						},
						&litMatcher{
							pos:        position{line: 119, col: 41, offset: 3793},
							val:        "NW",
							ignoreCase: false,
							want:       "\"NW\"",
						},
						&litMatcher{
							pos:        position{line: 119, col: 48, offset: 3800},
							val:        "N",
							ignoreCase: false,
							want:       "\"N\"",
						},
						&litMatcher{
							pos:        position{line: 119, col: 54, offset: 3806},
							val:        "S",
							ignoreCase: false,
							want:       "\"S\"",
						},
					},
				},
			},
		},
		{
			name: "TERRAIN_CODE",
			pos:  position{line: 131, col: 1, offset: 4173},
			expr: &actionExpr{
				pos: position{line: 131, col: 17, offset: 4189},
				run: (*parser).callonTERRAIN_CODE1,
				expr: &choiceExpr{
					pos: position{line: 132, col: 5, offset: 4195},
					alternatives: []any{
						&litMatcher{
							pos:        position{line: 132, col: 5, offset: 4195},
							val:        "CH",
							ignoreCase: false,
							want:       "\"CH\"",
						},
						&litMatcher{
							pos:        position{line: 132, col: 12, offset: 4202},
							val:        "GH",
							ignoreCase: false,
							want:       "\"GH\"",
						},
						&litMatcher{
							pos:        position{line: 132, col: 19, offset: 4209},
							val:        "PR",
							ignoreCase: false,
							want:       "\"PR\"",
						},
						&litMatcher{
							pos:        position{line: 132, col: 26, offset: 4216},
							val:        "RH",
							ignoreCase: false,
							want:       "\"RH\"",
						},
						&litMatcher{
							pos:        position{line: 132, col: 33, offset: 4223},
							val:        "SW",
							ignoreCase: false,
							want:       "\"SW\"",
						},
						&litMatcher{
							pos:        position{line: 133, col: 5, offset: 4234},
							val:        "L",
							ignoreCase: false,
							want:       "\"L\"",
						},
						&litMatcher{
							pos:        position{line: 133, col: 11, offset: 4240},
							val:        "O",
							ignoreCase: false,
							want:       "\"O\"",
						},
					},
				},
			},
		},
		{
			name: "Edges",
			pos:  position{line: 154, col: 1, offset: 4706},
			expr: &choiceExpr{
				pos: position{line: 154, col: 10, offset: 4715},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 154, col: 10, offset: 4715},
						run: (*parser).callonEdges2,
						expr: &seqExpr{
							pos: position{line: 154, col: 10, offset: 4715},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 154, col: 10, offset: 4715},
									val:        ",",
									ignoreCase: false,
									want:       "\",\"",
								},
								&ruleRefExpr{
									pos:  position{line: 154, col: 14, offset: 4719},
									name: "_",
								},
								&litMatcher{
									pos:        position{line: 154, col: 16, offset: 4721},
									val:        "Ford",
									ignoreCase: false,
									want:       "\"Ford\"",
								},
								&ruleRefExpr{
									pos:  position{line: 154, col: 23, offset: 4728},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 154, col: 25, offset: 4730},
									label: "d",
									expr: &ruleRefExpr{
										pos:  position{line: 154, col: 27, offset: 4732},
										name: "DIRECTION_CODE",
									},
								},
								&labeledExpr{
									pos:   position{line: 154, col: 42, offset: 4747},
									label: "dli",
									expr: &zeroOrMoreExpr{
										pos: position{line: 154, col: 46, offset: 4751},
										expr: &ruleRefExpr{
											pos:  position{line: 154, col: 46, offset: 4751},
											name: "optSpaceDirection",
										},
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 168, col: 5, offset: 5160},
						run: (*parser).callonEdges13,
						expr: &seqExpr{
							pos: position{line: 168, col: 5, offset: 5160},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 168, col: 5, offset: 5160},
									val:        ",",
									ignoreCase: false,
									want:       "\",\"",
								},
								&ruleRefExpr{
									pos:  position{line: 168, col: 9, offset: 5164},
									name: "_",
								},
								&litMatcher{
									pos:        position{line: 168, col: 11, offset: 5166},
									val:        "O",
									ignoreCase: false,
									want:       "\"O\"",
								},
								&ruleRefExpr{
									pos:  position{line: 168, col: 15, offset: 5170},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 168, col: 17, offset: 5172},
									label: "d",
									expr: &ruleRefExpr{
										pos:  position{line: 168, col: 19, offset: 5174},
										name: "DIRECTION_CODE",
									},
								},
								&labeledExpr{
									pos:   position{line: 168, col: 34, offset: 5189},
									label: "dli",
									expr: &zeroOrMoreExpr{
										pos: position{line: 168, col: 38, offset: 5193},
										expr: &ruleRefExpr{
											pos:  position{line: 168, col: 38, offset: 5193},
											name: "optCommaDirection",
										},
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 182, col: 5, offset: 5603},
						run: (*parser).callonEdges24,
						expr: &seqExpr{
							pos: position{line: 182, col: 5, offset: 5603},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 182, col: 5, offset: 5603},
									val:        ",",
									ignoreCase: false,
									want:       "\",\"",
								},
								&ruleRefExpr{
									pos:  position{line: 182, col: 9, offset: 5607},
									name: "_",
								},
								&litMatcher{
									pos:        position{line: 182, col: 11, offset: 5609},
									val:        "River",
									ignoreCase: false,
									want:       "\"River\"",
								},
								&ruleRefExpr{
									pos:  position{line: 182, col: 19, offset: 5617},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 182, col: 21, offset: 5619},
									label: "d",
									expr: &ruleRefExpr{
										pos:  position{line: 182, col: 23, offset: 5621},
										name: "DIRECTION_CODE",
									},
								},
								&labeledExpr{
									pos:   position{line: 182, col: 38, offset: 5636},
									label: "dli",
									expr: &zeroOrMoreExpr{
										pos: position{line: 182, col: 42, offset: 5640},
										expr: &ruleRefExpr{
											pos:  position{line: 182, col: 42, offset: 5640},
											name: "optSpaceDirection",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "optCommaDirection",
			pos:  position{line: 198, col: 1, offset: 6049},
			expr: &actionExpr{
				pos: position{line: 198, col: 22, offset: 6070},
				run: (*parser).callonoptCommaDirection1,
				expr: &seqExpr{
					pos: position{line: 198, col: 22, offset: 6070},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 198, col: 22, offset: 6070},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 198, col: 24, offset: 6072},
							val:        ",",
							ignoreCase: false,
							want:       "\",\"",
						},
						&ruleRefExpr{
							pos:  position{line: 198, col: 28, offset: 6076},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 198, col: 30, offset: 6078},
							label: "d",
							expr: &ruleRefExpr{
								pos:  position{line: 198, col: 32, offset: 6080},
								name: "DIRECTION_CODE",
							},
						},
					},
				},
			},
		},
		{
			name: "optSpaceDirection",
			pos:  position{line: 202, col: 1, offset: 6137},
			expr: &actionExpr{
				pos: position{line: 202, col: 22, offset: 6158},
				run: (*parser).callonoptSpaceDirection1,
				expr: &seqExpr{
					pos: position{line: 202, col: 22, offset: 6158},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 202, col: 22, offset: 6158},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 202, col: 24, offset: 6160},
							label: "d",
							expr: &ruleRefExpr{
								pos:  position{line: 202, col: 26, offset: 6162},
								name: "DIRECTION_CODE",
							},
						},
					},
				},
			},
		},
		{
			name: "Settlement",
			pos:  position{line: 206, col: 1, offset: 6219},
			expr: &actionExpr{
				pos: position{line: 206, col: 15, offset: 6233},
				run: (*parser).callonSettlement1,
				expr: &seqExpr{
					pos: position{line: 206, col: 15, offset: 6233},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 206, col: 15, offset: 6233},
							val:        ",",
							ignoreCase: false,
							want:       "\",\"",
						},
						&ruleRefExpr{
							pos:  position{line: 206, col: 19, offset: 6237},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 206, col: 21, offset: 6239},
							label: "n",
							expr: &ruleRefExpr{
								pos:  position{line: 206, col: 23, offset: 6241},
								name: "SettlementName",
							},
						},
					},
				},
			},
		},
		{
			name: "SettlementName",
			pos:  position{line: 210, col: 1, offset: 6288},
			expr: &actionExpr{
				pos: position{line: 210, col: 19, offset: 6306},
				run: (*parser).callonSettlementName1,
				expr: &seqExpr{
					pos: position{line: 210, col: 19, offset: 6306},
					exprs: []any{
						&charClassMatcher{
							pos:        position{line: 210, col: 19, offset: 6306},
							val:        "[A-Z]",
							ranges:     []rune{'A', 'Z'},
							ignoreCase: false,
							inverted:   false,
						},
						&oneOrMoreExpr{
							pos: position{line: 210, col: 24, offset: 6311},
							expr: &charClassMatcher{
								pos:        position{line: 210, col: 24, offset: 6311},
								val:        "[A-Za-z]",
								ranges:     []rune{'A', 'Z', 'a', 'z'},
								ignoreCase: false,
								inverted:   false,
							},
						},
					},
				},
			},
		},
		{
			name: "TERRAIN_LONG",
			pos:  position{line: 214, col: 1, offset: 6357},
			expr: &actionExpr{
				pos: position{line: 214, col: 20, offset: 6376},
				run: (*parser).callonTERRAIN_LONG1,
				expr: &choiceExpr{
					pos: position{line: 215, col: 5, offset: 6382},
					alternatives: []any{
						&litMatcher{
							pos:        position{line: 215, col: 5, offset: 6382},
							val:        "CONIFER HILLS",
							ignoreCase: false,
							want:       "\"CONIFER HILLS\"",
						},
						&litMatcher{
							pos:        position{line: 215, col: 23, offset: 6400},
							val:        "GRASSY HILLS",
							ignoreCase: false,
							want:       "\"GRASSY HILLS\"",
						},
						&litMatcher{
							pos:        position{line: 215, col: 40, offset: 6417},
							val:        "LAKE",
							ignoreCase: false,
							want:       "\"LAKE\"",
						},
						&litMatcher{
							pos:        position{line: 215, col: 50, offset: 6427},
							val:        "OCEAN",
							ignoreCase: false,
							want:       "\"OCEAN\"",
						},
						&litMatcher{
							pos:        position{line: 216, col: 5, offset: 6441},
							val:        "PRAIRIE",
							ignoreCase: false,
							want:       "\"PRAIRIE\"",
						},
						&litMatcher{
							pos:        position{line: 216, col: 23, offset: 6459},
							val:        "ROCKY HILLS",
							ignoreCase: false,
							want:       "\"ROCKY HILLS\"",
						},
						&litMatcher{
							pos:        position{line: 216, col: 40, offset: 6476},
							val:        "SWAMP",
							ignoreCase: false,
							want:       "\"SWAMP\"",
						},
					},
				},
			},
		},
		{
			name: "EOF",
			pos:  position{line: 239, col: 1, offset: 7015},
			expr: &notExpr{
				pos: position{line: 239, col: 8, offset: 7022},
				expr: &anyMatcher{
					line: 239, col: 9, offset: 7023,
				},
			},
		},
		{
			name: "DIGIT",
			pos:  position{line: 240, col: 1, offset: 7025},
			expr: &charClassMatcher{
				pos:        position{line: 240, col: 9, offset: 7033},
				val:        "[0-9]",
				ranges:     []rune{'0', '9'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "SP",
			pos:  position{line: 241, col: 1, offset: 7039},
			expr: &litMatcher{
				pos:        position{line: 241, col: 6, offset: 7044},
				val:        " ",
				ignoreCase: false,
				want:       "\" \"",
			},
		},
		{
			name: "_",
			pos:  position{line: 242, col: 1, offset: 7048},
			expr: &zeroOrMoreExpr{
				pos: position{line: 242, col: 5, offset: 7052},
				expr: &charClassMatcher{
					pos:        position{line: 242, col: 5, offset: 7052},
					val:        "[ \\t]",
					chars:      []rune{' ', '\t'},
					ignoreCase: false,
					inverted:   false,
				},
			},
		},
	},
}

func (c *current) onStep2(d, t, edges, si any) (any, error) {
	var step stepSucceeded
	step.Direction = d.(domain.Direction)
	step.Found.Terrain = t.(domain.Terrain)

	for _, edge := range toAnySlice(edges) {
		if edge != nil {
			switch val := edge.(type) {
			case fordEdges:
				for _, v := range val {
					step.Found.Edges.Ford = append(step.Found.Edges.Ford, v)
				}
			case oceanEdges:
				for _, v := range val {
					step.Found.Edges.Ocean = append(step.Found.Edges.Ocean, v)
				}
			case riverEdges:
				for _, v := range val {
					step.Found.Edges.River = append(step.Found.Edges.River, v)
				}
			default:
				panic(fmt.Errorf("step: edges: unknown type %T", val))
			}
		}
	}

	if si != nil {
		step.Found.Settlement = si.(string)
	}

	return &step, nil
}

func (p *parser) callonStep2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onStep2(stack["d"], stack["t"], stack["edges"], stack["si"])
}

func (c *current) onStep23(d any) (any, error) {
	var step stepBlocked
	step.Direction = d.(domain.Direction)
	step.BlockedBy = domain.TOcean
	return &step, nil
}

func (p *parser) callonStep23() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onStep23(stack["d"])
}

func (c *current) onStep33(d, t any) (any, error) {
	var step stepExhaustedMP
	step.Direction = d.(domain.Direction)
	step.Terrain = t.(domain.Terrain)
	return &step, nil
}

func (p *parser) callonStep33() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onStep33(stack["d"], stack["t"])
}

func (c *current) onDIRECTION_CODE1() (any, error) {
	switch string(c.text) {
	case "N":
		return domain.DNorth, nil
	case "NE":
		return domain.DNorthEast, nil
	case "SE":
		return domain.DSouthEast, nil
	case "S":
		return domain.DSouth, nil
	case "SW":
		return domain.DSouthWest, nil
	case "NW":
		return domain.DNorthWest, nil
	}
	panic(fmt.Sprintf("assert(code != %q)", string(c.text)))
}

func (p *parser) callonDIRECTION_CODE1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDIRECTION_CODE1()
}

func (c *current) onTERRAIN_CODE1() (any, error) {
	switch string(c.text) {
	case "CH":
		return domain.TConiferHills, nil
	case "GH":
		return domain.TGrassyHills, nil
	case "L":
		return domain.TLake, nil
	case "O":
		return domain.TOcean, nil
	case "PR":
		return domain.TPrairie, nil
	case "RH":
		return domain.TRockyHills, nil
	case "SW":
		return domain.TSwamp, nil
	}
	panic(fmt.Sprintf("assert(code != %q)", string(c.text)))
}

func (p *parser) callonTERRAIN_CODE1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTERRAIN_CODE1()
}

func (c *current) onEdges2(d, dli any) (any, error) {
	var edges fordEdges
	edges = append(edges, d.(domain.Direction))
	for _, dir := range toAnySlice(dli) {
		if dir != nil {
			switch v := dir.(type) {
			case domain.Direction:
				edges = append(edges, v)
			default:
				panic(fmt.Sprintf("assert(type != %T)", v))
			}
		}
	}
	return edges, nil
}

func (p *parser) callonEdges2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onEdges2(stack["d"], stack["dli"])
}

func (c *current) onEdges13(d, dli any) (any, error) {
	var edges oceanEdges
	edges = append(edges, d.(domain.Direction))
	for _, dir := range toAnySlice(dli) {
		if dir != nil {
			switch v := dir.(type) {
			case domain.Direction:
				edges = append(edges, v)
			default:
				panic(fmt.Sprintf("assert(type != %T)", v))
			}
		}
	}
	return edges, nil
}

func (p *parser) callonEdges13() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onEdges13(stack["d"], stack["dli"])
}

func (c *current) onEdges24(d, dli any) (any, error) {
	var edges riverEdges
	edges = append(edges, d.(domain.Direction))
	for _, dir := range toAnySlice(dli) {
		if dir != nil {
			switch v := dir.(type) {
			case domain.Direction:
				edges = append(edges, v)
			default:
				panic(fmt.Sprintf("assert(type != %T)", v))
			}
		}
	}
	return edges, nil
}

func (p *parser) callonEdges24() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onEdges24(stack["d"], stack["dli"])
}

func (c *current) onoptCommaDirection1(d any) (any, error) {
	return d.(domain.Direction), nil
}

func (p *parser) callonoptCommaDirection1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onoptCommaDirection1(stack["d"])
}

func (c *current) onoptSpaceDirection1(d any) (any, error) {
	return d.(domain.Direction), nil
}

func (p *parser) callonoptSpaceDirection1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onoptSpaceDirection1(stack["d"])
}

func (c *current) onSettlement1(n any) (any, error) {
	return n.(string), nil
}

func (p *parser) callonSettlement1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSettlement1(stack["n"])
}

func (c *current) onSettlementName1() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonSettlementName1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSettlementName1()
}

func (c *current) onTERRAIN_LONG1() (any, error) {
	s := string(c.text)
	switch s {
	case "CONIFER HILLS":
		return domain.TConiferHills, nil
	case "GRASSY HILLS":
		return domain.TGrassyHills, nil
	case "LAKE":
		return domain.TLake, nil
	case "OCEAN":
		return domain.TOcean, nil
	case "PRAIRIE":
		return domain.TPrairie, nil
	case "ROCKY HILLS":
		return domain.TRockyHills, nil
	case "SWAMP":
		return domain.TSwamp, nil
	default:
		return string(c.text), fmt.Errorf("unknown terrain")
	}
}

func (p *parser) callonTERRAIN_LONG1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTERRAIN_LONG1()
}

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEntrypoint is returned when the specified entrypoint rule
	// does not exit.
	errInvalidEntrypoint = errors.New("invalid entrypoint")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errMaxExprCnt is used to signal that the maximum number of
	// expressions have been parsed.
	errMaxExprCnt = errors.New("max number of expresssions parsed")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// MaxExpressions creates an Option to stop parsing after the provided
// number of expressions have been parsed, if the value is 0 then the parser will
// parse for as many steps as needed (possibly an infinite number).
//
// The default for maxExprCnt is 0.
func MaxExpressions(maxExprCnt uint64) Option {
	return func(p *parser) Option {
		oldMaxExprCnt := p.maxExprCnt
		p.maxExprCnt = maxExprCnt
		return MaxExpressions(oldMaxExprCnt)
	}
}

// Entrypoint creates an Option to set the rule name to use as entrypoint.
// The rule name must have been specified in the -alternate-entrypoints
// if generating the parser with the -optimize-grammar flag, otherwise
// it may have been optimized out. Passing an empty string sets the
// entrypoint to the first rule in the grammar.
//
// The default is to start parsing at the first rule in the grammar.
func Entrypoint(ruleName string) Option {
	return func(p *parser) Option {
		oldEntrypoint := p.entrypoint
		p.entrypoint = ruleName
		if ruleName == "" {
			p.entrypoint = g.rules[0].name
		}
		return Entrypoint(oldEntrypoint)
	}
}

// Statistics adds a user provided Stats struct to the parser to allow
// the user to process the results after the parsing has finished.
// Also the key for the "no match" counter is set.
//
// Example usage:
//
//	input := "input"
//	stats := Stats{}
//	_, err := Parse("input-file", []byte(input), Statistics(&stats, "no match"))
//	if err != nil {
//	    log.Panicln(err)
//	}
//	b, err := json.MarshalIndent(stats.ChoiceAltCnt, "", "  ")
//	if err != nil {
//	    log.Panicln(err)
//	}
//	fmt.Println(string(b))
func Statistics(stats *Stats, choiceNoMatch string) Option {
	return func(p *parser) Option {
		oldStats := p.Stats
		p.Stats = stats
		oldChoiceNoMatch := p.choiceNoMatch
		p.choiceNoMatch = choiceNoMatch
		if p.Stats.ChoiceAltCnt == nil {
			p.Stats.ChoiceAltCnt = make(map[string]map[string]int)
		}
		return Statistics(oldStats, oldChoiceNoMatch)
	}
}

// Debug creates an Option to set the debug flag to b. When set to true,
// debugging information is printed to stdout while parsing.
//
// The default is false.
func Debug(b bool) Option {
	return func(p *parser) Option {
		old := p.debug
		p.debug = b
		return Debug(old)
	}
}

// Memoize creates an Option to set the memoize flag to b. When set to true,
// the parser will cache all results so each expression is evaluated only
// once. This guarantees linear parsing time even for pathological cases,
// at the expense of more memory and slower times for typical cases.
//
// The default is false.
func Memoize(b bool) Option {
	return func(p *parser) Option {
		old := p.memoize
		p.memoize = b
		return Memoize(old)
	}
}

// AllowInvalidUTF8 creates an Option to allow invalid UTF-8 bytes.
// Every invalid UTF-8 byte is treated as a utf8.RuneError (U+FFFD)
// by character class matchers and is matched by the any matcher.
// The returned matched value, c.text and c.offset are NOT affected.
//
// The default is false.
func AllowInvalidUTF8(b bool) Option {
	return func(p *parser) Option {
		old := p.allowInvalidUTF8
		p.allowInvalidUTF8 = b
		return AllowInvalidUTF8(old)
	}
}

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option {
	return func(p *parser) Option {
		old := p.recover
		p.recover = b
		return Recover(old)
	}
}

// GlobalStore creates an Option to set a key to a certain value in
// the globalStore.
func GlobalStore(key string, value any) Option {
	return func(p *parser) Option {
		old := p.cur.globalStore[key]
		p.cur.globalStore[key] = value
		return GlobalStore(key, old)
	}
}

// InitState creates an Option to set a key to a certain value in
// the global "state" store.
func InitState(key string, value any) Option {
	return func(p *parser) Option {
		old := p.cur.state[key]
		p.cur.state[key] = value
		return InitState(key, old)
	}
}

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (i any, err error) {
	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer func() {
		if closeErr := f.Close(); closeErr != nil {
			err = closeErr
		}
	}()
	return ParseReader(filename, f, opts...)
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (any, error) {
	b, err := io.ReadAll(r)
	if err != nil {
		return nil, err
	}

	return Parse(filename, b, opts...)
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (any, error) {
	return newParser(filename, b, opts...).parse(g)
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string {
	return strconv.Itoa(p.line) + ":" + strconv.Itoa(p.col) + " [" + strconv.Itoa(p.offset) + "]"
}

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match

	// state is a store for arbitrary key,value pairs that the user wants to be
	// tied to the backtracking of the parser.
	// This is always rolled back if a parsing rule fails.
	state storeDict

	// globalStore is a general store for the user to store arbitrary key-value
	// pairs that they need to manage and that they do not want tied to the
	// backtracking of the parser. This is only modified by the user and never
	// rolled back by the parser. It is always up to the user to keep this in a
	// consistent state.
	globalStore storeDict
}

type storeDict map[string]any

// the AST types...

type grammar struct {
	pos   position
	rules []*rule
}

type rule struct {
	pos         position
	name        string
	displayName string
	expr        any
}

type choiceExpr struct {
	pos          position
	alternatives []any
}

type actionExpr struct {
	pos  position
	expr any
	run  func(*parser) (any, error)
}

type recoveryExpr struct {
	pos          position
	expr         any
	recoverExpr  any
	failureLabel []string
}

type seqExpr struct {
	pos   position
	exprs []any
}

type throwExpr struct {
	pos   position
	label string
}

type labeledExpr struct {
	pos   position
	label string
	expr  any
}

type expr struct {
	pos  position
	expr any
}

type (
	andExpr        expr
	notExpr        expr
	zeroOrOneExpr  expr
	zeroOrMoreExpr expr
	oneOrMoreExpr  expr
)

type ruleRefExpr struct {
	pos  position
	name string
}

type stateCodeExpr struct {
	pos position
	run func(*parser) error
}

type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
	want       string
}

type charClassMatcher struct {
	pos             position
	val             string
	basicLatinChars [128]bool
	chars           []rune
	ranges          []rune
	classes         []*unicode.RangeTable
	ignoreCase      bool
	inverted        bool
}

type anyMatcher position

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) {
	*e = append(*e, err)
}

func (e errList) err() error {
	if len(e) == 0 {
		return nil
	}
	e.dedupe()
	return e
}

func (e *errList) dedupe() {
	var cleaned []error
	set := make(map[string]bool)
	for _, err := range *e {
		if msg := err.Error(); !set[msg] {
			set[msg] = true
			cleaned = append(cleaned, err)
		}
	}
	*e = cleaned
}

func (e errList) Error() string {
	switch len(e) {
	case 0:
		return ""
	case 1:
		return e[0].Error()
	default:
		var buf bytes.Buffer

		for i, err := range e {
			if i > 0 {
				buf.WriteRune('\n')
			}
			buf.WriteString(err.Error())
		}
		return buf.String()
	}
}

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner    error
	pos      position
	prefix   string
	expected []string
}

// Error returns the error message.
func (p *parserError) Error() string {
	return p.prefix + ": " + p.Inner.Error()
}

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	stats := Stats{
		ChoiceAltCnt: make(map[string]map[string]int),
	}

	p := &parser{
		filename: filename,
		errs:     new(errList),
		data:     b,
		pt:       savepoint{position: position{line: 1}},
		recover:  true,
		cur: current{
			state:       make(storeDict),
			globalStore: make(storeDict),
		},
		maxFailPos:      position{col: 1, line: 1},
		maxFailExpected: make([]string, 0, 20),
		Stats:           &stats,
		// start rule is rule [0] unless an alternate entrypoint is specified
		entrypoint: g.rules[0].name,
	}
	p.setOptions(opts)

	if p.maxExprCnt == 0 {
		p.maxExprCnt = math.MaxUint64
	}

	return p
}

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) {
	for _, opt := range opts {
		opt(p)
	}
}

type resultTuple struct {
	v   any
	b   bool
	end savepoint
}

const choiceNoMatch = -1

// Stats stores some statistics, gathered during parsing
type Stats struct {
	// ExprCnt counts the number of expressions processed during parsing
	// This value is compared to the maximum number of expressions allowed
	// (set by the MaxExpressions option).
	ExprCnt uint64

	// ChoiceAltCnt is used to count for each ordered choice expression,
	// which alternative is used how may times.
	// These numbers allow to optimize the order of the ordered choice expression
	// to increase the performance of the parser
	//
	// The outer key of ChoiceAltCnt is composed of the name of the rule as well
	// as the line and the column of the ordered choice.
	// The inner key of ChoiceAltCnt is the number (one-based) of the matching alternative.
	// For each alternative the number of matches are counted. If an ordered choice does not
	// match, a special counter is incremented. The name of this counter is set with
	// the parser option Statistics.
	// For an alternative to be included in ChoiceAltCnt, it has to match at least once.
	ChoiceAltCnt map[string]map[string]int
}

type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	depth   int
	recover bool
	debug   bool

	memoize bool
	// memoization table for the packrat algorithm:
	// map[offset in source] map[expression or rule] {value, match}
	memo map[int]map[any]resultTuple

	// rules table, maps the rule identifier to the rule node
	rules map[string]*rule
	// variables stack, map of label to value
	vstack []map[string]any
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// parse fail
	maxFailPos            position
	maxFailExpected       []string
	maxFailInvertExpected bool

	// max number of expressions to be parsed
	maxExprCnt uint64
	// entrypoint for the parser
	entrypoint string

	allowInvalidUTF8 bool

	*Stats

	choiceNoMatch string
	// recovery expression stack, keeps track of the currently available recovery expression, these are traversed in reverse
	recoveryStack []map[string]any
}

// push a variable set on the vstack.
func (p *parser) pushV() {
	if cap(p.vstack) == len(p.vstack) {
		// create new empty slot in the stack
		p.vstack = append(p.vstack, nil)
	} else {
		// slice to 1 more
		p.vstack = p.vstack[:len(p.vstack)+1]
	}

	// get the last args set
	m := p.vstack[len(p.vstack)-1]
	if m != nil && len(m) == 0 {
		// empty map, all good
		return
	}

	m = make(map[string]any)
	p.vstack[len(p.vstack)-1] = m
}

// pop a variable set from the vstack.
func (p *parser) popV() {
	// if the map is not empty, clear it
	m := p.vstack[len(p.vstack)-1]
	if len(m) > 0 {
		// GC that map
		p.vstack[len(p.vstack)-1] = nil
	}
	p.vstack = p.vstack[:len(p.vstack)-1]
}

// push a recovery expression with its labels to the recoveryStack
func (p *parser) pushRecovery(labels []string, expr any) {
	if cap(p.recoveryStack) == len(p.recoveryStack) {
		// create new empty slot in the stack
		p.recoveryStack = append(p.recoveryStack, nil)
	} else {
		// slice to 1 more
		p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)+1]
	}

	m := make(map[string]any, len(labels))
	for _, fl := range labels {
		m[fl] = expr
	}
	p.recoveryStack[len(p.recoveryStack)-1] = m
}

// pop a recovery expression from the recoveryStack
func (p *parser) popRecovery() {
	// GC that map
	p.recoveryStack[len(p.recoveryStack)-1] = nil

	p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)-1]
}

func (p *parser) print(prefix, s string) string {
	if !p.debug {
		return s
	}

	fmt.Printf("%s %d:%d:%d: %s [%#U]\n",
		prefix, p.pt.line, p.pt.col, p.pt.offset, s, p.pt.rn)
	return s
}

func (p *parser) printIndent(mark string, s string) string {
	return p.print(strings.Repeat(" ", p.depth)+mark, s)
}

func (p *parser) in(s string) string {
	res := p.printIndent(">", s)
	p.depth++
	return res
}

func (p *parser) out(s string) string {
	p.depth--
	return p.printIndent("<", s)
}

func (p *parser) addErr(err error) {
	p.addErrAt(err, p.pt.position, []string{})
}

func (p *parser) addErrAt(err error, pos position, expected []string) {
	var buf bytes.Buffer
	if p.filename != "" {
		buf.WriteString(p.filename)
	}
	if buf.Len() > 0 {
		buf.WriteString(":")
	}
	buf.WriteString(fmt.Sprintf("%d:%d (%d)", pos.line, pos.col, pos.offset))
	if len(p.rstack) > 0 {
		if buf.Len() > 0 {
			buf.WriteString(": ")
		}
		rule := p.rstack[len(p.rstack)-1]
		if rule.displayName != "" {
			buf.WriteString("rule " + rule.displayName)
		} else {
			buf.WriteString("rule " + rule.name)
		}
	}
	pe := &parserError{Inner: err, pos: pos, prefix: buf.String(), expected: expected}
	p.errs.add(pe)
}

func (p *parser) failAt(fail bool, pos position, want string) {
	// process fail if parsing fails and not inverted or parsing succeeds and invert is set
	if fail == p.maxFailInvertExpected {
		if pos.offset < p.maxFailPos.offset {
			return
		}

		if pos.offset > p.maxFailPos.offset {
			p.maxFailPos = pos
			p.maxFailExpected = p.maxFailExpected[:0]
		}

		if p.maxFailInvertExpected {
			want = "!" + want
		}
		p.maxFailExpected = append(p.maxFailExpected, want)
	}
}

// read advances the parser to the next rune.
func (p *parser) read() {
	p.pt.offset += p.pt.w
	rn, n := utf8.DecodeRune(p.data[p.pt.offset:])
	p.pt.rn = rn
	p.pt.w = n
	p.pt.col++
	if rn == '\n' {
		p.pt.line++
		p.pt.col = 0
	}

	if rn == utf8.RuneError && n == 1 { // see utf8.DecodeRune
		if !p.allowInvalidUTF8 {
			p.addErr(errInvalidEncoding)
		}
	}
}

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) {
	if p.debug {
		defer p.out(p.in("restore"))
	}
	if pt.offset == p.pt.offset {
		return
	}
	p.pt = pt
}

// Cloner is implemented by any value that has a Clone method, which returns a
// copy of the value. This is mainly used for types which are not passed by
// value (e.g map, slice, chan) or structs that contain such types.
//
// This is used in conjunction with the global state feature to create proper
// copies of the state to allow the parser to properly restore the state in
// the case of backtracking.
type Cloner interface {
	Clone() any
}

var statePool = &sync.Pool{
	New: func() any { return make(storeDict) },
}

func (sd storeDict) Discard() {
	for k := range sd {
		delete(sd, k)
	}
	statePool.Put(sd)
}

// clone and return parser current state.
func (p *parser) cloneState() storeDict {
	if p.debug {
		defer p.out(p.in("cloneState"))
	}

	state := statePool.Get().(storeDict)
	for k, v := range p.cur.state {
		if c, ok := v.(Cloner); ok {
			state[k] = c.Clone()
		} else {
			state[k] = v
		}
	}
	return state
}

// restore parser current state to the state storeDict.
// every restoreState should applied only one time for every cloned state
func (p *parser) restoreState(state storeDict) {
	if p.debug {
		defer p.out(p.in("restoreState"))
	}
	p.cur.state.Discard()
	p.cur.state = state
}

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte {
	return p.data[start.position.offset:p.pt.position.offset]
}

func (p *parser) getMemoized(node any) (resultTuple, bool) {
	if len(p.memo) == 0 {
		return resultTuple{}, false
	}
	m := p.memo[p.pt.offset]
	if len(m) == 0 {
		return resultTuple{}, false
	}
	res, ok := m[node]
	return res, ok
}

func (p *parser) setMemoized(pt savepoint, node any, tuple resultTuple) {
	if p.memo == nil {
		p.memo = make(map[int]map[any]resultTuple)
	}
	m := p.memo[pt.offset]
	if m == nil {
		m = make(map[any]resultTuple)
		p.memo[pt.offset] = m
	}
	m[node] = tuple
}

func (p *parser) buildRulesTable(g *grammar) {
	p.rules = make(map[string]*rule, len(g.rules))
	for _, r := range g.rules {
		p.rules[r.name] = r
	}
}

func (p *parser) parse(g *grammar) (val any, err error) {
	if len(g.rules) == 0 {
		p.addErr(errNoRule)
		return nil, p.errs.err()
	}

	// TODO : not super critical but this could be generated
	p.buildRulesTable(g)

	if p.recover {
		// panic can be used in action code to stop parsing immediately
		// and return the panic as an error.
		defer func() {
			if e := recover(); e != nil {
				if p.debug {
					defer p.out(p.in("panic handler"))
				}
				val = nil
				switch e := e.(type) {
				case error:
					p.addErr(e)
				default:
					p.addErr(fmt.Errorf("%v", e))
				}
				err = p.errs.err()
			}
		}()
	}

	startRule, ok := p.rules[p.entrypoint]
	if !ok {
		p.addErr(errInvalidEntrypoint)
		return nil, p.errs.err()
	}

	p.read() // advance to first rune
	val, ok = p.parseRuleWrap(startRule)
	if !ok {
		if len(*p.errs) == 0 {
			// If parsing fails, but no errors have been recorded, the expected values
			// for the farthest parser position are returned as error.
			maxFailExpectedMap := make(map[string]struct{}, len(p.maxFailExpected))
			for _, v := range p.maxFailExpected {
				maxFailExpectedMap[v] = struct{}{}
			}
			expected := make([]string, 0, len(maxFailExpectedMap))
			eof := false
			if _, ok := maxFailExpectedMap["!."]; ok {
				delete(maxFailExpectedMap, "!.")
				eof = true
			}
			for k := range maxFailExpectedMap {
				expected = append(expected, k)
			}
			sort.Strings(expected)
			if eof {
				expected = append(expected, "EOF")
			}
			p.addErrAt(errors.New("no match found, expected: "+listJoin(expected, ", ", "or")), p.maxFailPos, expected)
		}

		return nil, p.errs.err()
	}
	return val, p.errs.err()
}

func listJoin(list []string, sep string, lastSep string) string {
	switch len(list) {
	case 0:
		return ""
	case 1:
		return list[0]
	default:
		return strings.Join(list[:len(list)-1], sep) + " " + lastSep + " " + list[len(list)-1]
	}
}

func (p *parser) parseRuleMemoize(rule *rule) (any, bool) {
	res, ok := p.getMemoized(rule)
	if ok {
		p.restore(res.end)
		return res.v, res.b
	}

	startMark := p.pt
	val, ok := p.parseRule(rule)
	p.setMemoized(startMark, rule, resultTuple{val, ok, p.pt})

	return val, ok
}

func (p *parser) parseRuleWrap(rule *rule) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRule " + rule.name))
	}
	var (
		val       any
		ok        bool
		startMark = p.pt
	)

	if p.memoize {
		val, ok = p.parseRuleMemoize(rule)
	} else {
		val, ok = p.parseRule(rule)
	}

	if ok && p.debug {
		p.printIndent("MATCH", string(p.sliceFrom(startMark)))
	}
	return val, ok
}

func (p *parser) parseRule(rule *rule) (any, bool) {
	p.rstack = append(p.rstack, rule)
	p.pushV()
	val, ok := p.parseExprWrap(rule.expr)
	p.popV()
	p.rstack = p.rstack[:len(p.rstack)-1]
	return val, ok
}

func (p *parser) parseExprWrap(expr any) (any, bool) {
	var pt savepoint

	if p.memoize {
		res, ok := p.getMemoized(expr)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
		pt = p.pt
	}

	val, ok := p.parseExpr(expr)

	if p.memoize {
		p.setMemoized(pt, expr, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseExpr(expr any) (any, bool) {
	p.ExprCnt++
	if p.ExprCnt > p.maxExprCnt {
		panic(errMaxExprCnt)
	}

	var val any
	var ok bool
	switch expr := expr.(type) {
	case *actionExpr:
		val, ok = p.parseActionExpr(expr)
	case *andCodeExpr:
		val, ok = p.parseAndCodeExpr(expr)
	case *andExpr:
		val, ok = p.parseAndExpr(expr)
	case *anyMatcher:
		val, ok = p.parseAnyMatcher(expr)
	case *charClassMatcher:
		val, ok = p.parseCharClassMatcher(expr)
	case *choiceExpr:
		val, ok = p.parseChoiceExpr(expr)
	case *labeledExpr:
		val, ok = p.parseLabeledExpr(expr)
	case *litMatcher:
		val, ok = p.parseLitMatcher(expr)
	case *notCodeExpr:
		val, ok = p.parseNotCodeExpr(expr)
	case *notExpr:
		val, ok = p.parseNotExpr(expr)
	case *oneOrMoreExpr:
		val, ok = p.parseOneOrMoreExpr(expr)
	case *recoveryExpr:
		val, ok = p.parseRecoveryExpr(expr)
	case *ruleRefExpr:
		val, ok = p.parseRuleRefExpr(expr)
	case *seqExpr:
		val, ok = p.parseSeqExpr(expr)
	case *stateCodeExpr:
		val, ok = p.parseStateCodeExpr(expr)
	case *throwExpr:
		val, ok = p.parseThrowExpr(expr)
	case *zeroOrMoreExpr:
		val, ok = p.parseZeroOrMoreExpr(expr)
	case *zeroOrOneExpr:
		val, ok = p.parseZeroOrOneExpr(expr)
	default:
		panic(fmt.Sprintf("unknown expression type %T", expr))
	}
	return val, ok
}

func (p *parser) parseActionExpr(act *actionExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseActionExpr"))
	}

	start := p.pt
	val, ok := p.parseExprWrap(act.expr)
	if ok {
		p.cur.pos = start.position
		p.cur.text = p.sliceFrom(start)
		state := p.cloneState()
		actVal, err := act.run(p)
		if err != nil {
			p.addErrAt(err, start.position, []string{})
		}
		p.restoreState(state)

		val = actVal
	}
	if ok && p.debug {
		p.printIndent("MATCH", string(p.sliceFrom(start)))
	}
	return val, ok
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAndCodeExpr"))
	}

	state := p.cloneState()

	ok, err := and.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, ok
}

func (p *parser) parseAndExpr(and *andExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAndExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	_, ok := p.parseExprWrap(and.expr)
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, ok
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAnyMatcher"))
	}

	if p.pt.rn == utf8.RuneError && p.pt.w == 0 {
		// EOF - see utf8.DecodeRune
		p.failAt(false, p.pt.position, ".")
		return nil, false
	}
	start := p.pt
	p.read()
	p.failAt(true, start.position, ".")
	return p.sliceFrom(start), true
}

func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseCharClassMatcher"))
	}

	cur := p.pt.rn
	start := p.pt

	// can't match EOF
	if cur == utf8.RuneError && p.pt.w == 0 { // see utf8.DecodeRune
		p.failAt(false, start.position, chr.val)
		return nil, false
	}

	if chr.ignoreCase {
		cur = unicode.ToLower(cur)
	}

	// try to match in the list of available chars
	for _, rn := range chr.chars {
		if rn == cur {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of ranges
	for i := 0; i < len(chr.ranges); i += 2 {
		if cur >= chr.ranges[i] && cur <= chr.ranges[i+1] {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of Unicode classes
	for _, cl := range chr.classes {
		if unicode.Is(cl, cur) {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	if chr.inverted {
		p.read()
		p.failAt(true, start.position, chr.val)
		return p.sliceFrom(start), true
	}
	p.failAt(false, start.position, chr.val)
	return nil, false
}

func (p *parser) incChoiceAltCnt(ch *choiceExpr, altI int) {
	choiceIdent := fmt.Sprintf("%s %d:%d", p.rstack[len(p.rstack)-1].name, ch.pos.line, ch.pos.col)
	m := p.ChoiceAltCnt[choiceIdent]
	if m == nil {
		m = make(map[string]int)
		p.ChoiceAltCnt[choiceIdent] = m
	}
	// We increment altI by 1, so the keys do not start at 0
	alt := strconv.Itoa(altI + 1)
	if altI == choiceNoMatch {
		alt = p.choiceNoMatch
	}
	m[alt]++
}

func (p *parser) parseChoiceExpr(ch *choiceExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseChoiceExpr"))
	}

	for altI, alt := range ch.alternatives {
		// dummy assignment to prevent compile error if optimized
		_ = altI

		state := p.cloneState()

		p.pushV()
		val, ok := p.parseExprWrap(alt)
		p.popV()
		if ok {
			p.incChoiceAltCnt(ch, altI)
			return val, ok
		}
		p.restoreState(state)
	}
	p.incChoiceAltCnt(ch, choiceNoMatch)
	return nil, false
}

func (p *parser) parseLabeledExpr(lab *labeledExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseLabeledExpr"))
	}

	p.pushV()
	val, ok := p.parseExprWrap(lab.expr)
	p.popV()
	if ok && lab.label != "" {
		m := p.vstack[len(p.vstack)-1]
		m[lab.label] = val
	}
	return val, ok
}

func (p *parser) parseLitMatcher(lit *litMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseLitMatcher"))
	}

	start := p.pt
	for _, want := range lit.val {
		cur := p.pt.rn
		if lit.ignoreCase {
			cur = unicode.ToLower(cur)
		}
		if cur != want {
			p.failAt(false, start.position, lit.want)
			p.restore(start)
			return nil, false
		}
		p.read()
	}
	p.failAt(true, start.position, lit.want)
	return p.sliceFrom(start), true
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseNotCodeExpr"))
	}

	state := p.cloneState()

	ok, err := not.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, !ok
}

func (p *parser) parseNotExpr(not *notExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseNotExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	_, ok := p.parseExprWrap(not.expr)
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, !ok
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseOneOrMoreExpr"))
	}

	var vals []any

	for {
		p.pushV()
		val, ok := p.parseExprWrap(expr.expr)
		p.popV()
		if !ok {
			if len(vals) == 0 {
				// did not match once, no match
				return nil, false
			}
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseRecoveryExpr(recover *recoveryExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRecoveryExpr (" + strings.Join(recover.failureLabel, ",") + ")"))
	}

	p.pushRecovery(recover.failureLabel, recover.recoverExpr)
	val, ok := p.parseExprWrap(recover.expr)
	p.popRecovery()

	return val, ok
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRuleRefExpr " + ref.name))
	}

	if ref.name == "" {
		panic(fmt.Sprintf("%s: invalid rule: missing name", ref.pos))
	}

	rule := p.rules[ref.name]
	if rule == nil {
		p.addErr(fmt.Errorf("undefined rule: %s", ref.name))
		return nil, false
	}
	return p.parseRuleWrap(rule)
}

func (p *parser) parseSeqExpr(seq *seqExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseSeqExpr"))
	}

	vals := make([]any, 0, len(seq.exprs))

	pt := p.pt
	state := p.cloneState()
	for _, expr := range seq.exprs {
		val, ok := p.parseExprWrap(expr)
		if !ok {
			p.restoreState(state)
			p.restore(pt)
			return nil, false
		}
		vals = append(vals, val)
	}
	return vals, true
}

func (p *parser) parseStateCodeExpr(state *stateCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseStateCodeExpr"))
	}

	err := state.run(p)
	if err != nil {
		p.addErr(err)
	}
	return nil, true
}

func (p *parser) parseThrowExpr(expr *throwExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseThrowExpr"))
	}

	for i := len(p.recoveryStack) - 1; i >= 0; i-- {
		if recoverExpr, ok := p.recoveryStack[i][expr.label]; ok {
			if val, ok := p.parseExprWrap(recoverExpr); ok {
				return val, ok
			}
		}
	}

	return nil, false
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrMoreExpr"))
	}

	var vals []any

	for {
		p.pushV()
		val, ok := p.parseExprWrap(expr.expr)
		p.popV()
		if !ok {
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrOneExpr"))
	}

	p.pushV()
	val, _ := p.parseExprWrap(expr.expr)
	p.popV()
	// whether it matched or not, consider it a match
	return val, true
}
