// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"time"
)

type Session struct {
	Sid         string
	Uid         int64
	ExpiresDttm time.Time
}

type User struct {
	Uid            int64
	Handle         string
	HashedPassword string
	Clan           string
	MagicKey       string
	Path           string
	Crdttm         time.Time
	Updttm         time.Time
}
