// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"time"
)

type Clan struct {
	Cid string
	Uid string
}

type Element struct {
	Cid    string
	Eid    string
	Kind   string
	Crdttm time.Time
}

type ElementMetadatum struct {
	Eid      string
	Tid      string
	ActionCd string
	Hex      string
	Crdttm   time.Time
}

type ElementsParent struct {
	Eid       string
	ParentEid string
}

type Input struct {
	ID     int64
	Status string
	Path   string
	Name   string
	Cksum  string
	Crdttm time.Time
	Updttm time.Time
}

type InputLine struct {
	Iid    int64
	SectNo int64
	LineNo int64
	Line   string
}

type LogMessage struct {
	ID      int64
	Arg1    string
	Arg2    string
	Arg3    string
	Message string
	Crdttm  time.Time
}

type Metadatum struct {
	Version       string
	InputPath     string
	OutputPath    string
	PublicPath    string
	TemplatesPath string
}

type Report struct {
	Tid    string
	Cid    string
	Rid    string
	Crdttm time.Time
}

type ReportQueue struct {
	Qid    string
	Cid    string
	Status string
	Crdttm time.Time
	Updttm time.Time
}

type ReportQueueDatum struct {
	Qid    string
	Name   string
	Cksum  string
	Lines  string
	Crdttm time.Time
}

type ReportSection struct {
	Rid    string
	Eid    string
	Lines  string
	Crdttm time.Time
}

type Role struct {
	Rlid string
}

type Session struct {
	Sid       string
	Uid       string
	ExpiresAt time.Time
}

type Turn struct {
	Tid    string
	Turn   string
	Year   int64
	Month  int64
	Crdttm time.Time
}

type User struct {
	Uid            string
	Username       string
	Email          string
	HashedPassword string
}

type UsersRole struct {
	Uid   string
	Rlid  string
	Value string
}
