// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"time"
)

type Role struct {
	Rid string
}

type Session struct {
	Sid       string
	Uid       string
	ExpiresAt time.Time
}

type User struct {
	Uid            string
	Username       string
	Email          string
	HashedPassword string
	Clan           string
}

type UsersRole struct {
	Uid   string
	Rid   string
	Value string
}
