// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: roles.sql

package sqlc

import (
	"context"
)

const readAllRoles = `-- name: ReadAllRoles :many
SELECT rid
FROM roles
`

func (q *Queries) ReadAllRoles(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, readAllRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var rid string
		if err := rows.Scan(&rid); err != nil {
			return nil, err
		}
		items = append(items, rid)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
