// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: users.sql

package sqlc

import (
	"context"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (uid, username, email, hashed_password, clan)
VALUES (?, ?, ?, ?, ?)
`

type CreateUserParams struct {
	Uid            string
	Username       string
	Email          string
	HashedPassword string
	Clan           string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.Uid,
		arg.Username,
		arg.Email,
		arg.HashedPassword,
		arg.Clan,
	)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE
FROM users
WHERE uid = ?
`

func (q *Queries) DeleteUser(ctx context.Context, uid string) error {
	_, err := q.db.ExecContext(ctx, deleteUser, uid)
	return err
}

const readUser = `-- name: ReadUser :one
SELECT username, email, clan
FROM users
WHERE uid = ?
`

type ReadUserRow struct {
	Username string
	Email    string
	Clan     string
}

func (q *Queries) ReadUser(ctx context.Context, uid string) (ReadUserRow, error) {
	row := q.db.QueryRowContext(ctx, readUser, uid)
	var i ReadUserRow
	err := row.Scan(&i.Username, &i.Email, &i.Clan)
	return i, err
}

const readUserAuthenticationData = `-- name: ReadUserAuthenticationData :one
SELECT uid, hashed_password
FROM users
WHERE username = ?
`

type ReadUserAuthenticationDataRow struct {
	Uid            string
	HashedPassword string
}

func (q *Queries) ReadUserAuthenticationData(ctx context.Context, username string) (ReadUserAuthenticationDataRow, error) {
	row := q.db.QueryRowContext(ctx, readUserAuthenticationData, username)
	var i ReadUserAuthenticationDataRow
	err := row.Scan(&i.Uid, &i.HashedPassword)
	return i, err
}

const readUsers = `-- name: ReadUsers :many
SELECT uid, username, email, clan
FROM users
ORDER BY username
`

type ReadUsersRow struct {
	Uid      string
	Username string
	Email    string
	Clan     string
}

func (q *Queries) ReadUsers(ctx context.Context) ([]ReadUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, readUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReadUsersRow
	for rows.Next() {
		var i ReadUsersRow
		if err := rows.Scan(
			&i.Uid,
			&i.Username,
			&i.Email,
			&i.Clan,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
