// Code generated by pigeon; DO NOT EDIT.

package parser

// NB: including all the imports make the parser generator run a bit more quickly.
import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"math"
	"os"
	"sort"
	"strconv"
	"strings"
	"sync"
	"unicode"
	"unicode/utf8"

	"github.com/mdhender/ottomap/internal/compass"
	"github.com/mdhender/ottomap/internal/direction"
	"github.com/mdhender/ottomap/internal/unit_movement"
	"github.com/mdhender/ottomap/internal/winds"
)

type Date_t struct {
	Year  int
	Month int
	Day   int
}

func (d Date_t) IsZero() bool {
	return d == Date_t{}
}

type Location_t struct {
	UnitId      string
	Message     string
	CurrentHex  string
	PreviousHex string
}

type CrowsNestObservation_t struct {
	Point   compass.Point_e
	Terrain string
}

type TurnInfo_t struct {
	CurrentTurn Date_t
	NextTurn    Date_t
}

func bdup(src []byte) []byte {
	dst := make([]byte, len(src))
	copy(dst, src)
	return dst
}

var g = &grammar{
	rules: []*rule{
		{
			name: "Noop",
			pos:  position{line: 60, col: 1, offset: 935},
			expr: &actionExpr{
				pos: position{line: 60, col: 9, offset: 943},
				run: (*parser).callonNoop1,
				expr: &ruleRefExpr{
					pos:  position{line: 60, col: 9, offset: 943},
					name: "EOF",
				},
			},
		},
		{
			name: "CrowsNestObservation",
			pos:  position{line: 64, col: 1, offset: 973},
			expr: &actionExpr{
				pos: position{line: 64, col: 25, offset: 997},
				run: (*parser).callonCrowsNestObservation1,
				expr: &seqExpr{
					pos: position{line: 64, col: 25, offset: 997},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 64, col: 25, offset: 997},
							label: "cs",
							expr: &ruleRefExpr{
								pos:  position{line: 64, col: 28, offset: 1000},
								name: "CROWSIGHTING",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 64, col: 41, offset: 1013},
							name: "SP",
						},
						&litMatcher{
							pos:        position{line: 64, col: 44, offset: 1016},
							val:        "-",
							ignoreCase: false,
							want:       "\"-\"",
						},
						&ruleRefExpr{
							pos:  position{line: 64, col: 48, offset: 1020},
							name: "SP",
						},
						&labeledExpr{
							pos:   position{line: 64, col: 51, offset: 1023},
							label: "cp",
							expr: &ruleRefExpr{
								pos:  position{line: 64, col: 54, offset: 1026},
								name: "COMPASSPOINT",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 64, col: 67, offset: 1039},
							name: "EOF",
						},
					},
				},
			},
		},
		{
			name: "FleetMovement",
			pos:  position{line: 72, col: 1, offset: 1161},
			expr: &actionExpr{
				pos: position{line: 72, col: 18, offset: 1178},
				run: (*parser).callonFleetMovement1,
				expr: &seqExpr{
					pos: position{line: 72, col: 18, offset: 1178},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 72, col: 18, offset: 1178},
							label: "ws",
							expr: &ruleRefExpr{
								pos:  position{line: 72, col: 21, offset: 1181},
								name: "WINDSTRENGTH",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 72, col: 34, offset: 1194},
							name: "SP",
						},
						&labeledExpr{
							pos:   position{line: 72, col: 37, offset: 1197},
							label: "d",
							expr: &ruleRefExpr{
								pos:  position{line: 72, col: 39, offset: 1199},
								name: "DIRECTION",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 72, col: 49, offset: 1209},
							name: "SP",
						},
						&litMatcher{
							pos:        position{line: 72, col: 52, offset: 1212},
							val:        "Fleet Movement:",
							ignoreCase: false,
							want:       "\"Fleet Movement:\"",
						},
						&ruleRefExpr{
							pos:  position{line: 72, col: 70, offset: 1230},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 72, col: 72, offset: 1232},
							label: "results",
							expr: &ruleRefExpr{
								pos:  position{line: 72, col: 80, offset: 1240},
								name: "ToEOL",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 72, col: 86, offset: 1246},
							name: "EOF",
						},
					},
				},
			},
		},
		{
			name: "Location",
			pos:  position{line: 82, col: 1, offset: 1486},
			expr: &actionExpr{
				pos: position{line: 82, col: 13, offset: 1498},
				run: (*parser).callonLocation1,
				expr: &seqExpr{
					pos: position{line: 82, col: 13, offset: 1498},
					exprs: []any{
						&choiceExpr{
							pos: position{line: 82, col: 14, offset: 1499},
							alternatives: []any{
								&litMatcher{
									pos:        position{line: 82, col: 14, offset: 1499},
									val:        "Courier",
									ignoreCase: false,
									want:       "\"Courier\"",
								},
								&litMatcher{
									pos:        position{line: 82, col: 26, offset: 1511},
									val:        "Element",
									ignoreCase: false,
									want:       "\"Element\"",
								},
								&litMatcher{
									pos:        position{line: 82, col: 38, offset: 1523},
									val:        "Fleet",
									ignoreCase: false,
									want:       "\"Fleet\"",
								},
								&litMatcher{
									pos:        position{line: 82, col: 48, offset: 1533},
									val:        "Garrison",
									ignoreCase: false,
									want:       "\"Garrison\"",
								},
								&litMatcher{
									pos:        position{line: 82, col: 61, offset: 1546},
									val:        "Tribe",
									ignoreCase: false,
									want:       "\"Tribe\"",
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 82, col: 70, offset: 1555},
							name: "SP",
						},
						&labeledExpr{
							pos:   position{line: 82, col: 73, offset: 1558},
							label: "u",
							expr: &ruleRefExpr{
								pos:  position{line: 82, col: 75, offset: 1560},
								name: "UNIT_ID",
							},
						},
						&litMatcher{
							pos:        position{line: 82, col: 83, offset: 1568},
							val:        ",",
							ignoreCase: false,
							want:       "\",\"",
						},
						&ruleRefExpr{
							pos:  position{line: 82, col: 87, offset: 1572},
							name: "SP",
						},
						&litMatcher{
							pos:        position{line: 82, col: 90, offset: 1575},
							val:        ",",
							ignoreCase: false,
							want:       "\",\"",
						},
						&ruleRefExpr{
							pos:  position{line: 82, col: 94, offset: 1579},
							name: "SP",
						},
						&litMatcher{
							pos:        position{line: 82, col: 97, offset: 1582},
							val:        "Current Hex =",
							ignoreCase: false,
							want:       "\"Current Hex =\"",
						},
						&ruleRefExpr{
							pos:  position{line: 82, col: 113, offset: 1598},
							name: "SP",
						},
						&labeledExpr{
							pos:   position{line: 82, col: 116, offset: 1601},
							label: "ch",
							expr: &ruleRefExpr{
								pos:  position{line: 82, col: 119, offset: 1604},
								name: "COORDS",
							},
						},
						&litMatcher{
							pos:        position{line: 82, col: 126, offset: 1611},
							val:        ",",
							ignoreCase: false,
							want:       "\",\"",
						},
						&ruleRefExpr{
							pos:  position{line: 82, col: 130, offset: 1615},
							name: "SP",
						},
						&litMatcher{
							pos:        position{line: 82, col: 133, offset: 1618},
							val:        "(Previous Hex =",
							ignoreCase: false,
							want:       "\"(Previous Hex =\"",
						},
						&ruleRefExpr{
							pos:  position{line: 82, col: 151, offset: 1636},
							name: "SP",
						},
						&labeledExpr{
							pos:   position{line: 82, col: 154, offset: 1639},
							label: "ph",
							expr: &ruleRefExpr{
								pos:  position{line: 82, col: 157, offset: 1642},
								name: "COORDS",
							},
						},
						&litMatcher{
							pos:        position{line: 82, col: 164, offset: 1649},
							val:        ")",
							ignoreCase: false,
							want:       "\")\"",
						},
						&ruleRefExpr{
							pos:  position{line: 82, col: 168, offset: 1653},
							name: "_",
						},
						&ruleRefExpr{
							pos:  position{line: 82, col: 170, offset: 1655},
							name: "EOF",
						},
					},
				},
			},
		},
		{
			name: "TribeFollows",
			pos:  position{line: 90, col: 1, offset: 1800},
			expr: &actionExpr{
				pos: position{line: 90, col: 17, offset: 1816},
				run: (*parser).callonTribeFollows1,
				expr: &seqExpr{
					pos: position{line: 90, col: 17, offset: 1816},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 90, col: 17, offset: 1816},
							val:        "Tribe Follows",
							ignoreCase: false,
							want:       "\"Tribe Follows\"",
						},
						&ruleRefExpr{
							pos:  position{line: 90, col: 33, offset: 1832},
							name: "SP",
						},
						&labeledExpr{
							pos:   position{line: 90, col: 36, offset: 1835},
							label: "u",
							expr: &ruleRefExpr{
								pos:  position{line: 90, col: 38, offset: 1837},
								name: "UNIT_ID",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 90, col: 46, offset: 1845},
							name: "_",
						},
						&ruleRefExpr{
							pos:  position{line: 90, col: 48, offset: 1847},
							name: "EOF",
						},
					},
				},
			},
		},
		{
			name: "TribeGoes",
			pos:  position{line: 94, col: 1, offset: 1874},
			expr: &actionExpr{
				pos: position{line: 94, col: 14, offset: 1887},
				run: (*parser).callonTribeGoes1,
				expr: &seqExpr{
					pos: position{line: 94, col: 14, offset: 1887},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 94, col: 14, offset: 1887},
							val:        "Tribe Goes to",
							ignoreCase: false,
							want:       "\"Tribe Goes to\"",
						},
						&ruleRefExpr{
							pos:  position{line: 94, col: 30, offset: 1903},
							name: "SP",
						},
						&labeledExpr{
							pos:   position{line: 94, col: 33, offset: 1906},
							label: "h",
							expr: &ruleRefExpr{
								pos:  position{line: 94, col: 35, offset: 1908},
								name: "COORDS",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 94, col: 42, offset: 1915},
							name: "_",
						},
						&ruleRefExpr{
							pos:  position{line: 94, col: 44, offset: 1917},
							name: "EOF",
						},
					},
				},
			},
		},
		{
			name: "TribeMovement",
			pos:  position{line: 98, col: 1, offset: 1944},
			expr: &actionExpr{
				pos: position{line: 98, col: 18, offset: 1961},
				run: (*parser).callonTribeMovement1,
				expr: &seqExpr{
					pos: position{line: 98, col: 18, offset: 1961},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 98, col: 18, offset: 1961},
							val:        "Tribe Movement:",
							ignoreCase: false,
							want:       "\"Tribe Movement:\"",
						},
						&ruleRefExpr{
							pos:  position{line: 98, col: 36, offset: 1979},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 98, col: 38, offset: 1981},
							label: "results",
							expr: &ruleRefExpr{
								pos:  position{line: 98, col: 46, offset: 1989},
								name: "ToEOL",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 98, col: 52, offset: 1995},
							name: "EOF",
						},
					},
				},
			},
		},
		{
			name: "TurnInfo",
			pos:  position{line: 106, col: 1, offset: 2143},
			expr: &actionExpr{
				pos: position{line: 106, col: 13, offset: 2155},
				run: (*parser).callonTurnInfo1,
				expr: &seqExpr{
					pos: position{line: 106, col: 13, offset: 2155},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 106, col: 13, offset: 2155},
							label: "cd",
							expr: &ruleRefExpr{
								pos:  position{line: 106, col: 16, offset: 2158},
								name: "CurrentTurn",
							},
						},
						&litMatcher{
							pos:        position{line: 106, col: 28, offset: 2170},
							val:        ",",
							ignoreCase: false,
							want:       "\",\"",
						},
						&ruleRefExpr{
							pos:  position{line: 106, col: 32, offset: 2174},
							name: "SP",
						},
						&ruleRefExpr{
							pos:  position{line: 106, col: 35, offset: 2177},
							name: "TurnSeason",
						},
						&litMatcher{
							pos:        position{line: 106, col: 46, offset: 2188},
							val:        ",",
							ignoreCase: false,
							want:       "\",\"",
						},
						&ruleRefExpr{
							pos:  position{line: 106, col: 50, offset: 2192},
							name: "SP",
						},
						&ruleRefExpr{
							pos:  position{line: 106, col: 53, offset: 2195},
							name: "TurnWeather",
						},
						&labeledExpr{
							pos:   position{line: 106, col: 65, offset: 2207},
							label: "nt",
							expr: &zeroOrOneExpr{
								pos: position{line: 106, col: 68, offset: 2210},
								expr: &ruleRefExpr{
									pos:  position{line: 106, col: 68, offset: 2210},
									name: "NextTurn",
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 106, col: 78, offset: 2220},
							name: "_",
						},
						&ruleRefExpr{
							pos:  position{line: 106, col: 80, offset: 2222},
							name: "EOF",
						},
					},
				},
			},
		},
		{
			name: "CurrentTurn",
			pos:  position{line: 119, col: 1, offset: 2440},
			expr: &actionExpr{
				pos: position{line: 119, col: 16, offset: 2455},
				run: (*parser).callonCurrentTurn1,
				expr: &seqExpr{
					pos: position{line: 119, col: 16, offset: 2455},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 119, col: 16, offset: 2455},
							val:        "Current Turn",
							ignoreCase: false,
							want:       "\"Current Turn\"",
						},
						&ruleRefExpr{
							pos:  position{line: 119, col: 31, offset: 2470},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 119, col: 33, offset: 2472},
							label: "cd",
							expr: &ruleRefExpr{
								pos:  position{line: 119, col: 36, offset: 2475},
								name: "YearMonth",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 119, col: 46, offset: 2485},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 119, col: 48, offset: 2487},
							val:        "(#",
							ignoreCase: false,
							want:       "\"(#\"",
						},
						&oneOrMoreExpr{
							pos: position{line: 119, col: 53, offset: 2492},
							expr: &ruleRefExpr{
								pos:  position{line: 119, col: 53, offset: 2492},
								name: "DIGIT",
							},
						},
						&litMatcher{
							pos:        position{line: 119, col: 60, offset: 2499},
							val:        ")",
							ignoreCase: false,
							want:       "\")\"",
						},
					},
				},
			},
		},
		{
			name: "NextTurn",
			pos:  position{line: 123, col: 1, offset: 2527},
			expr: &actionExpr{
				pos: position{line: 123, col: 13, offset: 2539},
				run: (*parser).callonNextTurn1,
				expr: &seqExpr{
					pos: position{line: 123, col: 13, offset: 2539},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 123, col: 13, offset: 2539},
							name: "SP",
						},
						&litMatcher{
							pos:        position{line: 123, col: 16, offset: 2542},
							val:        "Next Turn",
							ignoreCase: false,
							want:       "\"Next Turn\"",
						},
						&ruleRefExpr{
							pos:  position{line: 123, col: 28, offset: 2554},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 123, col: 30, offset: 2556},
							label: "nd",
							expr: &ruleRefExpr{
								pos:  position{line: 123, col: 33, offset: 2559},
								name: "YearMonth",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 123, col: 43, offset: 2569},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 123, col: 45, offset: 2571},
							val:        "(#",
							ignoreCase: false,
							want:       "\"(#\"",
						},
						&oneOrMoreExpr{
							pos: position{line: 123, col: 50, offset: 2576},
							expr: &ruleRefExpr{
								pos:  position{line: 123, col: 50, offset: 2576},
								name: "DIGIT",
							},
						},
						&litMatcher{
							pos:        position{line: 123, col: 57, offset: 2583},
							val:        "),",
							ignoreCase: false,
							want:       "\"),\"",
						},
						&ruleRefExpr{
							pos:  position{line: 123, col: 62, offset: 2588},
							name: "_",
						},
						&ruleRefExpr{
							pos:  position{line: 123, col: 64, offset: 2590},
							name: "ReportDate",
						},
					},
				},
			},
		},
		{
			name: "ReportDate",
			pos:  position{line: 127, col: 1, offset: 2625},
			expr: &actionExpr{
				pos: position{line: 127, col: 15, offset: 2639},
				run: (*parser).callonReportDate1,
				expr: &seqExpr{
					pos: position{line: 127, col: 15, offset: 2639},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 127, col: 15, offset: 2639},
							name: "DIGIT",
						},
						&zeroOrOneExpr{
							pos: position{line: 127, col: 21, offset: 2645},
							expr: &ruleRefExpr{
								pos:  position{line: 127, col: 21, offset: 2645},
								name: "DIGIT",
							},
						},
						&litMatcher{
							pos:        position{line: 127, col: 28, offset: 2652},
							val:        "/",
							ignoreCase: false,
							want:       "\"/\"",
						},
						&ruleRefExpr{
							pos:  position{line: 127, col: 32, offset: 2656},
							name: "DIGIT",
						},
						&zeroOrOneExpr{
							pos: position{line: 127, col: 38, offset: 2662},
							expr: &ruleRefExpr{
								pos:  position{line: 127, col: 38, offset: 2662},
								name: "DIGIT",
							},
						},
						&litMatcher{
							pos:        position{line: 127, col: 45, offset: 2669},
							val:        "/",
							ignoreCase: false,
							want:       "\"/\"",
						},
						&ruleRefExpr{
							pos:  position{line: 127, col: 49, offset: 2673},
							name: "DIGIT",
						},
						&ruleRefExpr{
							pos:  position{line: 127, col: 55, offset: 2679},
							name: "DIGIT",
						},
						&ruleRefExpr{
							pos:  position{line: 127, col: 61, offset: 2685},
							name: "DIGIT",
						},
						&ruleRefExpr{
							pos:  position{line: 127, col: 67, offset: 2691},
							name: "DIGIT",
						},
					},
				},
			},
		},
		{
			name: "ToEOL",
			pos:  position{line: 132, col: 1, offset: 2769},
			expr: &actionExpr{
				pos: position{line: 132, col: 10, offset: 2778},
				run: (*parser).callonToEOL1,
				expr: &seqExpr{
					pos: position{line: 132, col: 10, offset: 2778},
					exprs: []any{
						&zeroOrMoreExpr{
							pos: position{line: 132, col: 10, offset: 2778},
							expr: &anyMatcher{
								line: 132, col: 10, offset: 2778,
							},
						},
						&ruleRefExpr{
							pos:  position{line: 132, col: 13, offset: 2781},
							name: "EOF",
						},
					},
				},
			},
		},
		{
			name: "TurnSeason",
			pos:  position{line: 136, col: 1, offset: 2813},
			expr: &actionExpr{
				pos: position{line: 136, col: 15, offset: 2827},
				run: (*parser).callonTurnSeason1,
				expr: &seqExpr{
					pos: position{line: 136, col: 15, offset: 2827},
					exprs: []any{
						&charClassMatcher{
							pos:        position{line: 136, col: 15, offset: 2827},
							val:        "[A-Z]",
							ranges:     []rune{'A', 'Z'},
							ignoreCase: false,
							inverted:   false,
						},
						&oneOrMoreExpr{
							pos: position{line: 136, col: 20, offset: 2832},
							expr: &charClassMatcher{
								pos:        position{line: 136, col: 20, offset: 2832},
								val:        "[A-Za-z]",
								ranges:     []rune{'A', 'Z', 'a', 'z'},
								ignoreCase: false,
								inverted:   false,
							},
						},
					},
				},
			},
		},
		{
			name: "TurnWeather",
			pos:  position{line: 141, col: 1, offset: 2914},
			expr: &actionExpr{
				pos: position{line: 141, col: 16, offset: 2929},
				run: (*parser).callonTurnWeather1,
				expr: &seqExpr{
					pos: position{line: 141, col: 16, offset: 2929},
					exprs: []any{
						&charClassMatcher{
							pos:        position{line: 141, col: 16, offset: 2929},
							val:        "[A-Z]",
							ranges:     []rune{'A', 'Z'},
							ignoreCase: false,
							inverted:   false,
						},
						&oneOrMoreExpr{
							pos: position{line: 141, col: 21, offset: 2934},
							expr: &charClassMatcher{
								pos:        position{line: 141, col: 21, offset: 2934},
								val:        "[A-Za-z]",
								ranges:     []rune{'A', 'Z', 'a', 'z'},
								ignoreCase: false,
								inverted:   false,
							},
						},
					},
				},
			},
		},
		{
			name: "YearMonth",
			pos:  position{line: 146, col: 1, offset: 3017},
			expr: &actionExpr{
				pos: position{line: 146, col: 14, offset: 3030},
				run: (*parser).callonYearMonth1,
				expr: &seqExpr{
					pos: position{line: 146, col: 14, offset: 3030},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 146, col: 14, offset: 3030},
							label: "y",
							expr: &ruleRefExpr{
								pos:  position{line: 146, col: 16, offset: 3032},
								name: "YEAR",
							},
						},
						&litMatcher{
							pos:        position{line: 146, col: 21, offset: 3037},
							val:        "-",
							ignoreCase: false,
							want:       "\"-\"",
						},
						&labeledExpr{
							pos:   position{line: 146, col: 25, offset: 3041},
							label: "m",
							expr: &ruleRefExpr{
								pos:  position{line: 146, col: 27, offset: 3043},
								name: "MONTH",
							},
						},
					},
				},
			},
		},
		{
			name: "COMPASSPOINT",
			pos:  position{line: 153, col: 1, offset: 3133},
			expr: &choiceExpr{
				pos: position{line: 153, col: 17, offset: 3149},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 153, col: 17, offset: 3149},
						run: (*parser).callonCOMPASSPOINT2,
						expr: &litMatcher{
							pos:        position{line: 153, col: 17, offset: 3149},
							val:        "NE/NE",
							ignoreCase: false,
							want:       "\"NE/NE\"",
						},
					},
					&actionExpr{
						pos: position{line: 155, col: 5, offset: 3197},
						run: (*parser).callonCOMPASSPOINT4,
						expr: &litMatcher{
							pos:        position{line: 155, col: 5, offset: 3197},
							val:        "NE/SE",
							ignoreCase: false,
							want:       "\"NE/SE\"",
						},
					},
					&actionExpr{
						pos: position{line: 157, col: 5, offset: 3240},
						run: (*parser).callonCOMPASSPOINT6,
						expr: &litMatcher{
							pos:        position{line: 157, col: 5, offset: 3240},
							val:        "NW/NW",
							ignoreCase: false,
							want:       "\"NW/NW\"",
						},
					},
					&actionExpr{
						pos: position{line: 159, col: 5, offset: 3288},
						run: (*parser).callonCOMPASSPOINT8,
						expr: &litMatcher{
							pos:        position{line: 159, col: 5, offset: 3288},
							val:        "N/NE",
							ignoreCase: false,
							want:       "\"N/NE\"",
						},
					},
					&actionExpr{
						pos: position{line: 161, col: 5, offset: 3340},
						run: (*parser).callonCOMPASSPOINT10,
						expr: &litMatcher{
							pos:        position{line: 161, col: 5, offset: 3340},
							val:        "N/NW",
							ignoreCase: false,
							want:       "\"N/NW\"",
						},
					},
					&actionExpr{
						pos: position{line: 163, col: 5, offset: 3392},
						run: (*parser).callonCOMPASSPOINT12,
						expr: &litMatcher{
							pos:        position{line: 163, col: 5, offset: 3392},
							val:        "N/N",
							ignoreCase: false,
							want:       "\"N/N\"",
						},
					},
					&actionExpr{
						pos: position{line: 165, col: 5, offset: 3434},
						run: (*parser).callonCOMPASSPOINT14,
						expr: &litMatcher{
							pos:        position{line: 165, col: 5, offset: 3434},
							val:        "SE/SE",
							ignoreCase: false,
							want:       "\"SE/SE\"",
						},
					},
					&actionExpr{
						pos: position{line: 167, col: 5, offset: 3482},
						run: (*parser).callonCOMPASSPOINT16,
						expr: &litMatcher{
							pos:        position{line: 167, col: 5, offset: 3482},
							val:        "SW/NW",
							ignoreCase: false,
							want:       "\"SW/NW\"",
						},
					},
					&actionExpr{
						pos: position{line: 169, col: 5, offset: 3525},
						run: (*parser).callonCOMPASSPOINT18,
						expr: &litMatcher{
							pos:        position{line: 169, col: 5, offset: 3525},
							val:        "SW/SW",
							ignoreCase: false,
							want:       "\"SW/SW\"",
						},
					},
					&actionExpr{
						pos: position{line: 171, col: 5, offset: 3573},
						run: (*parser).callonCOMPASSPOINT20,
						expr: &litMatcher{
							pos:        position{line: 171, col: 5, offset: 3573},
							val:        "S/SE",
							ignoreCase: false,
							want:       "\"S/SE\"",
						},
					},
					&actionExpr{
						pos: position{line: 173, col: 5, offset: 3625},
						run: (*parser).callonCOMPASSPOINT22,
						expr: &litMatcher{
							pos:        position{line: 173, col: 5, offset: 3625},
							val:        "S/SW",
							ignoreCase: false,
							want:       "\"S/SW\"",
						},
					},
					&actionExpr{
						pos: position{line: 175, col: 5, offset: 3677},
						run: (*parser).callonCOMPASSPOINT24,
						expr: &litMatcher{
							pos:        position{line: 175, col: 5, offset: 3677},
							val:        "S/S",
							ignoreCase: false,
							want:       "\"S/S\"",
						},
					},
				},
			},
		},
		{
			name: "COORDS",
			pos:  position{line: 179, col: 1, offset: 3718},
			expr: &choiceExpr{
				pos: position{line: 179, col: 11, offset: 3728},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 179, col: 11, offset: 3728},
						run: (*parser).callonCOORDS2,
						expr: &litMatcher{
							pos:        position{line: 179, col: 11, offset: 3728},
							val:        "N/A",
							ignoreCase: false,
							want:       "\"N/A\"",
						},
					},
					&actionExpr{
						pos: position{line: 181, col: 5, offset: 3759},
						run: (*parser).callonCOORDS4,
						expr: &seqExpr{
							pos: position{line: 181, col: 5, offset: 3759},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 181, col: 5, offset: 3759},
									val:        "##",
									ignoreCase: false,
									want:       "\"##\"",
								},
								&ruleRefExpr{
									pos:  position{line: 181, col: 10, offset: 3764},
									name: "SP",
								},
								&ruleRefExpr{
									pos:  position{line: 181, col: 13, offset: 3767},
									name: "DIGIT",
								},
								&ruleRefExpr{
									pos:  position{line: 181, col: 19, offset: 3773},
									name: "DIGIT",
								},
								&ruleRefExpr{
									pos:  position{line: 181, col: 25, offset: 3779},
									name: "DIGIT",
								},
								&ruleRefExpr{
									pos:  position{line: 181, col: 31, offset: 3785},
									name: "DIGIT",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 183, col: 5, offset: 3828},
						run: (*parser).callonCOORDS12,
						expr: &seqExpr{
							pos: position{line: 183, col: 5, offset: 3828},
							exprs: []any{
								&ruleRefExpr{
									pos:  position{line: 183, col: 5, offset: 3828},
									name: "LETTER",
								},
								&ruleRefExpr{
									pos:  position{line: 183, col: 12, offset: 3835},
									name: "LETTER",
								},
								&ruleRefExpr{
									pos:  position{line: 183, col: 19, offset: 3842},
									name: "SP",
								},
								&ruleRefExpr{
									pos:  position{line: 183, col: 22, offset: 3845},
									name: "DIGIT",
								},
								&ruleRefExpr{
									pos:  position{line: 183, col: 28, offset: 3851},
									name: "DIGIT",
								},
								&ruleRefExpr{
									pos:  position{line: 183, col: 34, offset: 3857},
									name: "DIGIT",
								},
								&ruleRefExpr{
									pos:  position{line: 183, col: 40, offset: 3863},
									name: "DIGIT",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "CROWSIGHTING",
			pos:  position{line: 187, col: 1, offset: 3905},
			expr: &choiceExpr{
				pos: position{line: 187, col: 17, offset: 3921},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 187, col: 17, offset: 3921},
						run: (*parser).callonCROWSIGHTING2,
						expr: &litMatcher{
							pos:        position{line: 187, col: 17, offset: 3921},
							val:        "Sight Land",
							ignoreCase: false,
							want:       "\"Sight Land\"",
						},
					},
					&actionExpr{
						pos: position{line: 189, col: 5, offset: 3963},
						run: (*parser).callonCROWSIGHTING4,
						expr: &litMatcher{
							pos:        position{line: 189, col: 5, offset: 3963},
							val:        "Sight Water",
							ignoreCase: false,
							want:       "\"Sight Water\"",
						},
					},
				},
			},
		},
		{
			name: "DIRECTION",
			pos:  position{line: 194, col: 1, offset: 4007},
			expr: &choiceExpr{
				pos: position{line: 194, col: 14, offset: 4020},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 194, col: 14, offset: 4020},
						run: (*parser).callonDIRECTION2,
						expr: &litMatcher{
							pos:        position{line: 194, col: 14, offset: 4020},
							val:        "NE",
							ignoreCase: false,
							want:       "\"NE\"",
						},
					},
					&actionExpr{
						pos: position{line: 196, col: 5, offset: 4067},
						run: (*parser).callonDIRECTION4,
						expr: &litMatcher{
							pos:        position{line: 196, col: 5, offset: 4067},
							val:        "SE",
							ignoreCase: false,
							want:       "\"SE\"",
						},
					},
					&actionExpr{
						pos: position{line: 198, col: 5, offset: 4114},
						run: (*parser).callonDIRECTION6,
						expr: &litMatcher{
							pos:        position{line: 198, col: 5, offset: 4114},
							val:        "SW",
							ignoreCase: false,
							want:       "\"SW\"",
						},
					},
					&actionExpr{
						pos: position{line: 200, col: 5, offset: 4161},
						run: (*parser).callonDIRECTION8,
						expr: &litMatcher{
							pos:        position{line: 200, col: 5, offset: 4161},
							val:        "NW",
							ignoreCase: false,
							want:       "\"NW\"",
						},
					},
					&actionExpr{
						pos: position{line: 202, col: 5, offset: 4208},
						run: (*parser).callonDIRECTION10,
						expr: &litMatcher{
							pos:        position{line: 202, col: 5, offset: 4208},
							val:        "N",
							ignoreCase: false,
							want:       "\"N\"",
						},
					},
					&actionExpr{
						pos: position{line: 204, col: 5, offset: 4250},
						run: (*parser).callonDIRECTION12,
						expr: &litMatcher{
							pos:        position{line: 204, col: 5, offset: 4250},
							val:        "S",
							ignoreCase: false,
							want:       "\"S\"",
						},
					},
				},
			},
		},
		{
			name: "MONTH",
			pos:  position{line: 208, col: 1, offset: 4291},
			expr: &actionExpr{
				pos: position{line: 208, col: 10, offset: 4300},
				run: (*parser).callonMONTH1,
				expr: &seqExpr{
					pos: position{line: 208, col: 10, offset: 4300},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 208, col: 10, offset: 4300},
							name: "DIGIT",
						},
						&zeroOrOneExpr{
							pos: position{line: 208, col: 16, offset: 4306},
							expr: &ruleRefExpr{
								pos:  position{line: 208, col: 16, offset: 4306},
								name: "DIGIT",
							},
						},
					},
				},
			},
		},
		{
			name: "UNIT_ID",
			pos:  position{line: 213, col: 1, offset: 4382},
			expr: &actionExpr{
				pos: position{line: 213, col: 12, offset: 4393},
				run: (*parser).callonUNIT_ID1,
				expr: &seqExpr{
					pos: position{line: 213, col: 12, offset: 4393},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 213, col: 12, offset: 4393},
							name: "DIGIT",
						},
						&ruleRefExpr{
							pos:  position{line: 213, col: 18, offset: 4399},
							name: "DIGIT",
						},
						&ruleRefExpr{
							pos:  position{line: 213, col: 24, offset: 4405},
							name: "DIGIT",
						},
						&ruleRefExpr{
							pos:  position{line: 213, col: 30, offset: 4411},
							name: "DIGIT",
						},
						&zeroOrOneExpr{
							pos: position{line: 213, col: 36, offset: 4417},
							expr: &seqExpr{
								pos: position{line: 213, col: 37, offset: 4418},
								exprs: []any{
									&charClassMatcher{
										pos:        position{line: 213, col: 37, offset: 4418},
										val:        "[cefg]",
										chars:      []rune{'c', 'e', 'f', 'g'},
										ignoreCase: false,
										inverted:   false,
									},
									&charClassMatcher{
										pos:        position{line: 213, col: 44, offset: 4425},
										val:        "[1-9]",
										ranges:     []rune{'1', '9'},
										ignoreCase: false,
										inverted:   false,
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "WINDSTRENGTH",
			pos:  position{line: 217, col: 1, offset: 4469},
			expr: &choiceExpr{
				pos: position{line: 217, col: 17, offset: 4485},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 217, col: 17, offset: 4485},
						run: (*parser).callonWINDSTRENGTH2,
						expr: &litMatcher{
							pos:        position{line: 217, col: 17, offset: 4485},
							val:        "CALM",
							ignoreCase: false,
							want:       "\"CALM\"",
						},
					},
					&actionExpr{
						pos: position{line: 219, col: 5, offset: 4525},
						run: (*parser).callonWINDSTRENGTH4,
						expr: &litMatcher{
							pos:        position{line: 219, col: 5, offset: 4525},
							val:        "MILD",
							ignoreCase: false,
							want:       "\"MILD\"",
						},
					},
					&actionExpr{
						pos: position{line: 221, col: 5, offset: 4565},
						run: (*parser).callonWINDSTRENGTH6,
						expr: &litMatcher{
							pos:        position{line: 221, col: 5, offset: 4565},
							val:        "STRONG",
							ignoreCase: false,
							want:       "\"STRONG\"",
						},
					},
					&actionExpr{
						pos: position{line: 223, col: 5, offset: 4609},
						run: (*parser).callonWINDSTRENGTH8,
						expr: &litMatcher{
							pos:        position{line: 223, col: 5, offset: 4609},
							val:        "GALE",
							ignoreCase: false,
							want:       "\"GALE\"",
						},
					},
				},
			},
		},
		{
			name: "YEAR",
			pos:  position{line: 227, col: 1, offset: 4648},
			expr: &actionExpr{
				pos: position{line: 227, col: 9, offset: 4656},
				run: (*parser).callonYEAR1,
				expr: &seqExpr{
					pos: position{line: 227, col: 9, offset: 4656},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 227, col: 9, offset: 4656},
							name: "DIGIT",
						},
						&ruleRefExpr{
							pos:  position{line: 227, col: 15, offset: 4662},
							name: "DIGIT",
						},
						&ruleRefExpr{
							pos:  position{line: 227, col: 21, offset: 4668},
							name: "DIGIT",
						},
						&zeroOrOneExpr{
							pos: position{line: 227, col: 27, offset: 4674},
							expr: &ruleRefExpr{
								pos:  position{line: 227, col: 27, offset: 4674},
								name: "DIGIT",
							},
						},
					},
				},
			},
		},
		{
			name: "EOF",
			pos:  position{line: 233, col: 1, offset: 4751},
			expr: &notExpr{
				pos: position{line: 233, col: 10, offset: 4760},
				expr: &anyMatcher{
					line: 233, col: 11, offset: 4761,
				},
			},
		},
		{
			name: "DIGIT",
			pos:  position{line: 234, col: 1, offset: 4763},
			expr: &charClassMatcher{
				pos:        position{line: 234, col: 10, offset: 4772},
				val:        "[0-9]",
				ranges:     []rune{'0', '9'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "LETTER",
			pos:  position{line: 235, col: 1, offset: 4778},
			expr: &charClassMatcher{
				pos:        position{line: 235, col: 10, offset: 4787},
				val:        "[A-Z]",
				ranges:     []rune{'A', 'Z'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "SP",
			pos:  position{line: 236, col: 1, offset: 4793},
			expr: &oneOrMoreExpr{
				pos: position{line: 236, col: 10, offset: 4802},
				expr: &charClassMatcher{
					pos:        position{line: 236, col: 10, offset: 4802},
					val:        "[ \\t]",
					chars:      []rune{' ', '\t'},
					ignoreCase: false,
					inverted:   false,
				},
			},
		},
		{
			name: "_",
			pos:  position{line: 237, col: 1, offset: 4809},
			expr: &zeroOrMoreExpr{
				pos: position{line: 237, col: 10, offset: 4818},
				expr: &charClassMatcher{
					pos:        position{line: 237, col: 10, offset: 4818},
					val:        "[ \\t]",
					chars:      []rune{' ', '\t'},
					ignoreCase: false,
					inverted:   false,
				},
			},
		},
	},
}

func (c *current) onNoop1() (any, error) {
	return true, nil
}

func (p *parser) callonNoop1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNoop1()
}

func (c *current) onCrowsNestObservation1(cs, cp any) (any, error) {
	return CrowsNestObservation_t{
		Point:   cp.(compass.Point_e),
		Terrain: cs.(string),
	}, nil
}

func (p *parser) callonCrowsNestObservation1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCrowsNestObservation1(stack["cs"], stack["cp"])
}

func (c *current) onFleetMovement1(ws, d, results any) (any, error) {
	mt := Movement_t{Type: unit_movement.Fleet}
	mt.Winds.Strength = ws.(winds.Strength_e)
	mt.Winds.From = d.(direction.Direction_e)
	if results != nil {
		mt.Text = bdup(results.([]byte))
	}
	return mt, nil
}

func (p *parser) callonFleetMovement1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFleetMovement1(stack["ws"], stack["d"], stack["results"])
}

func (c *current) onLocation1(u, ch, ph any) (any, error) {
	return Location_t{
		UnitId:      u.(string),
		CurrentHex:  ch.(string),
		PreviousHex: ph.(string),
	}, nil
}

func (p *parser) callonLocation1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onLocation1(stack["u"], stack["ch"], stack["ph"])
}

func (c *current) onTribeFollows1(u any) (any, error) {
	return u, nil
}

func (p *parser) callonTribeFollows1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTribeFollows1(stack["u"])
}

func (c *current) onTribeGoes1(h any) (any, error) {
	return h, nil
}

func (p *parser) callonTribeGoes1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTribeGoes1(stack["h"])
}

func (c *current) onTribeMovement1(results any) (any, error) {
	mt := Movement_t{Type: unit_movement.Tribe}
	if results != nil {
		mt.Text = bdup(results.([]byte))
	}
	return mt, nil
}

func (p *parser) callonTribeMovement1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTribeMovement1(stack["results"])
}

func (c *current) onTurnInfo1(cd, nt any) (any, error) {
	if nt != nil {
		return TurnInfo_t{
			CurrentTurn: cd.(Date_t),
			NextTurn:    nt.(Date_t),
		}, nil
	}

	return TurnInfo_t{
		CurrentTurn: cd.(Date_t),
	}, nil
}

func (p *parser) callonTurnInfo1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTurnInfo1(stack["cd"], stack["nt"])
}

func (c *current) onCurrentTurn1(cd any) (any, error) {
	return cd, nil
}

func (p *parser) callonCurrentTurn1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCurrentTurn1(stack["cd"])
}

func (c *current) onNextTurn1(nd any) (any, error) {
	return nd, nil
}

func (p *parser) callonNextTurn1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNextTurn1(stack["nd"])
}

func (c *current) onReportDate1() (any, error) {
	//log.Printf("reportDate %q\n", c.text)
	return c.text, nil
}

func (p *parser) callonReportDate1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onReportDate1()
}

func (c *current) onToEOL1() (any, error) {
	return c.text, nil
}

func (p *parser) callonToEOL1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onToEOL1()
}

func (c *current) onTurnSeason1() (any, error) {
	//log.Printf("turnSeason %q\n", c.text)
	return c.text, nil
}

func (p *parser) callonTurnSeason1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTurnSeason1()
}

func (c *current) onTurnWeather1() (any, error) {
	//log.Printf("turnWeather %q\n", c.text)
	return c.text, nil
}

func (p *parser) callonTurnWeather1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTurnWeather1()
}

func (c *current) onYearMonth1(y, m any) (any, error) {
	return Date_t{
		Year:  y.(int),
		Month: m.(int),
	}, nil
}

func (p *parser) callonYearMonth1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onYearMonth1(stack["y"], stack["m"])
}

func (c *current) onCOMPASSPOINT2() (any, error) {
	return compass.NorthEast, nil
}

func (p *parser) callonCOMPASSPOINT2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCOMPASSPOINT2()
}

func (c *current) onCOMPASSPOINT4() (any, error) {
	return compass.East, nil
}

func (p *parser) callonCOMPASSPOINT4() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCOMPASSPOINT4()
}

func (c *current) onCOMPASSPOINT6() (any, error) {
	return compass.NorthWest, nil
}

func (p *parser) callonCOMPASSPOINT6() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCOMPASSPOINT6()
}

func (c *current) onCOMPASSPOINT8() (any, error) {
	return compass.NorthNorthEast, nil
}

func (p *parser) callonCOMPASSPOINT8() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCOMPASSPOINT8()
}

func (c *current) onCOMPASSPOINT10() (any, error) {
	return compass.NorthNorthWest, nil
}

func (p *parser) callonCOMPASSPOINT10() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCOMPASSPOINT10()
}

func (c *current) onCOMPASSPOINT12() (any, error) {
	return compass.North, nil
}

func (p *parser) callonCOMPASSPOINT12() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCOMPASSPOINT12()
}

func (c *current) onCOMPASSPOINT14() (any, error) {
	return compass.SouthEast, nil
}

func (p *parser) callonCOMPASSPOINT14() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCOMPASSPOINT14()
}

func (c *current) onCOMPASSPOINT16() (any, error) {
	return compass.West, nil
}

func (p *parser) callonCOMPASSPOINT16() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCOMPASSPOINT16()
}

func (c *current) onCOMPASSPOINT18() (any, error) {
	return compass.SouthWest, nil
}

func (p *parser) callonCOMPASSPOINT18() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCOMPASSPOINT18()
}

func (c *current) onCOMPASSPOINT20() (any, error) {
	return compass.SouthSouthEast, nil
}

func (p *parser) callonCOMPASSPOINT20() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCOMPASSPOINT20()
}

func (c *current) onCOMPASSPOINT22() (any, error) {
	return compass.SouthSouthWest, nil
}

func (p *parser) callonCOMPASSPOINT22() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCOMPASSPOINT22()
}

func (c *current) onCOMPASSPOINT24() (any, error) {
	return compass.South, nil
}

func (p *parser) callonCOMPASSPOINT24() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCOMPASSPOINT24()
}

func (c *current) onCOORDS2() (any, error) {
	return "", nil
}

func (p *parser) callonCOORDS2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCOORDS2()
}

func (c *current) onCOORDS4() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonCOORDS4() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCOORDS4()
}

func (c *current) onCOORDS12() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonCOORDS12() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCOORDS12()
}

func (c *current) onCROWSIGHTING2() (any, error) {
	return "Land", nil
}

func (p *parser) callonCROWSIGHTING2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCROWSIGHTING2()
}

func (c *current) onCROWSIGHTING4() (any, error) {
	return "Water", nil
}

func (p *parser) callonCROWSIGHTING4() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCROWSIGHTING4()
}

func (c *current) onDIRECTION2() (any, error) {
	return direction.NorthEast, nil
}

func (p *parser) callonDIRECTION2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDIRECTION2()
}

func (c *current) onDIRECTION4() (any, error) {
	return direction.SouthEast, nil
}

func (p *parser) callonDIRECTION4() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDIRECTION4()
}

func (c *current) onDIRECTION6() (any, error) {
	return direction.SouthWest, nil
}

func (p *parser) callonDIRECTION6() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDIRECTION6()
}

func (c *current) onDIRECTION8() (any, error) {
	return direction.NorthWest, nil
}

func (p *parser) callonDIRECTION8() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDIRECTION8()
}

func (c *current) onDIRECTION10() (any, error) {
	return direction.North, nil
}

func (p *parser) callonDIRECTION10() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDIRECTION10()
}

func (c *current) onDIRECTION12() (any, error) {
	return direction.South, nil
}

func (p *parser) callonDIRECTION12() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDIRECTION12()
}

func (c *current) onMONTH1() (any, error) {
	n, _ := strconv.Atoi(string(c.text))
	return int(n), nil
}

func (p *parser) callonMONTH1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMONTH1()
}

func (c *current) onUNIT_ID1() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonUNIT_ID1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onUNIT_ID1()
}

func (c *current) onWINDSTRENGTH2() (any, error) {
	return winds.Calm, nil
}

func (p *parser) callonWINDSTRENGTH2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onWINDSTRENGTH2()
}

func (c *current) onWINDSTRENGTH4() (any, error) {
	return winds.Mild, nil
}

func (p *parser) callonWINDSTRENGTH4() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onWINDSTRENGTH4()
}

func (c *current) onWINDSTRENGTH6() (any, error) {
	return winds.Strong, nil
}

func (p *parser) callonWINDSTRENGTH6() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onWINDSTRENGTH6()
}

func (c *current) onWINDSTRENGTH8() (any, error) {
	return winds.Gale, nil
}

func (p *parser) callonWINDSTRENGTH8() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onWINDSTRENGTH8()
}

func (c *current) onYEAR1() (any, error) {
	n, _ := strconv.Atoi(string(c.text))
	return int(n), nil
}

func (p *parser) callonYEAR1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onYEAR1()
}

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEntrypoint is returned when the specified entrypoint rule
	// does not exit.
	errInvalidEntrypoint = errors.New("invalid entrypoint")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errMaxExprCnt is used to signal that the maximum number of
	// expressions have been parsed.
	errMaxExprCnt = errors.New("max number of expresssions parsed")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// MaxExpressions creates an Option to stop parsing after the provided
// number of expressions have been parsed, if the value is 0 then the parser will
// parse for as many steps as needed (possibly an infinite number).
//
// The default for maxExprCnt is 0.
func MaxExpressions(maxExprCnt uint64) Option {
	return func(p *parser) Option {
		oldMaxExprCnt := p.maxExprCnt
		p.maxExprCnt = maxExprCnt
		return MaxExpressions(oldMaxExprCnt)
	}
}

// Entrypoint creates an Option to set the rule name to use as entrypoint.
// The rule name must have been specified in the -alternate-entrypoints
// if generating the parser with the -optimize-grammar flag, otherwise
// it may have been optimized out. Passing an empty string sets the
// entrypoint to the first rule in the grammar.
//
// The default is to start parsing at the first rule in the grammar.
func Entrypoint(ruleName string) Option {
	return func(p *parser) Option {
		oldEntrypoint := p.entrypoint
		p.entrypoint = ruleName
		if ruleName == "" {
			p.entrypoint = g.rules[0].name
		}
		return Entrypoint(oldEntrypoint)
	}
}

// Statistics adds a user provided Stats struct to the parser to allow
// the user to process the results after the parsing has finished.
// Also the key for the "no match" counter is set.
//
// Example usage:
//
//	input := "input"
//	stats := Stats{}
//	_, err := Parse("input-file", []byte(input), Statistics(&stats, "no match"))
//	if err != nil {
//	    log.Panicln(err)
//	}
//	b, err := json.MarshalIndent(stats.ChoiceAltCnt, "", "  ")
//	if err != nil {
//	    log.Panicln(err)
//	}
//	fmt.Println(string(b))
func Statistics(stats *Stats, choiceNoMatch string) Option {
	return func(p *parser) Option {
		oldStats := p.Stats
		p.Stats = stats
		oldChoiceNoMatch := p.choiceNoMatch
		p.choiceNoMatch = choiceNoMatch
		if p.Stats.ChoiceAltCnt == nil {
			p.Stats.ChoiceAltCnt = make(map[string]map[string]int)
		}
		return Statistics(oldStats, oldChoiceNoMatch)
	}
}

// Debug creates an Option to set the debug flag to b. When set to true,
// debugging information is printed to stdout while parsing.
//
// The default is false.
func Debug(b bool) Option {
	return func(p *parser) Option {
		old := p.debug
		p.debug = b
		return Debug(old)
	}
}

// Memoize creates an Option to set the memoize flag to b. When set to true,
// the parser will cache all results so each expression is evaluated only
// once. This guarantees linear parsing time even for pathological cases,
// at the expense of more memory and slower times for typical cases.
//
// The default is false.
func Memoize(b bool) Option {
	return func(p *parser) Option {
		old := p.memoize
		p.memoize = b
		return Memoize(old)
	}
}

// AllowInvalidUTF8 creates an Option to allow invalid UTF-8 bytes.
// Every invalid UTF-8 byte is treated as a utf8.RuneError (U+FFFD)
// by character class matchers and is matched by the any matcher.
// The returned matched value, c.text and c.offset are NOT affected.
//
// The default is false.
func AllowInvalidUTF8(b bool) Option {
	return func(p *parser) Option {
		old := p.allowInvalidUTF8
		p.allowInvalidUTF8 = b
		return AllowInvalidUTF8(old)
	}
}

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option {
	return func(p *parser) Option {
		old := p.recover
		p.recover = b
		return Recover(old)
	}
}

// GlobalStore creates an Option to set a key to a certain value in
// the globalStore.
func GlobalStore(key string, value any) Option {
	return func(p *parser) Option {
		old := p.cur.globalStore[key]
		p.cur.globalStore[key] = value
		return GlobalStore(key, old)
	}
}

// InitState creates an Option to set a key to a certain value in
// the global "state" store.
func InitState(key string, value any) Option {
	return func(p *parser) Option {
		old := p.cur.state[key]
		p.cur.state[key] = value
		return InitState(key, old)
	}
}

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (i any, err error) {
	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer func() {
		if closeErr := f.Close(); closeErr != nil {
			err = closeErr
		}
	}()
	return ParseReader(filename, f, opts...)
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (any, error) {
	b, err := io.ReadAll(r)
	if err != nil {
		return nil, err
	}

	return Parse(filename, b, opts...)
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (any, error) {
	return newParser(filename, b, opts...).parse(g)
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string {
	return strconv.Itoa(p.line) + ":" + strconv.Itoa(p.col) + " [" + strconv.Itoa(p.offset) + "]"
}

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match

	// state is a store for arbitrary key,value pairs that the user wants to be
	// tied to the backtracking of the parser.
	// This is always rolled back if a parsing rule fails.
	state storeDict

	// globalStore is a general store for the user to store arbitrary key-value
	// pairs that they need to manage and that they do not want tied to the
	// backtracking of the parser. This is only modified by the user and never
	// rolled back by the parser. It is always up to the user to keep this in a
	// consistent state.
	globalStore storeDict
}

type storeDict map[string]any

// the AST types...

type grammar struct {
	pos   position
	rules []*rule
}

type rule struct {
	pos         position
	name        string
	displayName string
	expr        any
}

type choiceExpr struct {
	pos          position
	alternatives []any
}

type actionExpr struct {
	pos  position
	expr any
	run  func(*parser) (any, error)
}

type recoveryExpr struct {
	pos          position
	expr         any
	recoverExpr  any
	failureLabel []string
}

type seqExpr struct {
	pos   position
	exprs []any
}

type throwExpr struct {
	pos   position
	label string
}

type labeledExpr struct {
	pos   position
	label string
	expr  any
}

type expr struct {
	pos  position
	expr any
}

type (
	andExpr        expr
	notExpr        expr
	zeroOrOneExpr  expr
	zeroOrMoreExpr expr
	oneOrMoreExpr  expr
)

type ruleRefExpr struct {
	pos  position
	name string
}

type stateCodeExpr struct {
	pos position
	run func(*parser) error
}

type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
	want       string
}

type charClassMatcher struct {
	pos             position
	val             string
	basicLatinChars [128]bool
	chars           []rune
	ranges          []rune
	classes         []*unicode.RangeTable
	ignoreCase      bool
	inverted        bool
}

type anyMatcher position

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) {
	*e = append(*e, err)
}

func (e errList) err() error {
	if len(e) == 0 {
		return nil
	}
	e.dedupe()
	return e
}

func (e *errList) dedupe() {
	var cleaned []error
	set := make(map[string]bool)
	for _, err := range *e {
		if msg := err.Error(); !set[msg] {
			set[msg] = true
			cleaned = append(cleaned, err)
		}
	}
	*e = cleaned
}

func (e errList) Error() string {
	switch len(e) {
	case 0:
		return ""
	case 1:
		return e[0].Error()
	default:
		var buf bytes.Buffer

		for i, err := range e {
			if i > 0 {
				buf.WriteRune('\n')
			}
			buf.WriteString(err.Error())
		}
		return buf.String()
	}
}

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner    error
	pos      position
	prefix   string
	expected []string
}

// Error returns the error message.
func (p *parserError) Error() string {
	return p.prefix + ": " + p.Inner.Error()
}

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	stats := Stats{
		ChoiceAltCnt: make(map[string]map[string]int),
	}

	p := &parser{
		filename: filename,
		errs:     new(errList),
		data:     b,
		pt:       savepoint{position: position{line: 1}},
		recover:  true,
		cur: current{
			state:       make(storeDict),
			globalStore: make(storeDict),
		},
		maxFailPos:      position{col: 1, line: 1},
		maxFailExpected: make([]string, 0, 20),
		Stats:           &stats,
		// start rule is rule [0] unless an alternate entrypoint is specified
		entrypoint: g.rules[0].name,
	}
	p.setOptions(opts)

	if p.maxExprCnt == 0 {
		p.maxExprCnt = math.MaxUint64
	}

	return p
}

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) {
	for _, opt := range opts {
		opt(p)
	}
}

type resultTuple struct {
	v   any
	b   bool
	end savepoint
}

const choiceNoMatch = -1

// Stats stores some statistics, gathered during parsing
type Stats struct {
	// ExprCnt counts the number of expressions processed during parsing
	// This value is compared to the maximum number of expressions allowed
	// (set by the MaxExpressions option).
	ExprCnt uint64

	// ChoiceAltCnt is used to count for each ordered choice expression,
	// which alternative is used how may times.
	// These numbers allow to optimize the order of the ordered choice expression
	// to increase the performance of the parser
	//
	// The outer key of ChoiceAltCnt is composed of the name of the rule as well
	// as the line and the column of the ordered choice.
	// The inner key of ChoiceAltCnt is the number (one-based) of the matching alternative.
	// For each alternative the number of matches are counted. If an ordered choice does not
	// match, a special counter is incremented. The name of this counter is set with
	// the parser option Statistics.
	// For an alternative to be included in ChoiceAltCnt, it has to match at least once.
	ChoiceAltCnt map[string]map[string]int
}

type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	depth   int
	recover bool
	debug   bool

	memoize bool
	// memoization table for the packrat algorithm:
	// map[offset in source] map[expression or rule] {value, match}
	memo map[int]map[any]resultTuple

	// rules table, maps the rule identifier to the rule node
	rules map[string]*rule
	// variables stack, map of label to value
	vstack []map[string]any
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// parse fail
	maxFailPos            position
	maxFailExpected       []string
	maxFailInvertExpected bool

	// max number of expressions to be parsed
	maxExprCnt uint64
	// entrypoint for the parser
	entrypoint string

	allowInvalidUTF8 bool

	*Stats

	choiceNoMatch string
	// recovery expression stack, keeps track of the currently available recovery expression, these are traversed in reverse
	recoveryStack []map[string]any
}

// push a variable set on the vstack.
func (p *parser) pushV() {
	if cap(p.vstack) == len(p.vstack) {
		// create new empty slot in the stack
		p.vstack = append(p.vstack, nil)
	} else {
		// slice to 1 more
		p.vstack = p.vstack[:len(p.vstack)+1]
	}

	// get the last args set
	m := p.vstack[len(p.vstack)-1]
	if m != nil && len(m) == 0 {
		// empty map, all good
		return
	}

	m = make(map[string]any)
	p.vstack[len(p.vstack)-1] = m
}

// pop a variable set from the vstack.
func (p *parser) popV() {
	// if the map is not empty, clear it
	m := p.vstack[len(p.vstack)-1]
	if len(m) > 0 {
		// GC that map
		p.vstack[len(p.vstack)-1] = nil
	}
	p.vstack = p.vstack[:len(p.vstack)-1]
}

// push a recovery expression with its labels to the recoveryStack
func (p *parser) pushRecovery(labels []string, expr any) {
	if cap(p.recoveryStack) == len(p.recoveryStack) {
		// create new empty slot in the stack
		p.recoveryStack = append(p.recoveryStack, nil)
	} else {
		// slice to 1 more
		p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)+1]
	}

	m := make(map[string]any, len(labels))
	for _, fl := range labels {
		m[fl] = expr
	}
	p.recoveryStack[len(p.recoveryStack)-1] = m
}

// pop a recovery expression from the recoveryStack
func (p *parser) popRecovery() {
	// GC that map
	p.recoveryStack[len(p.recoveryStack)-1] = nil

	p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)-1]
}

func (p *parser) print(prefix, s string) string {
	if !p.debug {
		return s
	}

	fmt.Printf("%s %d:%d:%d: %s [%#U]\n",
		prefix, p.pt.line, p.pt.col, p.pt.offset, s, p.pt.rn)
	return s
}

func (p *parser) printIndent(mark string, s string) string {
	return p.print(strings.Repeat(" ", p.depth)+mark, s)
}

func (p *parser) in(s string) string {
	res := p.printIndent(">", s)
	p.depth++
	return res
}

func (p *parser) out(s string) string {
	p.depth--
	return p.printIndent("<", s)
}

func (p *parser) addErr(err error) {
	p.addErrAt(err, p.pt.position, []string{})
}

func (p *parser) addErrAt(err error, pos position, expected []string) {
	var buf bytes.Buffer
	if p.filename != "" {
		buf.WriteString(p.filename)
	}
	if buf.Len() > 0 {
		buf.WriteString(":")
	}
	buf.WriteString(fmt.Sprintf("%d:%d (%d)", pos.line, pos.col, pos.offset))
	if len(p.rstack) > 0 {
		if buf.Len() > 0 {
			buf.WriteString(": ")
		}
		rule := p.rstack[len(p.rstack)-1]
		if rule.displayName != "" {
			buf.WriteString("rule " + rule.displayName)
		} else {
			buf.WriteString("rule " + rule.name)
		}
	}
	pe := &parserError{Inner: err, pos: pos, prefix: buf.String(), expected: expected}
	p.errs.add(pe)
}

func (p *parser) failAt(fail bool, pos position, want string) {
	// process fail if parsing fails and not inverted or parsing succeeds and invert is set
	if fail == p.maxFailInvertExpected {
		if pos.offset < p.maxFailPos.offset {
			return
		}

		if pos.offset > p.maxFailPos.offset {
			p.maxFailPos = pos
			p.maxFailExpected = p.maxFailExpected[:0]
		}

		if p.maxFailInvertExpected {
			want = "!" + want
		}
		p.maxFailExpected = append(p.maxFailExpected, want)
	}
}

// read advances the parser to the next rune.
func (p *parser) read() {
	p.pt.offset += p.pt.w
	rn, n := utf8.DecodeRune(p.data[p.pt.offset:])
	p.pt.rn = rn
	p.pt.w = n
	p.pt.col++
	if rn == '\n' {
		p.pt.line++
		p.pt.col = 0
	}

	if rn == utf8.RuneError && n == 1 { // see utf8.DecodeRune
		if !p.allowInvalidUTF8 {
			p.addErr(errInvalidEncoding)
		}
	}
}

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) {
	if p.debug {
		defer p.out(p.in("restore"))
	}
	if pt.offset == p.pt.offset {
		return
	}
	p.pt = pt
}

// Cloner is implemented by any value that has a Clone method, which returns a
// copy of the value. This is mainly used for types which are not passed by
// value (e.g map, slice, chan) or structs that contain such types.
//
// This is used in conjunction with the global state feature to create proper
// copies of the state to allow the parser to properly restore the state in
// the case of backtracking.
type Cloner interface {
	Clone() any
}

var statePool = &sync.Pool{
	New: func() any { return make(storeDict) },
}

func (sd storeDict) Discard() {
	for k := range sd {
		delete(sd, k)
	}
	statePool.Put(sd)
}

// clone and return parser current state.
func (p *parser) cloneState() storeDict {
	if p.debug {
		defer p.out(p.in("cloneState"))
	}

	state := statePool.Get().(storeDict)
	for k, v := range p.cur.state {
		if c, ok := v.(Cloner); ok {
			state[k] = c.Clone()
		} else {
			state[k] = v
		}
	}
	return state
}

// restore parser current state to the state storeDict.
// every restoreState should applied only one time for every cloned state
func (p *parser) restoreState(state storeDict) {
	if p.debug {
		defer p.out(p.in("restoreState"))
	}
	p.cur.state.Discard()
	p.cur.state = state
}

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte {
	return p.data[start.position.offset:p.pt.position.offset]
}

func (p *parser) getMemoized(node any) (resultTuple, bool) {
	if len(p.memo) == 0 {
		return resultTuple{}, false
	}
	m := p.memo[p.pt.offset]
	if len(m) == 0 {
		return resultTuple{}, false
	}
	res, ok := m[node]
	return res, ok
}

func (p *parser) setMemoized(pt savepoint, node any, tuple resultTuple) {
	if p.memo == nil {
		p.memo = make(map[int]map[any]resultTuple)
	}
	m := p.memo[pt.offset]
	if m == nil {
		m = make(map[any]resultTuple)
		p.memo[pt.offset] = m
	}
	m[node] = tuple
}

func (p *parser) buildRulesTable(g *grammar) {
	p.rules = make(map[string]*rule, len(g.rules))
	for _, r := range g.rules {
		p.rules[r.name] = r
	}
}

func (p *parser) parse(g *grammar) (val any, err error) {
	if len(g.rules) == 0 {
		p.addErr(errNoRule)
		return nil, p.errs.err()
	}

	// TODO : not super critical but this could be generated
	p.buildRulesTable(g)

	if p.recover {
		// panic can be used in action code to stop parsing immediately
		// and return the panic as an error.
		defer func() {
			if e := recover(); e != nil {
				if p.debug {
					defer p.out(p.in("panic handler"))
				}
				val = nil
				switch e := e.(type) {
				case error:
					p.addErr(e)
				default:
					p.addErr(fmt.Errorf("%v", e))
				}
				err = p.errs.err()
			}
		}()
	}

	startRule, ok := p.rules[p.entrypoint]
	if !ok {
		p.addErr(errInvalidEntrypoint)
		return nil, p.errs.err()
	}

	p.read() // advance to first rune
	val, ok = p.parseRuleWrap(startRule)
	if !ok {
		if len(*p.errs) == 0 {
			// If parsing fails, but no errors have been recorded, the expected values
			// for the farthest parser position are returned as error.
			maxFailExpectedMap := make(map[string]struct{}, len(p.maxFailExpected))
			for _, v := range p.maxFailExpected {
				maxFailExpectedMap[v] = struct{}{}
			}
			expected := make([]string, 0, len(maxFailExpectedMap))
			eof := false
			if _, ok := maxFailExpectedMap["!."]; ok {
				delete(maxFailExpectedMap, "!.")
				eof = true
			}
			for k := range maxFailExpectedMap {
				expected = append(expected, k)
			}
			sort.Strings(expected)
			if eof {
				expected = append(expected, "EOF")
			}
			p.addErrAt(errors.New("no match found, expected: "+listJoin(expected, ", ", "or")), p.maxFailPos, expected)
		}

		return nil, p.errs.err()
	}
	return val, p.errs.err()
}

func listJoin(list []string, sep string, lastSep string) string {
	switch len(list) {
	case 0:
		return ""
	case 1:
		return list[0]
	default:
		return strings.Join(list[:len(list)-1], sep) + " " + lastSep + " " + list[len(list)-1]
	}
}

func (p *parser) parseRuleMemoize(rule *rule) (any, bool) {
	res, ok := p.getMemoized(rule)
	if ok {
		p.restore(res.end)
		return res.v, res.b
	}

	startMark := p.pt
	val, ok := p.parseRule(rule)
	p.setMemoized(startMark, rule, resultTuple{val, ok, p.pt})

	return val, ok
}

func (p *parser) parseRuleWrap(rule *rule) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRule " + rule.name))
	}
	var (
		val       any
		ok        bool
		startMark = p.pt
	)

	if p.memoize {
		val, ok = p.parseRuleMemoize(rule)
	} else {
		val, ok = p.parseRule(rule)
	}

	if ok && p.debug {
		p.printIndent("MATCH", string(p.sliceFrom(startMark)))
	}
	return val, ok
}

func (p *parser) parseRule(rule *rule) (any, bool) {
	p.rstack = append(p.rstack, rule)
	p.pushV()
	val, ok := p.parseExprWrap(rule.expr)
	p.popV()
	p.rstack = p.rstack[:len(p.rstack)-1]
	return val, ok
}

func (p *parser) parseExprWrap(expr any) (any, bool) {
	var pt savepoint

	if p.memoize {
		res, ok := p.getMemoized(expr)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
		pt = p.pt
	}

	val, ok := p.parseExpr(expr)

	if p.memoize {
		p.setMemoized(pt, expr, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseExpr(expr any) (any, bool) {
	p.ExprCnt++
	if p.ExprCnt > p.maxExprCnt {
		panic(errMaxExprCnt)
	}

	var val any
	var ok bool
	switch expr := expr.(type) {
	case *actionExpr:
		val, ok = p.parseActionExpr(expr)
	case *andCodeExpr:
		val, ok = p.parseAndCodeExpr(expr)
	case *andExpr:
		val, ok = p.parseAndExpr(expr)
	case *anyMatcher:
		val, ok = p.parseAnyMatcher(expr)
	case *charClassMatcher:
		val, ok = p.parseCharClassMatcher(expr)
	case *choiceExpr:
		val, ok = p.parseChoiceExpr(expr)
	case *labeledExpr:
		val, ok = p.parseLabeledExpr(expr)
	case *litMatcher:
		val, ok = p.parseLitMatcher(expr)
	case *notCodeExpr:
		val, ok = p.parseNotCodeExpr(expr)
	case *notExpr:
		val, ok = p.parseNotExpr(expr)
	case *oneOrMoreExpr:
		val, ok = p.parseOneOrMoreExpr(expr)
	case *recoveryExpr:
		val, ok = p.parseRecoveryExpr(expr)
	case *ruleRefExpr:
		val, ok = p.parseRuleRefExpr(expr)
	case *seqExpr:
		val, ok = p.parseSeqExpr(expr)
	case *stateCodeExpr:
		val, ok = p.parseStateCodeExpr(expr)
	case *throwExpr:
		val, ok = p.parseThrowExpr(expr)
	case *zeroOrMoreExpr:
		val, ok = p.parseZeroOrMoreExpr(expr)
	case *zeroOrOneExpr:
		val, ok = p.parseZeroOrOneExpr(expr)
	default:
		panic(fmt.Sprintf("unknown expression type %T", expr))
	}
	return val, ok
}

func (p *parser) parseActionExpr(act *actionExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseActionExpr"))
	}

	start := p.pt
	val, ok := p.parseExprWrap(act.expr)
	if ok {
		p.cur.pos = start.position
		p.cur.text = p.sliceFrom(start)
		state := p.cloneState()
		actVal, err := act.run(p)
		if err != nil {
			p.addErrAt(err, start.position, []string{})
		}
		p.restoreState(state)

		val = actVal
	}
	if ok && p.debug {
		p.printIndent("MATCH", string(p.sliceFrom(start)))
	}
	return val, ok
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAndCodeExpr"))
	}

	state := p.cloneState()

	ok, err := and.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, ok
}

func (p *parser) parseAndExpr(and *andExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAndExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	_, ok := p.parseExprWrap(and.expr)
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, ok
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAnyMatcher"))
	}

	if p.pt.rn == utf8.RuneError && p.pt.w == 0 {
		// EOF - see utf8.DecodeRune
		p.failAt(false, p.pt.position, ".")
		return nil, false
	}
	start := p.pt
	p.read()
	p.failAt(true, start.position, ".")
	return p.sliceFrom(start), true
}

func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseCharClassMatcher"))
	}

	cur := p.pt.rn
	start := p.pt

	// can't match EOF
	if cur == utf8.RuneError && p.pt.w == 0 { // see utf8.DecodeRune
		p.failAt(false, start.position, chr.val)
		return nil, false
	}

	if chr.ignoreCase {
		cur = unicode.ToLower(cur)
	}

	// try to match in the list of available chars
	for _, rn := range chr.chars {
		if rn == cur {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of ranges
	for i := 0; i < len(chr.ranges); i += 2 {
		if cur >= chr.ranges[i] && cur <= chr.ranges[i+1] {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of Unicode classes
	for _, cl := range chr.classes {
		if unicode.Is(cl, cur) {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	if chr.inverted {
		p.read()
		p.failAt(true, start.position, chr.val)
		return p.sliceFrom(start), true
	}
	p.failAt(false, start.position, chr.val)
	return nil, false
}

func (p *parser) incChoiceAltCnt(ch *choiceExpr, altI int) {
	choiceIdent := fmt.Sprintf("%s %d:%d", p.rstack[len(p.rstack)-1].name, ch.pos.line, ch.pos.col)
	m := p.ChoiceAltCnt[choiceIdent]
	if m == nil {
		m = make(map[string]int)
		p.ChoiceAltCnt[choiceIdent] = m
	}
	// We increment altI by 1, so the keys do not start at 0
	alt := strconv.Itoa(altI + 1)
	if altI == choiceNoMatch {
		alt = p.choiceNoMatch
	}
	m[alt]++
}

func (p *parser) parseChoiceExpr(ch *choiceExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseChoiceExpr"))
	}

	for altI, alt := range ch.alternatives {
		// dummy assignment to prevent compile error if optimized
		_ = altI

		state := p.cloneState()

		p.pushV()
		val, ok := p.parseExprWrap(alt)
		p.popV()
		if ok {
			p.incChoiceAltCnt(ch, altI)
			return val, ok
		}
		p.restoreState(state)
	}
	p.incChoiceAltCnt(ch, choiceNoMatch)
	return nil, false
}

func (p *parser) parseLabeledExpr(lab *labeledExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseLabeledExpr"))
	}

	p.pushV()
	val, ok := p.parseExprWrap(lab.expr)
	p.popV()
	if ok && lab.label != "" {
		m := p.vstack[len(p.vstack)-1]
		m[lab.label] = val
	}
	return val, ok
}

func (p *parser) parseLitMatcher(lit *litMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseLitMatcher"))
	}

	start := p.pt
	for _, want := range lit.val {
		cur := p.pt.rn
		if lit.ignoreCase {
			cur = unicode.ToLower(cur)
		}
		if cur != want {
			p.failAt(false, start.position, lit.want)
			p.restore(start)
			return nil, false
		}
		p.read()
	}
	p.failAt(true, start.position, lit.want)
	return p.sliceFrom(start), true
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseNotCodeExpr"))
	}

	state := p.cloneState()

	ok, err := not.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, !ok
}

func (p *parser) parseNotExpr(not *notExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseNotExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	_, ok := p.parseExprWrap(not.expr)
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, !ok
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseOneOrMoreExpr"))
	}

	var vals []any

	for {
		p.pushV()
		val, ok := p.parseExprWrap(expr.expr)
		p.popV()
		if !ok {
			if len(vals) == 0 {
				// did not match once, no match
				return nil, false
			}
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseRecoveryExpr(recover *recoveryExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRecoveryExpr (" + strings.Join(recover.failureLabel, ",") + ")"))
	}

	p.pushRecovery(recover.failureLabel, recover.recoverExpr)
	val, ok := p.parseExprWrap(recover.expr)
	p.popRecovery()

	return val, ok
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRuleRefExpr " + ref.name))
	}

	if ref.name == "" {
		panic(fmt.Sprintf("%s: invalid rule: missing name", ref.pos))
	}

	rule := p.rules[ref.name]
	if rule == nil {
		p.addErr(fmt.Errorf("undefined rule: %s", ref.name))
		return nil, false
	}
	return p.parseRuleWrap(rule)
}

func (p *parser) parseSeqExpr(seq *seqExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseSeqExpr"))
	}

	vals := make([]any, 0, len(seq.exprs))

	pt := p.pt
	state := p.cloneState()
	for _, expr := range seq.exprs {
		val, ok := p.parseExprWrap(expr)
		if !ok {
			p.restoreState(state)
			p.restore(pt)
			return nil, false
		}
		vals = append(vals, val)
	}
	return vals, true
}

func (p *parser) parseStateCodeExpr(state *stateCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseStateCodeExpr"))
	}

	err := state.run(p)
	if err != nil {
		p.addErr(err)
	}
	return nil, true
}

func (p *parser) parseThrowExpr(expr *throwExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseThrowExpr"))
	}

	for i := len(p.recoveryStack) - 1; i >= 0; i-- {
		if recoverExpr, ok := p.recoveryStack[i][expr.label]; ok {
			if val, ok := p.parseExprWrap(recoverExpr); ok {
				return val, ok
			}
		}
	}

	return nil, false
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrMoreExpr"))
	}

	var vals []any

	for {
		p.pushV()
		val, ok := p.parseExprWrap(expr.expr)
		p.popV()
		if !ok {
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrOneExpr"))
	}

	p.pushV()
	val, _ := p.parseExprWrap(expr.expr)
	p.popV()
	// whether it matched or not, consider it a match
	return val, true
}
