// Code generated by pigeon; DO NOT EDIT.

package lbmoves

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"math"
	"os"
	"sort"
	"strconv"
	"strings"
	"sync"
	"unicode"
	"unicode/utf8"

	"github.com/mdhender/ottomap/directions"
	"github.com/mdhender/ottomap/domain"
	"github.com/mdhender/ottomap/items"
)

func toAnySlice(v any) []any {
	if v == nil {
		return nil
	}
	return v.([]any)
}

var g = &grammar{
	rules: []*rule{
		{
			name: "Step",
			pos:  position{line: 20, col: 1, offset: 256},
			expr: &choiceExpr{
				pos: position{line: 20, col: 9, offset: 264},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 20, col: 9, offset: 264},
						run: (*parser).callonStep2,
						expr: &seqExpr{
							pos: position{line: 20, col: 9, offset: 264},
							exprs: []any{
								&labeledExpr{
									pos:   position{line: 20, col: 9, offset: 264},
									label: "d",
									expr: &ruleRefExpr{
										pos:  position{line: 20, col: 11, offset: 266},
										name: "DIRECTION",
									},
								},
								&litMatcher{
									pos:        position{line: 20, col: 21, offset: 276},
									val:        "-",
									ignoreCase: false,
									want:       "\"-\"",
								},
								&labeledExpr{
									pos:   position{line: 20, col: 25, offset: 280},
									label: "t",
									expr: &ruleRefExpr{
										pos:  position{line: 20, col: 27, offset: 282},
										name: "TERRAIN",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 20, col: 35, offset: 290},
									name: "EOF",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 25, col: 5, offset: 424},
						run: (*parser).callonStep10,
						expr: &seqExpr{
							pos: position{line: 25, col: 5, offset: 424},
							exprs: []any{
								&charClassMatcher{
									pos:        position{line: 25, col: 5, offset: 424},
									val:        "[Cc]",
									chars:      []rune{'C', 'c'},
									ignoreCase: false,
									inverted:   false,
								},
								&litMatcher{
									pos:        position{line: 25, col: 10, offset: 429},
									val:        "an't Move on",
									ignoreCase: false,
									want:       "\"an't Move on\"",
								},
								&ruleRefExpr{
									pos:  position{line: 25, col: 25, offset: 444},
									name: "SP",
								},
								&labeledExpr{
									pos:   position{line: 25, col: 28, offset: 447},
									label: "t",
									expr: &ruleRefExpr{
										pos:  position{line: 25, col: 30, offset: 449},
										name: "ProhibitedBy",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 25, col: 43, offset: 462},
									name: "SP",
								},
								&litMatcher{
									pos:        position{line: 25, col: 46, offset: 465},
									val:        "to",
									ignoreCase: false,
									want:       "\"to\"",
								},
								&ruleRefExpr{
									pos:  position{line: 25, col: 51, offset: 470},
									name: "SP",
								},
								&labeledExpr{
									pos:   position{line: 25, col: 54, offset: 473},
									label: "d",
									expr: &ruleRefExpr{
										pos:  position{line: 25, col: 56, offset: 475},
										name: "DIRECTION",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 25, col: 66, offset: 485},
									name: "SP",
								},
								&litMatcher{
									pos:        position{line: 25, col: 69, offset: 488},
									val:        "of HEX",
									ignoreCase: false,
									want:       "\"of HEX\"",
								},
								&ruleRefExpr{
									pos:  position{line: 25, col: 78, offset: 497},
									name: "EOF",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 30, col: 5, offset: 630},
						run: (*parser).callonStep25,
						expr: &seqExpr{
							pos: position{line: 30, col: 5, offset: 630},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 30, col: 5, offset: 630},
									val:        "Group did not return",
									ignoreCase: false,
									want:       "\"Group did not return\"",
								},
								&ruleRefExpr{
									pos:  position{line: 30, col: 28, offset: 653},
									name: "EOF",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 32, col: 5, offset: 694},
						run: (*parser).callonStep29,
						expr: &seqExpr{
							pos: position{line: 32, col: 5, offset: 694},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 32, col: 5, offset: 694},
									val:        "Find",
									ignoreCase: false,
									want:       "\"Find\"",
								},
								&ruleRefExpr{
									pos:  position{line: 32, col: 12, offset: 701},
									name: "SP",
								},
								&labeledExpr{
									pos:   position{line: 32, col: 15, offset: 704},
									label: "r",
									expr: &ruleRefExpr{
										pos:  position{line: 32, col: 17, offset: 706},
										name: "RESOURCE",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 32, col: 26, offset: 715},
									name: "EOF",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 34, col: 5, offset: 743},
						run: (*parser).callonStep36,
						expr: &seqExpr{
							pos: position{line: 34, col: 5, offset: 743},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 34, col: 5, offset: 743},
									val:        "Find",
									ignoreCase: false,
									want:       "\"Find\"",
								},
								&ruleRefExpr{
									pos:  position{line: 34, col: 12, offset: 750},
									name: "SP",
								},
								&labeledExpr{
									pos:   position{line: 34, col: 15, offset: 753},
									label: "n",
									expr: &ruleRefExpr{
										pos:  position{line: 34, col: 17, offset: 755},
										name: "NUMBER",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 34, col: 24, offset: 762},
									name: "SP",
								},
								&labeledExpr{
									pos:   position{line: 34, col: 27, offset: 765},
									label: "i",
									expr: &ruleRefExpr{
										pos:  position{line: 34, col: 29, offset: 767},
										name: "ITEMS",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 34, col: 35, offset: 773},
									name: "EOF",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 39, col: 5, offset: 883},
						run: (*parser).callonStep46,
						expr: &seqExpr{
							pos: position{line: 39, col: 5, offset: 883},
							exprs: []any{
								&charClassMatcher{
									pos:        position{line: 39, col: 5, offset: 883},
									val:        "[Nn]",
									chars:      []rune{'N', 'n'},
									ignoreCase: false,
									inverted:   false,
								},
								&litMatcher{
									pos:        position{line: 39, col: 10, offset: 888},
									val:        "o Ford on River to",
									ignoreCase: false,
									want:       "\"o Ford on River to\"",
								},
								&ruleRefExpr{
									pos:  position{line: 39, col: 31, offset: 909},
									name: "SP",
								},
								&labeledExpr{
									pos:   position{line: 39, col: 34, offset: 912},
									label: "d",
									expr: &ruleRefExpr{
										pos:  position{line: 39, col: 36, offset: 914},
										name: "DIRECTION",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 39, col: 46, offset: 924},
									name: "SP",
								},
								&litMatcher{
									pos:        position{line: 39, col: 49, offset: 927},
									val:        "of HEX",
									ignoreCase: false,
									want:       "\"of HEX\"",
								},
								&ruleRefExpr{
									pos:  position{line: 39, col: 58, offset: 936},
									name: "EOF",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 44, col: 5, offset: 1063},
						run: (*parser).callonStep56,
						expr: &seqExpr{
							pos: position{line: 44, col: 5, offset: 1063},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 44, col: 5, offset: 1063},
									val:        "No groups found",
									ignoreCase: false,
									want:       "\"No groups found\"",
								},
								&ruleRefExpr{
									pos:  position{line: 44, col: 23, offset: 1081},
									name: "EOF",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 46, col: 5, offset: 1123},
						run: (*parser).callonStep60,
						expr: &seqExpr{
							pos: position{line: 46, col: 5, offset: 1123},
							exprs: []any{
								&charClassMatcher{
									pos:        position{line: 46, col: 5, offset: 1123},
									val:        "[Nn]",
									chars:      []rune{'N', 'n'},
									ignoreCase: false,
									inverted:   false,
								},
								&litMatcher{
									pos:        position{line: 46, col: 10, offset: 1128},
									val:        "ot enough M.P's to move to",
									ignoreCase: false,
									want:       "\"ot enough M.P's to move to\"",
								},
								&ruleRefExpr{
									pos:  position{line: 46, col: 39, offset: 1157},
									name: "SP",
								},
								&labeledExpr{
									pos:   position{line: 46, col: 42, offset: 1160},
									label: "d",
									expr: &ruleRefExpr{
										pos:  position{line: 46, col: 44, offset: 1162},
										name: "DIRECTION",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 46, col: 54, offset: 1172},
									name: "SP",
								},
								&litMatcher{
									pos:        position{line: 46, col: 57, offset: 1175},
									val:        "into",
									ignoreCase: false,
									want:       "\"into\"",
								},
								&ruleRefExpr{
									pos:  position{line: 46, col: 64, offset: 1182},
									name: "SP",
								},
								&labeledExpr{
									pos:   position{line: 46, col: 67, offset: 1185},
									label: "t",
									expr: &ruleRefExpr{
										pos:  position{line: 46, col: 69, offset: 1187},
										name: "TERRAIN",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 46, col: 77, offset: 1195},
									name: "EOF",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 51, col: 5, offset: 1323},
						run: (*parser).callonStep73,
						expr: &seqExpr{
							pos: position{line: 51, col: 5, offset: 1323},
							exprs: []any{
								&charClassMatcher{
									pos:        position{line: 51, col: 5, offset: 1323},
									val:        "[Nn]",
									chars:      []rune{'N', 'n'},
									ignoreCase: false,
									inverted:   false,
								},
								&litMatcher{
									pos:        position{line: 51, col: 10, offset: 1328},
									val:        "othing of interest found",
									ignoreCase: false,
									want:       "\"othing of interest found\"",
								},
								&ruleRefExpr{
									pos:  position{line: 51, col: 37, offset: 1355},
									name: "EOF",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 53, col: 5, offset: 1396},
						run: (*parser).callonStep78,
						expr: &seqExpr{
							pos: position{line: 53, col: 5, offset: 1396},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 53, col: 5, offset: 1396},
									val:        "Patrolled and found",
									ignoreCase: false,
									want:       "\"Patrolled and found\"",
								},
								&ruleRefExpr{
									pos:  position{line: 53, col: 27, offset: 1418},
									name: "SP",
								},
								&labeledExpr{
									pos:   position{line: 53, col: 30, offset: 1421},
									label: "u",
									expr: &ruleRefExpr{
										pos:  position{line: 53, col: 32, offset: 1423},
										name: "UNIT_ID",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 53, col: 40, offset: 1431},
									name: "EOF",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 58, col: 5, offset: 1566},
						run: (*parser).callonStep85,
						expr: &seqExpr{
							pos: position{line: 58, col: 5, offset: 1566},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 58, col: 5, offset: 1566},
									val:        "L",
									ignoreCase: false,
									want:       "\"L\"",
								},
								&ruleRefExpr{
									pos:  position{line: 58, col: 9, offset: 1570},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 58, col: 11, offset: 1572},
									label: "d",
									expr: &ruleRefExpr{
										pos:  position{line: 58, col: 13, offset: 1574},
										name: "DIRECTION",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 58, col: 23, offset: 1584},
									name: "EOF",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 63, col: 5, offset: 1705},
						run: (*parser).callonStep92,
						expr: &seqExpr{
							pos: position{line: 63, col: 5, offset: 1705},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 63, col: 5, offset: 1705},
									val:        "O",
									ignoreCase: false,
									want:       "\"O\"",
								},
								&ruleRefExpr{
									pos:  position{line: 63, col: 9, offset: 1709},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 63, col: 11, offset: 1711},
									label: "d",
									expr: &ruleRefExpr{
										pos:  position{line: 63, col: 13, offset: 1713},
										name: "DIRECTION",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 63, col: 23, offset: 1723},
									name: "EOF",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 68, col: 5, offset: 1845},
						run: (*parser).callonStep99,
						expr: &seqExpr{
							pos: position{line: 68, col: 5, offset: 1845},
							exprs: []any{
								&labeledExpr{
									pos:   position{line: 68, col: 5, offset: 1845},
									label: "et",
									expr: &ruleRefExpr{
										pos:  position{line: 68, col: 8, offset: 1848},
										name: "EdgeType",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 68, col: 17, offset: 1857},
									name: "SP",
								},
								&labeledExpr{
									pos:   position{line: 68, col: 20, offset: 1860},
									label: "d",
									expr: &ruleRefExpr{
										pos:  position{line: 68, col: 22, offset: 1862},
										name: "DIRECTION",
									},
								},
								&labeledExpr{
									pos:   position{line: 68, col: 32, offset: 1872},
									label: "edi",
									expr: &zeroOrMoreExpr{
										pos: position{line: 68, col: 36, offset: 1876},
										expr: &ruleRefExpr{
											pos:  position{line: 68, col: 36, offset: 1876},
											name: "SpaceDirection",
										},
									},
								},
								&ruleRefExpr{
									pos:  position{line: 68, col: 52, offset: 1892},
									name: "EOF",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 80, col: 5, offset: 2293},
						run: (*parser).callonStep110,
						expr: &seqExpr{
							pos: position{line: 80, col: 5, offset: 2293},
							exprs: []any{
								&labeledExpr{
									pos:   position{line: 80, col: 5, offset: 2293},
									label: "n",
									expr: &ruleRefExpr{
										pos:  position{line: 80, col: 7, offset: 2295},
										name: "NUMBER",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 80, col: 14, offset: 2302},
									name: "SP",
								},
								&labeledExpr{
									pos:   position{line: 80, col: 17, offset: 2305},
									label: "i",
									expr: &ruleRefExpr{
										pos:  position{line: 80, col: 19, offset: 2307},
										name: "ITEM",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 80, col: 24, offset: 2312},
									name: "EOF",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 85, col: 5, offset: 2422},
						run: (*parser).callonStep118,
						expr: &seqExpr{
							pos: position{line: 85, col: 5, offset: 2422},
							exprs: []any{
								&labeledExpr{
									pos:   position{line: 85, col: 5, offset: 2422},
									label: "u",
									expr: &ruleRefExpr{
										pos:  position{line: 85, col: 7, offset: 2424},
										name: "UNIT_ID",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 85, col: 15, offset: 2432},
									name: "EOF",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 87, col: 5, offset: 2460},
						run: (*parser).callonStep123,
						expr: &seqExpr{
							pos: position{line: 87, col: 5, offset: 2460},
							exprs: []any{
								&labeledExpr{
									pos:   position{line: 87, col: 5, offset: 2460},
									label: "d",
									expr: &ruleRefExpr{
										pos:  position{line: 87, col: 7, offset: 2462},
										name: "DIRECTION",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 87, col: 17, offset: 2472},
									name: "EOF",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "EdgeType",
			pos:  position{line: 91, col: 1, offset: 2499},
			expr: &choiceExpr{
				pos: position{line: 91, col: 13, offset: 2511},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 91, col: 13, offset: 2511},
						run: (*parser).callonEdgeType2,
						expr: &litMatcher{
							pos:        position{line: 91, col: 13, offset: 2511},
							val:        "Ford",
							ignoreCase: false,
							want:       "\"Ford\"",
						},
					},
					&actionExpr{
						pos: position{line: 93, col: 5, offset: 2553},
						run: (*parser).callonEdgeType4,
						expr: &litMatcher{
							pos:        position{line: 93, col: 5, offset: 2553},
							val:        "Pass",
							ignoreCase: false,
							want:       "\"Pass\"",
						},
					},
					&actionExpr{
						pos: position{line: 95, col: 5, offset: 2595},
						run: (*parser).callonEdgeType6,
						expr: &litMatcher{
							pos:        position{line: 95, col: 5, offset: 2595},
							val:        "River",
							ignoreCase: false,
							want:       "\"River\"",
						},
					},
				},
			},
		},
		{
			name: "SpaceDirection",
			pos:  position{line: 99, col: 1, offset: 2638},
			expr: &actionExpr{
				pos: position{line: 99, col: 19, offset: 2656},
				run: (*parser).callonSpaceDirection1,
				expr: &seqExpr{
					pos: position{line: 99, col: 19, offset: 2656},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 99, col: 19, offset: 2656},
							name: "SP",
						},
						&labeledExpr{
							pos:   position{line: 99, col: 22, offset: 2659},
							label: "d",
							expr: &ruleRefExpr{
								pos:  position{line: 99, col: 24, offset: 2661},
								name: "DIRECTION",
							},
						},
					},
				},
			},
		},
		{
			name: "ProhibitedBy",
			pos:  position{line: 103, col: 1, offset: 2694},
			expr: &choiceExpr{
				pos: position{line: 103, col: 17, offset: 2710},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 103, col: 17, offset: 2710},
						run: (*parser).callonProhibitedBy2,
						expr: &litMatcher{
							pos:        position{line: 103, col: 17, offset: 2710},
							val:        "Lake",
							ignoreCase: false,
							want:       "\"Lake\"",
						},
					},
					&actionExpr{
						pos: position{line: 105, col: 5, offset: 2752},
						run: (*parser).callonProhibitedBy4,
						expr: &litMatcher{
							pos:        position{line: 105, col: 5, offset: 2752},
							val:        "Ocean",
							ignoreCase: false,
							want:       "\"Ocean\"",
						},
					},
				},
			},
		},
		{
			name: "DIRECTION",
			pos:  position{line: 109, col: 1, offset: 2795},
			expr: &choiceExpr{
				pos: position{line: 109, col: 14, offset: 2808},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 109, col: 14, offset: 2808},
						run: (*parser).callonDIRECTION2,
						expr: &litMatcher{
							pos:        position{line: 109, col: 14, offset: 2808},
							val:        "NE",
							ignoreCase: false,
							want:       "\"NE\"",
						},
					},
					&actionExpr{
						pos: position{line: 111, col: 5, offset: 2857},
						run: (*parser).callonDIRECTION4,
						expr: &litMatcher{
							pos:        position{line: 111, col: 5, offset: 2857},
							val:        "SE",
							ignoreCase: false,
							want:       "\"SE\"",
						},
					},
					&actionExpr{
						pos: position{line: 113, col: 5, offset: 2906},
						run: (*parser).callonDIRECTION6,
						expr: &litMatcher{
							pos:        position{line: 113, col: 5, offset: 2906},
							val:        "SW",
							ignoreCase: false,
							want:       "\"SW\"",
						},
					},
					&actionExpr{
						pos: position{line: 115, col: 5, offset: 2955},
						run: (*parser).callonDIRECTION8,
						expr: &litMatcher{
							pos:        position{line: 115, col: 5, offset: 2955},
							val:        "NW",
							ignoreCase: false,
							want:       "\"NW\"",
						},
					},
					&actionExpr{
						pos: position{line: 117, col: 5, offset: 3004},
						run: (*parser).callonDIRECTION10,
						expr: &litMatcher{
							pos:        position{line: 117, col: 5, offset: 3004},
							val:        "N",
							ignoreCase: false,
							want:       "\"N\"",
						},
					},
					&actionExpr{
						pos: position{line: 119, col: 5, offset: 3048},
						run: (*parser).callonDIRECTION12,
						expr: &litMatcher{
							pos:        position{line: 119, col: 5, offset: 3048},
							val:        "S",
							ignoreCase: false,
							want:       "\"S\"",
						},
					},
				},
			},
		},
		{
			name: "ITEM",
			pos:  position{line: 123, col: 1, offset: 3091},
			expr: &choiceExpr{
				pos: position{line: 123, col: 9, offset: 3099},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 123, col: 9, offset: 3099},
						run: (*parser).callonITEM2,
						expr: &litMatcher{
							pos:        position{line: 123, col: 9, offset: 3099},
							val:        "Diamond",
							ignoreCase: false,
							want:       "\"Diamond\"",
						},
					},
					&actionExpr{
						pos: position{line: 125, col: 5, offset: 3145},
						run: (*parser).callonITEM4,
						expr: &litMatcher{
							pos:        position{line: 125, col: 5, offset: 3145},
							val:        "HORSES",
							ignoreCase: false,
							want:       "\"HORSES\"",
						},
					},
				},
			},
		},
		{
			name: "NUMBER",
			pos:  position{line: 129, col: 1, offset: 3188},
			expr: &actionExpr{
				pos: position{line: 129, col: 11, offset: 3198},
				run: (*parser).callonNUMBER1,
				expr: &oneOrMoreExpr{
					pos: position{line: 129, col: 11, offset: 3198},
					expr: &charClassMatcher{
						pos:        position{line: 129, col: 11, offset: 3198},
						val:        "[0-9]",
						ranges:     []rune{'0', '9'},
						ignoreCase: false,
						inverted:   false,
					},
				},
			},
		},
		{
			name: "RESOURCE",
			pos:  position{line: 133, col: 1, offset: 3250},
			expr: &choiceExpr{
				pos: position{line: 133, col: 13, offset: 3262},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 133, col: 13, offset: 3262},
						run: (*parser).callonRESOURCE2,
						expr: &litMatcher{
							pos:        position{line: 133, col: 13, offset: 3262},
							val:        "Coal",
							ignoreCase: false,
							want:       "\"Coal\"",
						},
					},
					&actionExpr{
						pos: position{line: 135, col: 5, offset: 3304},
						run: (*parser).callonRESOURCE4,
						expr: &litMatcher{
							pos:        position{line: 135, col: 5, offset: 3304},
							val:        "Iron Ore",
							ignoreCase: false,
							want:       "\"Iron Ore\"",
						},
					},
				},
			},
		},
		{
			name: "TERRAIN",
			pos:  position{line: 139, col: 1, offset: 3352},
			expr: &choiceExpr{
				pos: position{line: 139, col: 12, offset: 3363},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 139, col: 12, offset: 3363},
						run: (*parser).callonTERRAIN2,
						expr: &litMatcher{
							pos:        position{line: 139, col: 12, offset: 3363},
							val:        "CONIFER HILLS",
							ignoreCase: false,
							want:       "\"CONIFER HILLS\"",
						},
					},
					&actionExpr{
						pos: position{line: 141, col: 5, offset: 3422},
						run: (*parser).callonTERRAIN4,
						expr: &litMatcher{
							pos:        position{line: 141, col: 5, offset: 3422},
							val:        "GRASSY HILLS",
							ignoreCase: false,
							want:       "\"GRASSY HILLS\"",
						},
					},
					&actionExpr{
						pos: position{line: 143, col: 5, offset: 3479},
						run: (*parser).callonTERRAIN6,
						expr: &litMatcher{
							pos:        position{line: 143, col: 5, offset: 3479},
							val:        "PRAIRIE",
							ignoreCase: false,
							want:       "\"PRAIRIE\"",
						},
					},
					&actionExpr{
						pos: position{line: 145, col: 5, offset: 3527},
						run: (*parser).callonTERRAIN8,
						expr: &litMatcher{
							pos:        position{line: 145, col: 5, offset: 3527},
							val:        "ROCKY HILLS",
							ignoreCase: false,
							want:       "\"ROCKY HILLS\"",
						},
					},
					&actionExpr{
						pos: position{line: 147, col: 5, offset: 3582},
						run: (*parser).callonTERRAIN10,
						expr: &litMatcher{
							pos:        position{line: 147, col: 5, offset: 3582},
							val:        "SWAMP",
							ignoreCase: false,
							want:       "\"SWAMP\"",
						},
					},
					&actionExpr{
						pos: position{line: 149, col: 5, offset: 3626},
						run: (*parser).callonTERRAIN12,
						expr: &litMatcher{
							pos:        position{line: 149, col: 5, offset: 3626},
							val:        "LAKE",
							ignoreCase: false,
							want:       "\"LAKE\"",
						},
					},
					&actionExpr{
						pos: position{line: 151, col: 5, offset: 3668},
						run: (*parser).callonTERRAIN14,
						expr: &litMatcher{
							pos:        position{line: 151, col: 5, offset: 3668},
							val:        "OCEAN",
							ignoreCase: false,
							want:       "\"OCEAN\"",
						},
					},
					&actionExpr{
						pos: position{line: 153, col: 5, offset: 3712},
						run: (*parser).callonTERRAIN16,
						expr: &litMatcher{
							pos:        position{line: 153, col: 5, offset: 3712},
							val:        "CH",
							ignoreCase: false,
							want:       "\"CH\"",
						},
					},
					&actionExpr{
						pos: position{line: 155, col: 5, offset: 3760},
						run: (*parser).callonTERRAIN18,
						expr: &litMatcher{
							pos:        position{line: 155, col: 5, offset: 3760},
							val:        "GH",
							ignoreCase: false,
							want:       "\"GH\"",
						},
					},
					&actionExpr{
						pos: position{line: 157, col: 5, offset: 3807},
						run: (*parser).callonTERRAIN20,
						expr: &litMatcher{
							pos:        position{line: 157, col: 5, offset: 3807},
							val:        "PR",
							ignoreCase: false,
							want:       "\"PR\"",
						},
					},
					&actionExpr{
						pos: position{line: 159, col: 5, offset: 3850},
						run: (*parser).callonTERRAIN22,
						expr: &litMatcher{
							pos:        position{line: 159, col: 5, offset: 3850},
							val:        "RH",
							ignoreCase: false,
							want:       "\"RH\"",
						},
					},
					&actionExpr{
						pos: position{line: 161, col: 5, offset: 3896},
						run: (*parser).callonTERRAIN24,
						expr: &litMatcher{
							pos:        position{line: 161, col: 5, offset: 3896},
							val:        "SW",
							ignoreCase: false,
							want:       "\"SW\"",
						},
					},
					&actionExpr{
						pos: position{line: 163, col: 5, offset: 3937},
						run: (*parser).callonTERRAIN26,
						expr: &litMatcher{
							pos:        position{line: 163, col: 5, offset: 3937},
							val:        "L",
							ignoreCase: false,
							want:       "\"L\"",
						},
					},
					&actionExpr{
						pos: position{line: 165, col: 5, offset: 3976},
						run: (*parser).callonTERRAIN28,
						expr: &litMatcher{
							pos:        position{line: 165, col: 5, offset: 3976},
							val:        "O",
							ignoreCase: false,
							want:       "\"O\"",
						},
					},
				},
			},
		},
		{
			name: "UNIT_ID",
			pos:  position{line: 169, col: 1, offset: 4015},
			expr: &actionExpr{
				pos: position{line: 169, col: 12, offset: 4026},
				run: (*parser).callonUNIT_ID1,
				expr: &seqExpr{
					pos: position{line: 169, col: 12, offset: 4026},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 169, col: 12, offset: 4026},
							name: "DIGIT",
						},
						&ruleRefExpr{
							pos:  position{line: 169, col: 18, offset: 4032},
							name: "DIGIT",
						},
						&ruleRefExpr{
							pos:  position{line: 169, col: 24, offset: 4038},
							name: "DIGIT",
						},
						&ruleRefExpr{
							pos:  position{line: 169, col: 30, offset: 4044},
							name: "DIGIT",
						},
						&zeroOrOneExpr{
							pos: position{line: 169, col: 36, offset: 4050},
							expr: &seqExpr{
								pos: position{line: 169, col: 37, offset: 4051},
								exprs: []any{
									&charClassMatcher{
										pos:        position{line: 169, col: 37, offset: 4051},
										val:        "[cefg]",
										chars:      []rune{'c', 'e', 'f', 'g'},
										ignoreCase: false,
										inverted:   false,
									},
									&ruleRefExpr{
										pos:  position{line: 169, col: 44, offset: 4058},
										name: "DIGIT",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "EOF",
			pos:  position{line: 173, col: 1, offset: 4110},
			expr: &notExpr{
				pos: position{line: 173, col: 10, offset: 4119},
				expr: &anyMatcher{
					line: 173, col: 11, offset: 4120,
				},
			},
		},
		{
			name: "DIGIT",
			pos:  position{line: 174, col: 1, offset: 4122},
			expr: &charClassMatcher{
				pos:        position{line: 174, col: 10, offset: 4131},
				val:        "[0-9]",
				ranges:     []rune{'0', '9'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "LETTER",
			pos:  position{line: 175, col: 1, offset: 4137},
			expr: &charClassMatcher{
				pos:        position{line: 175, col: 10, offset: 4146},
				val:        "[A-Z]",
				ranges:     []rune{'A', 'Z'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "SP",
			pos:  position{line: 176, col: 1, offset: 4152},
			expr: &oneOrMoreExpr{
				pos: position{line: 176, col: 10, offset: 4161},
				expr: &charClassMatcher{
					pos:        position{line: 176, col: 10, offset: 4161},
					val:        "[ \\t]",
					chars:      []rune{' ', '\t'},
					ignoreCase: false,
					inverted:   false,
				},
			},
		},
		{
			name: "_",
			pos:  position{line: 177, col: 1, offset: 4168},
			expr: &zeroOrMoreExpr{
				pos: position{line: 177, col: 10, offset: 4177},
				expr: &charClassMatcher{
					pos:        position{line: 177, col: 10, offset: 4177},
					val:        "[ \\t]",
					chars:      []rune{' ', '\t'},
					ignoreCase: false,
					inverted:   false,
				},
			},
		},
	},
}

func (c *current) onStep2(d, t any) (any, error) {
	return DirectionTerrain{
		Direction: d.(directions.Direction),
		Terrain:   t.(domain.Terrain),
	}, nil
}

func (p *parser) callonStep2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onStep2(stack["d"], stack["t"])
}

func (c *current) onStep10(t, d any) (any, error) {
	return &ProhibitedFrom{
		Direction: d.(directions.Direction),
		Terrain:   t.(domain.Terrain),
	}, nil
}

func (p *parser) callonStep10() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onStep10(stack["t"], stack["d"])
}

func (c *current) onStep25() (any, error) {
	return DidNotReturn{}, nil
}

func (p *parser) callonStep25() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onStep25()
}

func (c *current) onStep29(r any) (any, error) {
	return r, nil
}

func (p *parser) callonStep29() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onStep29(stack["r"])
}

func (c *current) onStep36(n, i any) (any, error) {
	return RandomEncounter{
		Quantity: n.(int),
		Item:     i.(items.Item),
	}, nil
}

func (p *parser) callonStep36() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onStep36(stack["n"], stack["i"])
}

func (c *current) onStep46(d any) (any, error) {
	return &BlockedByEdge{
		Direction: d.(directions.Direction),
		Edge:      domain.ERiver,
	}, nil
}

func (p *parser) callonStep46() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onStep46(stack["d"])
}

func (c *current) onStep56() (any, error) {
	return NoGroupsFound{}, nil
}

func (p *parser) callonStep56() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onStep56()
}

func (c *current) onStep60(d, t any) (any, error) {
	return &Exhausted{
		Direction: d.(directions.Direction),
		Terrain:   t.(domain.Terrain),
	}, nil
}

func (p *parser) callonStep60() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onStep60(stack["d"], stack["t"])
}

func (c *current) onStep73() (any, error) {
	return FoundNothing{}, nil
}

func (p *parser) callonStep73() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onStep73()
}

func (c *current) onStep78(u any) (any, error) {
	// todo: input is comma separated, but we're only returning one
	return FoundUnit{
		Id: u.(UnitID),
	}, nil
}

func (p *parser) callonStep78() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onStep78(stack["u"])
}

func (c *current) onStep85(d any) (any, error) {
	return &Neighbor{
		Direction: d.(directions.Direction),
		Terrain:   domain.TLake,
	}, nil
}

func (p *parser) callonStep85() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onStep85(stack["d"])
}

func (c *current) onStep92(d any) (any, error) {
	return &Neighbor{
		Direction: d.(directions.Direction),
		Terrain:   domain.TOcean,
	}, nil
}

func (p *parser) callonStep92() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onStep92(stack["d"])
}

func (c *current) onStep99(et, d, edi any) (any, error) {
	kind := et.(domain.Edge)
	edges := []*Edge{&Edge{Direction: d.(directions.Direction), Edge: kind}}
	for _, ed := range toAnySlice(edi) {
		switch v := ed.(type) {
		case directions.Direction:
			edges = append(edges, &Edge{Direction: v, Edge: kind})
		default:
			panic(fmt.Errorf("unexpected type %T", v))
		}
	}
	return edges, nil
}

func (p *parser) callonStep99() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onStep99(stack["et"], stack["d"], stack["edi"])
}

func (c *current) onStep110(n, i any) (any, error) {
	return RandomEncounter{
		Quantity: n.(int),
		Item:     i.(items.Item),
	}, nil
}

func (p *parser) callonStep110() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onStep110(stack["n"], stack["i"])
}

func (c *current) onStep118(u any) (any, error) {
	return u, nil
}

func (p *parser) callonStep118() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onStep118(stack["u"])
}

func (c *current) onStep123(d any) (any, error) {
	return d, nil
}

func (p *parser) callonStep123() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onStep123(stack["d"])
}

func (c *current) onEdgeType2() (any, error) {
	return domain.EFord, nil
}

func (p *parser) callonEdgeType2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onEdgeType2()
}

func (c *current) onEdgeType4() (any, error) {
	return domain.EPass, nil
}

func (p *parser) callonEdgeType4() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onEdgeType4()
}

func (c *current) onEdgeType6() (any, error) {
	return domain.ERiver, nil
}

func (p *parser) callonEdgeType6() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onEdgeType6()
}

func (c *current) onSpaceDirection1(d any) (any, error) {
	return d, nil
}

func (p *parser) callonSpaceDirection1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSpaceDirection1(stack["d"])
}

func (c *current) onProhibitedBy2() (any, error) {
	return domain.TLake, nil
}

func (p *parser) callonProhibitedBy2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onProhibitedBy2()
}

func (c *current) onProhibitedBy4() (any, error) {
	return domain.TOcean, nil
}

func (p *parser) callonProhibitedBy4() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onProhibitedBy4()
}

func (c *current) onDIRECTION2() (any, error) {
	return directions.DNorthEast, nil
}

func (p *parser) callonDIRECTION2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDIRECTION2()
}

func (c *current) onDIRECTION4() (any, error) {
	return directions.DSouthEast, nil
}

func (p *parser) callonDIRECTION4() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDIRECTION4()
}

func (c *current) onDIRECTION6() (any, error) {
	return directions.DSouthWest, nil
}

func (p *parser) callonDIRECTION6() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDIRECTION6()
}

func (c *current) onDIRECTION8() (any, error) {
	return directions.DNorthWest, nil
}

func (p *parser) callonDIRECTION8() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDIRECTION8()
}

func (c *current) onDIRECTION10() (any, error) {
	return directions.DNorth, nil
}

func (p *parser) callonDIRECTION10() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDIRECTION10()
}

func (c *current) onDIRECTION12() (any, error) {
	return directions.DSouth, nil
}

func (p *parser) callonDIRECTION12() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDIRECTION12()
}

func (c *current) onITEM2() (any, error) {
	return items.Diamond, nil
}

func (p *parser) callonITEM2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onITEM2()
}

func (c *current) onITEM4() (any, error) {
	return items.Horses, nil
}

func (p *parser) callonITEM4() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onITEM4()
}

func (c *current) onNUMBER1() (any, error) {
	return strconv.Atoi(string(c.text))
}

func (p *parser) callonNUMBER1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNUMBER1()
}

func (c *current) onRESOURCE2() (any, error) {
	return domain.RCoal, nil
}

func (p *parser) callonRESOURCE2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onRESOURCE2()
}

func (c *current) onRESOURCE4() (any, error) {
	return domain.RIronOre, nil
}

func (p *parser) callonRESOURCE4() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onRESOURCE4()
}

func (c *current) onTERRAIN2() (any, error) {
	return domain.TConiferHills, nil
}

func (p *parser) callonTERRAIN2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTERRAIN2()
}

func (c *current) onTERRAIN4() (any, error) {
	return domain.TGrassyHills, nil
}

func (p *parser) callonTERRAIN4() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTERRAIN4()
}

func (c *current) onTERRAIN6() (any, error) {
	return domain.TPrairie, nil
}

func (p *parser) callonTERRAIN6() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTERRAIN6()
}

func (c *current) onTERRAIN8() (any, error) {
	return domain.TRockyHills, nil
}

func (p *parser) callonTERRAIN8() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTERRAIN8()
}

func (c *current) onTERRAIN10() (any, error) {
	return domain.TSwamp, nil
}

func (p *parser) callonTERRAIN10() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTERRAIN10()
}

func (c *current) onTERRAIN12() (any, error) {
	return domain.TLake, nil
}

func (p *parser) callonTERRAIN12() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTERRAIN12()
}

func (c *current) onTERRAIN14() (any, error) {
	return domain.TOcean, nil
}

func (p *parser) callonTERRAIN14() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTERRAIN14()
}

func (c *current) onTERRAIN16() (any, error) {
	return domain.TConiferHills, nil
}

func (p *parser) callonTERRAIN16() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTERRAIN16()
}

func (c *current) onTERRAIN18() (any, error) {
	return domain.TGrassyHills, nil
}

func (p *parser) callonTERRAIN18() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTERRAIN18()
}

func (c *current) onTERRAIN20() (any, error) {
	return domain.TPrairie, nil
}

func (p *parser) callonTERRAIN20() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTERRAIN20()
}

func (c *current) onTERRAIN22() (any, error) {
	return domain.TRockyHills, nil
}

func (p *parser) callonTERRAIN22() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTERRAIN22()
}

func (c *current) onTERRAIN24() (any, error) {
	return domain.TSwamp, nil
}

func (p *parser) callonTERRAIN24() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTERRAIN24()
}

func (c *current) onTERRAIN26() (any, error) {
	return domain.TLake, nil
}

func (p *parser) callonTERRAIN26() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTERRAIN26()
}

func (c *current) onTERRAIN28() (any, error) {
	return domain.TOcean, nil
}

func (p *parser) callonTERRAIN28() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTERRAIN28()
}

func (c *current) onUNIT_ID1() (any, error) {
	return UnitID(string(c.text)), nil
}

func (p *parser) callonUNIT_ID1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onUNIT_ID1()
}

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEntrypoint is returned when the specified entrypoint rule
	// does not exit.
	errInvalidEntrypoint = errors.New("invalid entrypoint")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errMaxExprCnt is used to signal that the maximum number of
	// expressions have been parsed.
	errMaxExprCnt = errors.New("max number of expresssions parsed")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// MaxExpressions creates an Option to stop parsing after the provided
// number of expressions have been parsed, if the value is 0 then the parser will
// parse for as many steps as needed (possibly an infinite number).
//
// The default for maxExprCnt is 0.
func MaxExpressions(maxExprCnt uint64) Option {
	return func(p *parser) Option {
		oldMaxExprCnt := p.maxExprCnt
		p.maxExprCnt = maxExprCnt
		return MaxExpressions(oldMaxExprCnt)
	}
}

// Entrypoint creates an Option to set the rule name to use as entrypoint.
// The rule name must have been specified in the -alternate-entrypoints
// if generating the parser with the -optimize-grammar flag, otherwise
// it may have been optimized out. Passing an empty string sets the
// entrypoint to the first rule in the grammar.
//
// The default is to start parsing at the first rule in the grammar.
func Entrypoint(ruleName string) Option {
	return func(p *parser) Option {
		oldEntrypoint := p.entrypoint
		p.entrypoint = ruleName
		if ruleName == "" {
			p.entrypoint = g.rules[0].name
		}
		return Entrypoint(oldEntrypoint)
	}
}

// Statistics adds a user provided Stats struct to the parser to allow
// the user to process the results after the parsing has finished.
// Also the key for the "no match" counter is set.
//
// Example usage:
//
//	input := "input"
//	stats := Stats{}
//	_, err := Parse("input-file", []byte(input), Statistics(&stats, "no match"))
//	if err != nil {
//	    log.Panicln(err)
//	}
//	b, err := json.MarshalIndent(stats.ChoiceAltCnt, "", "  ")
//	if err != nil {
//	    log.Panicln(err)
//	}
//	fmt.Println(string(b))
func Statistics(stats *Stats, choiceNoMatch string) Option {
	return func(p *parser) Option {
		oldStats := p.Stats
		p.Stats = stats
		oldChoiceNoMatch := p.choiceNoMatch
		p.choiceNoMatch = choiceNoMatch
		if p.Stats.ChoiceAltCnt == nil {
			p.Stats.ChoiceAltCnt = make(map[string]map[string]int)
		}
		return Statistics(oldStats, oldChoiceNoMatch)
	}
}

// Debug creates an Option to set the debug flag to b. When set to true,
// debugging information is printed to stdout while parsing.
//
// The default is false.
func Debug(b bool) Option {
	return func(p *parser) Option {
		old := p.debug
		p.debug = b
		return Debug(old)
	}
}

// Memoize creates an Option to set the memoize flag to b. When set to true,
// the parser will cache all results so each expression is evaluated only
// once. This guarantees linear parsing time even for pathological cases,
// at the expense of more memory and slower times for typical cases.
//
// The default is false.
func Memoize(b bool) Option {
	return func(p *parser) Option {
		old := p.memoize
		p.memoize = b
		return Memoize(old)
	}
}

// AllowInvalidUTF8 creates an Option to allow invalid UTF-8 bytes.
// Every invalid UTF-8 byte is treated as a utf8.RuneError (U+FFFD)
// by character class matchers and is matched by the any matcher.
// The returned matched value, c.text and c.offset are NOT affected.
//
// The default is false.
func AllowInvalidUTF8(b bool) Option {
	return func(p *parser) Option {
		old := p.allowInvalidUTF8
		p.allowInvalidUTF8 = b
		return AllowInvalidUTF8(old)
	}
}

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option {
	return func(p *parser) Option {
		old := p.recover
		p.recover = b
		return Recover(old)
	}
}

// GlobalStore creates an Option to set a key to a certain value in
// the globalStore.
func GlobalStore(key string, value any) Option {
	return func(p *parser) Option {
		old := p.cur.globalStore[key]
		p.cur.globalStore[key] = value
		return GlobalStore(key, old)
	}
}

// InitState creates an Option to set a key to a certain value in
// the global "state" store.
func InitState(key string, value any) Option {
	return func(p *parser) Option {
		old := p.cur.state[key]
		p.cur.state[key] = value
		return InitState(key, old)
	}
}

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (i any, err error) {
	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer func() {
		if closeErr := f.Close(); closeErr != nil {
			err = closeErr
		}
	}()
	return ParseReader(filename, f, opts...)
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (any, error) {
	b, err := io.ReadAll(r)
	if err != nil {
		return nil, err
	}

	return Parse(filename, b, opts...)
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (any, error) {
	return newParser(filename, b, opts...).parse(g)
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string {
	return strconv.Itoa(p.line) + ":" + strconv.Itoa(p.col) + " [" + strconv.Itoa(p.offset) + "]"
}

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match

	// state is a store for arbitrary key,value pairs that the user wants to be
	// tied to the backtracking of the parser.
	// This is always rolled back if a parsing rule fails.
	state storeDict

	// globalStore is a general store for the user to store arbitrary key-value
	// pairs that they need to manage and that they do not want tied to the
	// backtracking of the parser. This is only modified by the user and never
	// rolled back by the parser. It is always up to the user to keep this in a
	// consistent state.
	globalStore storeDict
}

type storeDict map[string]any

// the AST types...

type grammar struct {
	pos   position
	rules []*rule
}

type rule struct {
	pos         position
	name        string
	displayName string
	expr        any
}

type choiceExpr struct {
	pos          position
	alternatives []any
}

type actionExpr struct {
	pos  position
	expr any
	run  func(*parser) (any, error)
}

type recoveryExpr struct {
	pos          position
	expr         any
	recoverExpr  any
	failureLabel []string
}

type seqExpr struct {
	pos   position
	exprs []any
}

type throwExpr struct {
	pos   position
	label string
}

type labeledExpr struct {
	pos   position
	label string
	expr  any
}

type expr struct {
	pos  position
	expr any
}

type (
	andExpr        expr
	notExpr        expr
	zeroOrOneExpr  expr
	zeroOrMoreExpr expr
	oneOrMoreExpr  expr
)

type ruleRefExpr struct {
	pos  position
	name string
}

type stateCodeExpr struct {
	pos position
	run func(*parser) error
}

type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
	want       string
}

type charClassMatcher struct {
	pos             position
	val             string
	basicLatinChars [128]bool
	chars           []rune
	ranges          []rune
	classes         []*unicode.RangeTable
	ignoreCase      bool
	inverted        bool
}

type anyMatcher position

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) {
	*e = append(*e, err)
}

func (e errList) err() error {
	if len(e) == 0 {
		return nil
	}
	e.dedupe()
	return e
}

func (e *errList) dedupe() {
	var cleaned []error
	set := make(map[string]bool)
	for _, err := range *e {
		if msg := err.Error(); !set[msg] {
			set[msg] = true
			cleaned = append(cleaned, err)
		}
	}
	*e = cleaned
}

func (e errList) Error() string {
	switch len(e) {
	case 0:
		return ""
	case 1:
		return e[0].Error()
	default:
		var buf bytes.Buffer

		for i, err := range e {
			if i > 0 {
				buf.WriteRune('\n')
			}
			buf.WriteString(err.Error())
		}
		return buf.String()
	}
}

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner    error
	pos      position
	prefix   string
	expected []string
}

// Error returns the error message.
func (p *parserError) Error() string {
	return p.prefix + ": " + p.Inner.Error()
}

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	stats := Stats{
		ChoiceAltCnt: make(map[string]map[string]int),
	}

	p := &parser{
		filename: filename,
		errs:     new(errList),
		data:     b,
		pt:       savepoint{position: position{line: 1}},
		recover:  true,
		cur: current{
			state:       make(storeDict),
			globalStore: make(storeDict),
		},
		maxFailPos:      position{col: 1, line: 1},
		maxFailExpected: make([]string, 0, 20),
		Stats:           &stats,
		// start rule is rule [0] unless an alternate entrypoint is specified
		entrypoint: g.rules[0].name,
	}
	p.setOptions(opts)

	if p.maxExprCnt == 0 {
		p.maxExprCnt = math.MaxUint64
	}

	return p
}

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) {
	for _, opt := range opts {
		opt(p)
	}
}

type resultTuple struct {
	v   any
	b   bool
	end savepoint
}

const choiceNoMatch = -1

// Stats stores some statistics, gathered during parsing
type Stats struct {
	// ExprCnt counts the number of expressions processed during parsing
	// This value is compared to the maximum number of expressions allowed
	// (set by the MaxExpressions option).
	ExprCnt uint64

	// ChoiceAltCnt is used to count for each ordered choice expression,
	// which alternative is used how may times.
	// These numbers allow to optimize the order of the ordered choice expression
	// to increase the performance of the parser
	//
	// The outer key of ChoiceAltCnt is composed of the name of the rule as well
	// as the line and the column of the ordered choice.
	// The inner key of ChoiceAltCnt is the number (one-based) of the matching alternative.
	// For each alternative the number of matches are counted. If an ordered choice does not
	// match, a special counter is incremented. The name of this counter is set with
	// the parser option Statistics.
	// For an alternative to be included in ChoiceAltCnt, it has to match at least once.
	ChoiceAltCnt map[string]map[string]int
}

type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	depth   int
	recover bool
	debug   bool

	memoize bool
	// memoization table for the packrat algorithm:
	// map[offset in source] map[expression or rule] {value, match}
	memo map[int]map[any]resultTuple

	// rules table, maps the rule identifier to the rule node
	rules map[string]*rule
	// variables stack, map of label to value
	vstack []map[string]any
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// parse fail
	maxFailPos            position
	maxFailExpected       []string
	maxFailInvertExpected bool

	// max number of expressions to be parsed
	maxExprCnt uint64
	// entrypoint for the parser
	entrypoint string

	allowInvalidUTF8 bool

	*Stats

	choiceNoMatch string
	// recovery expression stack, keeps track of the currently available recovery expression, these are traversed in reverse
	recoveryStack []map[string]any
}

// push a variable set on the vstack.
func (p *parser) pushV() {
	if cap(p.vstack) == len(p.vstack) {
		// create new empty slot in the stack
		p.vstack = append(p.vstack, nil)
	} else {
		// slice to 1 more
		p.vstack = p.vstack[:len(p.vstack)+1]
	}

	// get the last args set
	m := p.vstack[len(p.vstack)-1]
	if m != nil && len(m) == 0 {
		// empty map, all good
		return
	}

	m = make(map[string]any)
	p.vstack[len(p.vstack)-1] = m
}

// pop a variable set from the vstack.
func (p *parser) popV() {
	// if the map is not empty, clear it
	m := p.vstack[len(p.vstack)-1]
	if len(m) > 0 {
		// GC that map
		p.vstack[len(p.vstack)-1] = nil
	}
	p.vstack = p.vstack[:len(p.vstack)-1]
}

// push a recovery expression with its labels to the recoveryStack
func (p *parser) pushRecovery(labels []string, expr any) {
	if cap(p.recoveryStack) == len(p.recoveryStack) {
		// create new empty slot in the stack
		p.recoveryStack = append(p.recoveryStack, nil)
	} else {
		// slice to 1 more
		p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)+1]
	}

	m := make(map[string]any, len(labels))
	for _, fl := range labels {
		m[fl] = expr
	}
	p.recoveryStack[len(p.recoveryStack)-1] = m
}

// pop a recovery expression from the recoveryStack
func (p *parser) popRecovery() {
	// GC that map
	p.recoveryStack[len(p.recoveryStack)-1] = nil

	p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)-1]
}

func (p *parser) print(prefix, s string) string {
	if !p.debug {
		return s
	}

	fmt.Printf("%s %d:%d:%d: %s [%#U]\n",
		prefix, p.pt.line, p.pt.col, p.pt.offset, s, p.pt.rn)
	return s
}

func (p *parser) printIndent(mark string, s string) string {
	return p.print(strings.Repeat(" ", p.depth)+mark, s)
}

func (p *parser) in(s string) string {
	res := p.printIndent(">", s)
	p.depth++
	return res
}

func (p *parser) out(s string) string {
	p.depth--
	return p.printIndent("<", s)
}

func (p *parser) addErr(err error) {
	p.addErrAt(err, p.pt.position, []string{})
}

func (p *parser) addErrAt(err error, pos position, expected []string) {
	var buf bytes.Buffer
	if p.filename != "" {
		buf.WriteString(p.filename)
	}
	if buf.Len() > 0 {
		buf.WriteString(":")
	}
	buf.WriteString(fmt.Sprintf("%d:%d (%d)", pos.line, pos.col, pos.offset))
	if len(p.rstack) > 0 {
		if buf.Len() > 0 {
			buf.WriteString(": ")
		}
		rule := p.rstack[len(p.rstack)-1]
		if rule.displayName != "" {
			buf.WriteString("rule " + rule.displayName)
		} else {
			buf.WriteString("rule " + rule.name)
		}
	}
	pe := &parserError{Inner: err, pos: pos, prefix: buf.String(), expected: expected}
	p.errs.add(pe)
}

func (p *parser) failAt(fail bool, pos position, want string) {
	// process fail if parsing fails and not inverted or parsing succeeds and invert is set
	if fail == p.maxFailInvertExpected {
		if pos.offset < p.maxFailPos.offset {
			return
		}

		if pos.offset > p.maxFailPos.offset {
			p.maxFailPos = pos
			p.maxFailExpected = p.maxFailExpected[:0]
		}

		if p.maxFailInvertExpected {
			want = "!" + want
		}
		p.maxFailExpected = append(p.maxFailExpected, want)
	}
}

// read advances the parser to the next rune.
func (p *parser) read() {
	p.pt.offset += p.pt.w
	rn, n := utf8.DecodeRune(p.data[p.pt.offset:])
	p.pt.rn = rn
	p.pt.w = n
	p.pt.col++
	if rn == '\n' {
		p.pt.line++
		p.pt.col = 0
	}

	if rn == utf8.RuneError && n == 1 { // see utf8.DecodeRune
		if !p.allowInvalidUTF8 {
			p.addErr(errInvalidEncoding)
		}
	}
}

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) {
	if p.debug {
		defer p.out(p.in("restore"))
	}
	if pt.offset == p.pt.offset {
		return
	}
	p.pt = pt
}

// Cloner is implemented by any value that has a Clone method, which returns a
// copy of the value. This is mainly used for types which are not passed by
// value (e.g map, slice, chan) or structs that contain such types.
//
// This is used in conjunction with the global state feature to create proper
// copies of the state to allow the parser to properly restore the state in
// the case of backtracking.
type Cloner interface {
	Clone() any
}

var statePool = &sync.Pool{
	New: func() any { return make(storeDict) },
}

func (sd storeDict) Discard() {
	for k := range sd {
		delete(sd, k)
	}
	statePool.Put(sd)
}

// clone and return parser current state.
func (p *parser) cloneState() storeDict {
	if p.debug {
		defer p.out(p.in("cloneState"))
	}

	state := statePool.Get().(storeDict)
	for k, v := range p.cur.state {
		if c, ok := v.(Cloner); ok {
			state[k] = c.Clone()
		} else {
			state[k] = v
		}
	}
	return state
}

// restore parser current state to the state storeDict.
// every restoreState should applied only one time for every cloned state
func (p *parser) restoreState(state storeDict) {
	if p.debug {
		defer p.out(p.in("restoreState"))
	}
	p.cur.state.Discard()
	p.cur.state = state
}

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte {
	return p.data[start.position.offset:p.pt.position.offset]
}

func (p *parser) getMemoized(node any) (resultTuple, bool) {
	if len(p.memo) == 0 {
		return resultTuple{}, false
	}
	m := p.memo[p.pt.offset]
	if len(m) == 0 {
		return resultTuple{}, false
	}
	res, ok := m[node]
	return res, ok
}

func (p *parser) setMemoized(pt savepoint, node any, tuple resultTuple) {
	if p.memo == nil {
		p.memo = make(map[int]map[any]resultTuple)
	}
	m := p.memo[pt.offset]
	if m == nil {
		m = make(map[any]resultTuple)
		p.memo[pt.offset] = m
	}
	m[node] = tuple
}

func (p *parser) buildRulesTable(g *grammar) {
	p.rules = make(map[string]*rule, len(g.rules))
	for _, r := range g.rules {
		p.rules[r.name] = r
	}
}

func (p *parser) parse(g *grammar) (val any, err error) {
	if len(g.rules) == 0 {
		p.addErr(errNoRule)
		return nil, p.errs.err()
	}

	// TODO : not super critical but this could be generated
	p.buildRulesTable(g)

	if p.recover {
		// panic can be used in action code to stop parsing immediately
		// and return the panic as an error.
		defer func() {
			if e := recover(); e != nil {
				if p.debug {
					defer p.out(p.in("panic handler"))
				}
				val = nil
				switch e := e.(type) {
				case error:
					p.addErr(e)
				default:
					p.addErr(fmt.Errorf("%v", e))
				}
				err = p.errs.err()
			}
		}()
	}

	startRule, ok := p.rules[p.entrypoint]
	if !ok {
		p.addErr(errInvalidEntrypoint)
		return nil, p.errs.err()
	}

	p.read() // advance to first rune
	val, ok = p.parseRuleWrap(startRule)
	if !ok {
		if len(*p.errs) == 0 {
			// If parsing fails, but no errors have been recorded, the expected values
			// for the farthest parser position are returned as error.
			maxFailExpectedMap := make(map[string]struct{}, len(p.maxFailExpected))
			for _, v := range p.maxFailExpected {
				maxFailExpectedMap[v] = struct{}{}
			}
			expected := make([]string, 0, len(maxFailExpectedMap))
			eof := false
			if _, ok := maxFailExpectedMap["!."]; ok {
				delete(maxFailExpectedMap, "!.")
				eof = true
			}
			for k := range maxFailExpectedMap {
				expected = append(expected, k)
			}
			sort.Strings(expected)
			if eof {
				expected = append(expected, "EOF")
			}
			p.addErrAt(errors.New("no match found, expected: "+listJoin(expected, ", ", "or")), p.maxFailPos, expected)
		}

		return nil, p.errs.err()
	}
	return val, p.errs.err()
}

func listJoin(list []string, sep string, lastSep string) string {
	switch len(list) {
	case 0:
		return ""
	case 1:
		return list[0]
	default:
		return strings.Join(list[:len(list)-1], sep) + " " + lastSep + " " + list[len(list)-1]
	}
}

func (p *parser) parseRuleMemoize(rule *rule) (any, bool) {
	res, ok := p.getMemoized(rule)
	if ok {
		p.restore(res.end)
		return res.v, res.b
	}

	startMark := p.pt
	val, ok := p.parseRule(rule)
	p.setMemoized(startMark, rule, resultTuple{val, ok, p.pt})

	return val, ok
}

func (p *parser) parseRuleWrap(rule *rule) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRule " + rule.name))
	}
	var (
		val       any
		ok        bool
		startMark = p.pt
	)

	if p.memoize {
		val, ok = p.parseRuleMemoize(rule)
	} else {
		val, ok = p.parseRule(rule)
	}

	if ok && p.debug {
		p.printIndent("MATCH", string(p.sliceFrom(startMark)))
	}
	return val, ok
}

func (p *parser) parseRule(rule *rule) (any, bool) {
	p.rstack = append(p.rstack, rule)
	p.pushV()
	val, ok := p.parseExprWrap(rule.expr)
	p.popV()
	p.rstack = p.rstack[:len(p.rstack)-1]
	return val, ok
}

func (p *parser) parseExprWrap(expr any) (any, bool) {
	var pt savepoint

	if p.memoize {
		res, ok := p.getMemoized(expr)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
		pt = p.pt
	}

	val, ok := p.parseExpr(expr)

	if p.memoize {
		p.setMemoized(pt, expr, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseExpr(expr any) (any, bool) {
	p.ExprCnt++
	if p.ExprCnt > p.maxExprCnt {
		panic(errMaxExprCnt)
	}

	var val any
	var ok bool
	switch expr := expr.(type) {
	case *actionExpr:
		val, ok = p.parseActionExpr(expr)
	case *andCodeExpr:
		val, ok = p.parseAndCodeExpr(expr)
	case *andExpr:
		val, ok = p.parseAndExpr(expr)
	case *anyMatcher:
		val, ok = p.parseAnyMatcher(expr)
	case *charClassMatcher:
		val, ok = p.parseCharClassMatcher(expr)
	case *choiceExpr:
		val, ok = p.parseChoiceExpr(expr)
	case *labeledExpr:
		val, ok = p.parseLabeledExpr(expr)
	case *litMatcher:
		val, ok = p.parseLitMatcher(expr)
	case *notCodeExpr:
		val, ok = p.parseNotCodeExpr(expr)
	case *notExpr:
		val, ok = p.parseNotExpr(expr)
	case *oneOrMoreExpr:
		val, ok = p.parseOneOrMoreExpr(expr)
	case *recoveryExpr:
		val, ok = p.parseRecoveryExpr(expr)
	case *ruleRefExpr:
		val, ok = p.parseRuleRefExpr(expr)
	case *seqExpr:
		val, ok = p.parseSeqExpr(expr)
	case *stateCodeExpr:
		val, ok = p.parseStateCodeExpr(expr)
	case *throwExpr:
		val, ok = p.parseThrowExpr(expr)
	case *zeroOrMoreExpr:
		val, ok = p.parseZeroOrMoreExpr(expr)
	case *zeroOrOneExpr:
		val, ok = p.parseZeroOrOneExpr(expr)
	default:
		panic(fmt.Sprintf("unknown expression type %T", expr))
	}
	return val, ok
}

func (p *parser) parseActionExpr(act *actionExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseActionExpr"))
	}

	start := p.pt
	val, ok := p.parseExprWrap(act.expr)
	if ok {
		p.cur.pos = start.position
		p.cur.text = p.sliceFrom(start)
		state := p.cloneState()
		actVal, err := act.run(p)
		if err != nil {
			p.addErrAt(err, start.position, []string{})
		}
		p.restoreState(state)

		val = actVal
	}
	if ok && p.debug {
		p.printIndent("MATCH", string(p.sliceFrom(start)))
	}
	return val, ok
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAndCodeExpr"))
	}

	state := p.cloneState()

	ok, err := and.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, ok
}

func (p *parser) parseAndExpr(and *andExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAndExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	_, ok := p.parseExprWrap(and.expr)
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, ok
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAnyMatcher"))
	}

	if p.pt.rn == utf8.RuneError && p.pt.w == 0 {
		// EOF - see utf8.DecodeRune
		p.failAt(false, p.pt.position, ".")
		return nil, false
	}
	start := p.pt
	p.read()
	p.failAt(true, start.position, ".")
	return p.sliceFrom(start), true
}

func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseCharClassMatcher"))
	}

	cur := p.pt.rn
	start := p.pt

	// can't match EOF
	if cur == utf8.RuneError && p.pt.w == 0 { // see utf8.DecodeRune
		p.failAt(false, start.position, chr.val)
		return nil, false
	}

	if chr.ignoreCase {
		cur = unicode.ToLower(cur)
	}

	// try to match in the list of available chars
	for _, rn := range chr.chars {
		if rn == cur {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of ranges
	for i := 0; i < len(chr.ranges); i += 2 {
		if cur >= chr.ranges[i] && cur <= chr.ranges[i+1] {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of Unicode classes
	for _, cl := range chr.classes {
		if unicode.Is(cl, cur) {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	if chr.inverted {
		p.read()
		p.failAt(true, start.position, chr.val)
		return p.sliceFrom(start), true
	}
	p.failAt(false, start.position, chr.val)
	return nil, false
}

func (p *parser) incChoiceAltCnt(ch *choiceExpr, altI int) {
	choiceIdent := fmt.Sprintf("%s %d:%d", p.rstack[len(p.rstack)-1].name, ch.pos.line, ch.pos.col)
	m := p.ChoiceAltCnt[choiceIdent]
	if m == nil {
		m = make(map[string]int)
		p.ChoiceAltCnt[choiceIdent] = m
	}
	// We increment altI by 1, so the keys do not start at 0
	alt := strconv.Itoa(altI + 1)
	if altI == choiceNoMatch {
		alt = p.choiceNoMatch
	}
	m[alt]++
}

func (p *parser) parseChoiceExpr(ch *choiceExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseChoiceExpr"))
	}

	for altI, alt := range ch.alternatives {
		// dummy assignment to prevent compile error if optimized
		_ = altI

		state := p.cloneState()

		p.pushV()
		val, ok := p.parseExprWrap(alt)
		p.popV()
		if ok {
			p.incChoiceAltCnt(ch, altI)
			return val, ok
		}
		p.restoreState(state)
	}
	p.incChoiceAltCnt(ch, choiceNoMatch)
	return nil, false
}

func (p *parser) parseLabeledExpr(lab *labeledExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseLabeledExpr"))
	}

	p.pushV()
	val, ok := p.parseExprWrap(lab.expr)
	p.popV()
	if ok && lab.label != "" {
		m := p.vstack[len(p.vstack)-1]
		m[lab.label] = val
	}
	return val, ok
}

func (p *parser) parseLitMatcher(lit *litMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseLitMatcher"))
	}

	start := p.pt
	for _, want := range lit.val {
		cur := p.pt.rn
		if lit.ignoreCase {
			cur = unicode.ToLower(cur)
		}
		if cur != want {
			p.failAt(false, start.position, lit.want)
			p.restore(start)
			return nil, false
		}
		p.read()
	}
	p.failAt(true, start.position, lit.want)
	return p.sliceFrom(start), true
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseNotCodeExpr"))
	}

	state := p.cloneState()

	ok, err := not.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, !ok
}

func (p *parser) parseNotExpr(not *notExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseNotExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	_, ok := p.parseExprWrap(not.expr)
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, !ok
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseOneOrMoreExpr"))
	}

	var vals []any

	for {
		p.pushV()
		val, ok := p.parseExprWrap(expr.expr)
		p.popV()
		if !ok {
			if len(vals) == 0 {
				// did not match once, no match
				return nil, false
			}
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseRecoveryExpr(recover *recoveryExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRecoveryExpr (" + strings.Join(recover.failureLabel, ",") + ")"))
	}

	p.pushRecovery(recover.failureLabel, recover.recoverExpr)
	val, ok := p.parseExprWrap(recover.expr)
	p.popRecovery()

	return val, ok
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRuleRefExpr " + ref.name))
	}

	if ref.name == "" {
		panic(fmt.Sprintf("%s: invalid rule: missing name", ref.pos))
	}

	rule := p.rules[ref.name]
	if rule == nil {
		p.addErr(fmt.Errorf("undefined rule: %s", ref.name))
		return nil, false
	}
	return p.parseRuleWrap(rule)
}

func (p *parser) parseSeqExpr(seq *seqExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseSeqExpr"))
	}

	vals := make([]any, 0, len(seq.exprs))

	pt := p.pt
	state := p.cloneState()
	for _, expr := range seq.exprs {
		val, ok := p.parseExprWrap(expr)
		if !ok {
			p.restoreState(state)
			p.restore(pt)
			return nil, false
		}
		vals = append(vals, val)
	}
	return vals, true
}

func (p *parser) parseStateCodeExpr(state *stateCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseStateCodeExpr"))
	}

	err := state.run(p)
	if err != nil {
		p.addErr(err)
	}
	return nil, true
}

func (p *parser) parseThrowExpr(expr *throwExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseThrowExpr"))
	}

	for i := len(p.recoveryStack) - 1; i >= 0; i-- {
		if recoverExpr, ok := p.recoveryStack[i][expr.label]; ok {
			if val, ok := p.parseExprWrap(recoverExpr); ok {
				return val, ok
			}
		}
	}

	return nil, false
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrMoreExpr"))
	}

	var vals []any

	for {
		p.pushV()
		val, ok := p.parseExprWrap(expr.expr)
		p.popV()
		if !ok {
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrOneExpr"))
	}

	p.pushV()
	val, _ := p.parseExprWrap(expr.expr)
	p.popV()
	// whether it matched or not, consider it a match
	return val, true
}
