// Code generated by pigeon; DO NOT EDIT.

// Package movements implements a Pigeon parser for unit movements.
package movements

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"log"
	"math"
	"os"
	"sort"
	"strconv"
	"strings"
	"sync"
	"unicode"
	"unicode/utf8"

	"github.com/mdhender/ottomap/directions"
	"github.com/mdhender/ottomap/domain"
)

// I'm not happy with the abstraction here, but...
//
// Movement captures a series of "wants" and "results."
// The unit wants to move in a certain direction and here are the results.
//
// Step is one piece of that movement. It captures the hex where
// the unit started (From), the direction, and the result (where
// the unit ended up (which could be where it started!), reasons
// why the step failed (it was blocked by an edge feature, it was
// blocked by the destination's terrain (water or mountains?), or
// didn't have enough movement points. Maybe even something like
// wagons can't enter a swamp hex. If the step failed because of a
// lack of movement points, we'll usually be told what the terrain
// type of the would-be destination hex it. If the step succeeded,
// we'll be told the terrain type and (usually) details about the
// edges, too. I don't think that occupants are mentioned when
// moving; that's reserved for scouting.

type Step struct {
	// direction will be Unknown when unit doesn't try to move
	Direction directions.Direction
	Result    Result
	// Hex is the hex where the unit ended up. It could be the same
	// as where it started if the step failed
	Hex Hex
}

type Result int

const (
	StayedInPlace Result = iota
	Succeeded
	Blocked
	ExhaustedMovementPoints
)

type Hex struct {
	Terrain     domain.Terrain
	Resource    domain.Resource
	Edges       []*Edge
	Neighbors   []*Neighbor
	Resources   []domain.Resource
	Settlements []*Settlement
	Occupants   []string
}

type Edge struct {
	Direction directions.Direction
	Edge      domain.Edge
}

type BlockedBy struct {
	Direction directions.Direction
	Terrain   domain.Terrain
}

type Exhausted struct {
	Direction directions.Direction
	Terrain   domain.Terrain
}

type Neighbor struct {
	Direction directions.Direction
	Terrain   domain.Terrain
}

type Settlement struct {
	Name string
}

func toAnySlice(v any) []any {
	if v == nil {
		return nil
	}
	return v.([]any)
}

var g = &grammar{
	rules: []*rule{
		{
			name: "Step",
			pos:  position{line: 89, col: 1, offset: 2251},
			expr: &choiceExpr{
				pos: position{line: 89, col: 9, offset: 2259},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 89, col: 9, offset: 2259},
						run: (*parser).callonStep2,
						expr: &seqExpr{
							pos: position{line: 89, col: 9, offset: 2259},
							exprs: []any{
								&labeledExpr{
									pos:   position{line: 89, col: 9, offset: 2259},
									label: "d",
									expr: &ruleRefExpr{
										pos:  position{line: 89, col: 11, offset: 2261},
										name: "DIRECTION",
									},
								},
								&litMatcher{
									pos:        position{line: 89, col: 21, offset: 2271},
									val:        "-",
									ignoreCase: false,
									want:       "\"-\"",
								},
								&labeledExpr{
									pos:   position{line: 89, col: 25, offset: 2275},
									label: "t",
									expr: &ruleRefExpr{
										pos:  position{line: 89, col: 27, offset: 2277},
										name: "TERRAIN",
									},
								},
								&labeledExpr{
									pos:   position{line: 89, col: 35, offset: 2285},
									label: "cfi",
									expr: &zeroOrMoreExpr{
										pos: position{line: 89, col: 39, offset: 2289},
										expr: &ruleRefExpr{
											pos:  position{line: 89, col: 39, offset: 2289},
											name: "CommaFound",
										},
									},
								},
								&ruleRefExpr{
									pos:  position{line: 89, col: 51, offset: 2301},
									name: "_",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 113, col: 5, offset: 2962},
						run: (*parser).callonStep13,
						expr: &seqExpr{
							pos: position{line: 113, col: 5, offset: 2962},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 113, col: 5, offset: 2962},
									val:        "Not enough M.P's to move to",
									ignoreCase: false,
									want:       "\"Not enough M.P's to move to\"",
								},
								&ruleRefExpr{
									pos:  position{line: 113, col: 35, offset: 2992},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 113, col: 37, offset: 2994},
									label: "d",
									expr: &ruleRefExpr{
										pos:  position{line: 113, col: 39, offset: 2996},
										name: "DIRECTION",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 113, col: 49, offset: 3006},
									name: "_",
								},
								&litMatcher{
									pos:        position{line: 113, col: 51, offset: 3008},
									val:        "into",
									ignoreCase: false,
									want:       "\"into\"",
								},
								&ruleRefExpr{
									pos:  position{line: 113, col: 58, offset: 3015},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 113, col: 60, offset: 3017},
									label: "t",
									expr: &ruleRefExpr{
										pos:  position{line: 113, col: 62, offset: 3019},
										name: "TERRAIN",
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 124, col: 5, offset: 3338},
						run: (*parser).callonStep24,
						expr: &seqExpr{
							pos: position{line: 124, col: 5, offset: 3338},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 124, col: 5, offset: 3338},
									val:        "Can't Move on",
									ignoreCase: false,
									want:       "\"Can't Move on\"",
								},
								&ruleRefExpr{
									pos:  position{line: 124, col: 21, offset: 3354},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 124, col: 23, offset: 3356},
									label: "t",
									expr: &ruleRefExpr{
										pos:  position{line: 124, col: 25, offset: 3358},
										name: "BlockedType",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 124, col: 37, offset: 3370},
									name: "_",
								},
								&litMatcher{
									pos:        position{line: 124, col: 39, offset: 3372},
									val:        "to",
									ignoreCase: false,
									want:       "\"to\"",
								},
								&ruleRefExpr{
									pos:  position{line: 124, col: 44, offset: 3377},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 124, col: 46, offset: 3379},
									label: "d",
									expr: &ruleRefExpr{
										pos:  position{line: 124, col: 48, offset: 3381},
										name: "DIRECTION",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 124, col: 58, offset: 3391},
									name: "_",
								},
								&litMatcher{
									pos:        position{line: 124, col: 60, offset: 3393},
									val:        "of HEX",
									ignoreCase: false,
									want:       "\"of HEX\"",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "CommaFound",
			pos:  position{line: 137, col: 1, offset: 3696},
			expr: &actionExpr{
				pos: position{line: 137, col: 15, offset: 3710},
				run: (*parser).callonCommaFound1,
				expr: &seqExpr{
					pos: position{line: 137, col: 15, offset: 3710},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 137, col: 15, offset: 3710},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 137, col: 17, offset: 3712},
							val:        ",",
							ignoreCase: false,
							want:       "\",\"",
						},
						&ruleRefExpr{
							pos:  position{line: 137, col: 21, offset: 3716},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 137, col: 23, offset: 3718},
							label: "f",
							expr: &ruleRefExpr{
								pos:  position{line: 137, col: 25, offset: 3720},
								name: "Found",
							},
						},
					},
				},
			},
		},
		{
			name: "Found",
			pos:  position{line: 141, col: 1, offset: 3749},
			expr: &choiceExpr{
				pos: position{line: 141, col: 10, offset: 3758},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 141, col: 10, offset: 3758},
						run: (*parser).callonFound2,
						expr: &labeledExpr{
							pos:   position{line: 141, col: 10, offset: 3758},
							label: "e",
							expr: &ruleRefExpr{
								pos:  position{line: 141, col: 12, offset: 3760},
								name: "Edges",
							},
						},
					},
					&actionExpr{
						pos: position{line: 143, col: 5, offset: 3790},
						run: (*parser).callonFound5,
						expr: &ruleRefExpr{
							pos:  position{line: 143, col: 5, offset: 3790},
							name: "_",
						},
					},
				},
			},
		},
		{
			name: "Hex",
			pos:  position{line: 147, col: 1, offset: 3819},
			expr: &actionExpr{
				pos: position{line: 147, col: 8, offset: 3826},
				run: (*parser).callonHex1,
				expr: &ruleRefExpr{
					pos:  position{line: 147, col: 8, offset: 3826},
					name: "_",
				},
			},
		},
		{
			name: "Edges",
			pos:  position{line: 152, col: 1, offset: 3911},
			expr: &actionExpr{
				pos: position{line: 152, col: 10, offset: 3920},
				run: (*parser).callonEdges1,
				expr: &seqExpr{
					pos: position{line: 152, col: 10, offset: 3920},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 152, col: 10, offset: 3920},
							label: "et",
							expr: &ruleRefExpr{
								pos:  position{line: 152, col: 13, offset: 3923},
								name: "EdgeType",
							},
						},
						&oneOrMoreExpr{
							pos: position{line: 152, col: 22, offset: 3932},
							expr: &ruleRefExpr{
								pos:  position{line: 152, col: 22, offset: 3932},
								name: "SP",
							},
						},
						&labeledExpr{
							pos:   position{line: 152, col: 26, offset: 3936},
							label: "d",
							expr: &ruleRefExpr{
								pos:  position{line: 152, col: 28, offset: 3938},
								name: "DIRECTION",
							},
						},
						&labeledExpr{
							pos:   position{line: 152, col: 38, offset: 3948},
							label: "edi",
							expr: &zeroOrMoreExpr{
								pos: position{line: 152, col: 42, offset: 3952},
								expr: &ruleRefExpr{
									pos:  position{line: 152, col: 42, offset: 3952},
									name: "SpaceDirection",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "EdgeType",
			pos:  position{line: 166, col: 1, offset: 4364},
			expr: &choiceExpr{
				pos: position{line: 166, col: 13, offset: 4376},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 166, col: 13, offset: 4376},
						run: (*parser).callonEdgeType2,
						expr: &litMatcher{
							pos:        position{line: 166, col: 13, offset: 4376},
							val:        "Ford",
							ignoreCase: false,
							want:       "\"Ford\"",
						},
					},
					&actionExpr{
						pos: position{line: 168, col: 5, offset: 4418},
						run: (*parser).callonEdgeType4,
						expr: &litMatcher{
							pos:        position{line: 168, col: 5, offset: 4418},
							val:        "Pass",
							ignoreCase: false,
							want:       "\"Pass\"",
						},
					},
					&actionExpr{
						pos: position{line: 170, col: 5, offset: 4460},
						run: (*parser).callonEdgeType6,
						expr: &litMatcher{
							pos:        position{line: 170, col: 5, offset: 4460},
							val:        "River",
							ignoreCase: false,
							want:       "\"River\"",
						},
					},
				},
			},
		},
		{
			name: "SpaceDirection",
			pos:  position{line: 174, col: 1, offset: 4503},
			expr: &actionExpr{
				pos: position{line: 174, col: 19, offset: 4521},
				run: (*parser).callonSpaceDirection1,
				expr: &seqExpr{
					pos: position{line: 174, col: 19, offset: 4521},
					exprs: []any{
						&oneOrMoreExpr{
							pos: position{line: 174, col: 19, offset: 4521},
							expr: &ruleRefExpr{
								pos:  position{line: 174, col: 19, offset: 4521},
								name: "SP",
							},
						},
						&labeledExpr{
							pos:   position{line: 174, col: 23, offset: 4525},
							label: "d",
							expr: &ruleRefExpr{
								pos:  position{line: 174, col: 25, offset: 4527},
								name: "DIRECTION",
							},
						},
					},
				},
			},
		},
		{
			name: "SlashStep",
			pos:  position{line: 178, col: 1, offset: 4560},
			expr: &actionExpr{
				pos: position{line: 178, col: 14, offset: 4573},
				run: (*parser).callonSlashStep1,
				expr: &seqExpr{
					pos: position{line: 178, col: 14, offset: 4573},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 178, col: 14, offset: 4573},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 178, col: 16, offset: 4575},
							val:        "\\",
							ignoreCase: false,
							want:       "\"\\\\\"",
						},
						&ruleRefExpr{
							pos:  position{line: 178, col: 21, offset: 4580},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 178, col: 23, offset: 4582},
							label: "s",
							expr: &ruleRefExpr{
								pos:  position{line: 178, col: 25, offset: 4584},
								name: "Step",
							},
						},
					},
				},
			},
		},
		{
			name: "BlockedType",
			pos:  position{line: 182, col: 1, offset: 4612},
			expr: &choiceExpr{
				pos: position{line: 182, col: 16, offset: 4627},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 182, col: 16, offset: 4627},
						run: (*parser).callonBlockedType2,
						expr: &litMatcher{
							pos:        position{line: 182, col: 16, offset: 4627},
							val:        "Lake",
							ignoreCase: false,
							want:       "\"Lake\"",
						},
					},
					&actionExpr{
						pos: position{line: 184, col: 5, offset: 4669},
						run: (*parser).callonBlockedType4,
						expr: &litMatcher{
							pos:        position{line: 184, col: 5, offset: 4669},
							val:        "Ocean",
							ignoreCase: false,
							want:       "\"Ocean\"",
						},
					},
				},
			},
		},
		{
			name: "DIRECTION",
			pos:  position{line: 188, col: 1, offset: 4712},
			expr: &choiceExpr{
				pos: position{line: 188, col: 14, offset: 4725},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 188, col: 14, offset: 4725},
						run: (*parser).callonDIRECTION2,
						expr: &litMatcher{
							pos:        position{line: 188, col: 14, offset: 4725},
							val:        "NE",
							ignoreCase: false,
							want:       "\"NE\"",
						},
					},
					&actionExpr{
						pos: position{line: 190, col: 5, offset: 4774},
						run: (*parser).callonDIRECTION4,
						expr: &litMatcher{
							pos:        position{line: 190, col: 5, offset: 4774},
							val:        "SE",
							ignoreCase: false,
							want:       "\"SE\"",
						},
					},
					&actionExpr{
						pos: position{line: 192, col: 5, offset: 4823},
						run: (*parser).callonDIRECTION6,
						expr: &litMatcher{
							pos:        position{line: 192, col: 5, offset: 4823},
							val:        "SW",
							ignoreCase: false,
							want:       "\"SW\"",
						},
					},
					&actionExpr{
						pos: position{line: 194, col: 5, offset: 4872},
						run: (*parser).callonDIRECTION8,
						expr: &litMatcher{
							pos:        position{line: 194, col: 5, offset: 4872},
							val:        "NW",
							ignoreCase: false,
							want:       "\"NW\"",
						},
					},
					&actionExpr{
						pos: position{line: 196, col: 5, offset: 4921},
						run: (*parser).callonDIRECTION10,
						expr: &litMatcher{
							pos:        position{line: 196, col: 5, offset: 4921},
							val:        "N",
							ignoreCase: false,
							want:       "\"N\"",
						},
					},
					&actionExpr{
						pos: position{line: 198, col: 5, offset: 4965},
						run: (*parser).callonDIRECTION12,
						expr: &litMatcher{
							pos:        position{line: 198, col: 5, offset: 4965},
							val:        "S",
							ignoreCase: false,
							want:       "\"S\"",
						},
					},
				},
			},
		},
		{
			name: "TERRAIN",
			pos:  position{line: 202, col: 1, offset: 5008},
			expr: &choiceExpr{
				pos: position{line: 202, col: 12, offset: 5019},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 202, col: 12, offset: 5019},
						run: (*parser).callonTERRAIN2,
						expr: &litMatcher{
							pos:        position{line: 202, col: 12, offset: 5019},
							val:        "CONIFER HILLS",
							ignoreCase: false,
							want:       "\"CONIFER HILLS\"",
						},
					},
					&actionExpr{
						pos: position{line: 204, col: 5, offset: 5078},
						run: (*parser).callonTERRAIN4,
						expr: &litMatcher{
							pos:        position{line: 204, col: 5, offset: 5078},
							val:        "GRASSY HILLS",
							ignoreCase: false,
							want:       "\"GRASSY HILLS\"",
						},
					},
					&actionExpr{
						pos: position{line: 206, col: 5, offset: 5135},
						run: (*parser).callonTERRAIN6,
						expr: &litMatcher{
							pos:        position{line: 206, col: 5, offset: 5135},
							val:        "PRAIRIE",
							ignoreCase: false,
							want:       "\"PRAIRIE\"",
						},
					},
					&actionExpr{
						pos: position{line: 208, col: 5, offset: 5183},
						run: (*parser).callonTERRAIN8,
						expr: &litMatcher{
							pos:        position{line: 208, col: 5, offset: 5183},
							val:        "ROCKY HILLS",
							ignoreCase: false,
							want:       "\"ROCKY HILLS\"",
						},
					},
					&actionExpr{
						pos: position{line: 210, col: 5, offset: 5238},
						run: (*parser).callonTERRAIN10,
						expr: &litMatcher{
							pos:        position{line: 210, col: 5, offset: 5238},
							val:        "SWAMP",
							ignoreCase: false,
							want:       "\"SWAMP\"",
						},
					},
					&actionExpr{
						pos: position{line: 212, col: 5, offset: 5282},
						run: (*parser).callonTERRAIN12,
						expr: &litMatcher{
							pos:        position{line: 212, col: 5, offset: 5282},
							val:        "LAKE",
							ignoreCase: false,
							want:       "\"LAKE\"",
						},
					},
					&actionExpr{
						pos: position{line: 214, col: 5, offset: 5324},
						run: (*parser).callonTERRAIN14,
						expr: &litMatcher{
							pos:        position{line: 214, col: 5, offset: 5324},
							val:        "OCEAN",
							ignoreCase: false,
							want:       "\"OCEAN\"",
						},
					},
					&actionExpr{
						pos: position{line: 216, col: 5, offset: 5368},
						run: (*parser).callonTERRAIN16,
						expr: &litMatcher{
							pos:        position{line: 216, col: 5, offset: 5368},
							val:        "CH",
							ignoreCase: false,
							want:       "\"CH\"",
						},
					},
					&actionExpr{
						pos: position{line: 218, col: 5, offset: 5416},
						run: (*parser).callonTERRAIN18,
						expr: &litMatcher{
							pos:        position{line: 218, col: 5, offset: 5416},
							val:        "GH",
							ignoreCase: false,
							want:       "\"GH\"",
						},
					},
					&actionExpr{
						pos: position{line: 220, col: 5, offset: 5463},
						run: (*parser).callonTERRAIN20,
						expr: &litMatcher{
							pos:        position{line: 220, col: 5, offset: 5463},
							val:        "PR",
							ignoreCase: false,
							want:       "\"PR\"",
						},
					},
					&actionExpr{
						pos: position{line: 222, col: 5, offset: 5506},
						run: (*parser).callonTERRAIN22,
						expr: &litMatcher{
							pos:        position{line: 222, col: 5, offset: 5506},
							val:        "RH",
							ignoreCase: false,
							want:       "\"RH\"",
						},
					},
					&actionExpr{
						pos: position{line: 224, col: 5, offset: 5552},
						run: (*parser).callonTERRAIN24,
						expr: &litMatcher{
							pos:        position{line: 224, col: 5, offset: 5552},
							val:        "SW",
							ignoreCase: false,
							want:       "\"SW\"",
						},
					},
					&actionExpr{
						pos: position{line: 226, col: 5, offset: 5593},
						run: (*parser).callonTERRAIN26,
						expr: &litMatcher{
							pos:        position{line: 226, col: 5, offset: 5593},
							val:        "L",
							ignoreCase: false,
							want:       "\"L\"",
						},
					},
					&actionExpr{
						pos: position{line: 228, col: 5, offset: 5632},
						run: (*parser).callonTERRAIN28,
						expr: &litMatcher{
							pos:        position{line: 228, col: 5, offset: 5632},
							val:        "O",
							ignoreCase: false,
							want:       "\"O\"",
						},
					},
				},
			},
		},
		{
			name: "EOF",
			pos:  position{line: 232, col: 1, offset: 5671},
			expr: &notExpr{
				pos: position{line: 232, col: 10, offset: 5680},
				expr: &anyMatcher{
					line: 232, col: 11, offset: 5681,
				},
			},
		},
		{
			name: "DIGIT",
			pos:  position{line: 233, col: 1, offset: 5683},
			expr: &charClassMatcher{
				pos:        position{line: 233, col: 10, offset: 5692},
				val:        "[0-9]",
				ranges:     []rune{'0', '9'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "LETTER",
			pos:  position{line: 234, col: 1, offset: 5698},
			expr: &charClassMatcher{
				pos:        position{line: 234, col: 10, offset: 5707},
				val:        "[A-Z]",
				ranges:     []rune{'A', 'Z'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "SP",
			pos:  position{line: 235, col: 1, offset: 5713},
			expr: &charClassMatcher{
				pos:        position{line: 235, col: 10, offset: 5722},
				val:        "[ \\t]",
				chars:      []rune{' ', '\t'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "_",
			pos:  position{line: 236, col: 1, offset: 5728},
			expr: &zeroOrMoreExpr{
				pos: position{line: 236, col: 10, offset: 5737},
				expr: &charClassMatcher{
					pos:        position{line: 236, col: 10, offset: 5737},
					val:        "[ \\t]",
					chars:      []rune{' ', '\t'},
					ignoreCase: false,
					inverted:   false,
				},
			},
		},
	},
}

func (c *current) onStep2(d, t, cfi any) (any, error) {
	s := Step{
		Direction: d.(directions.Direction),
		Result:    Succeeded,
		Hex: Hex{
			Terrain: t.(domain.Terrain),
		},
	}
	for _, cf := range toAnySlice(cfi) {
		log.Printf("step: cf %T\n", cf)
		switch v := cf.(type) {
		case []*Edge:
			// merge into the step's hex
			for _, e := range v {
				s.Hex.Edges = append(s.Hex.Edges, e)
			}
		case Hex:
			// merge into the step's hex
			//steps = append(steps, v)
		default:
			panic(fmt.Errorf("unexpected type %T", v))
		}
	}
	return s, nil
}

func (p *parser) callonStep2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onStep2(stack["d"], stack["t"], stack["cfi"])
}

func (c *current) onStep13(d, t any) (any, error) {
	return Step{
		Direction: d.(directions.Direction),
		Result:    ExhaustedMovementPoints,
		Hex: Hex{
			Neighbors: []*Neighbor{{
				Direction: d.(directions.Direction),
				Terrain:   t.(domain.Terrain),
			}},
		},
	}, nil
}

func (p *parser) callonStep13() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onStep13(stack["d"], stack["t"])
}

func (c *current) onStep24(t, d any) (any, error) {
	return Step{
		Direction: d.(directions.Direction),
		Result:    Blocked,
		Hex: Hex{
			Neighbors: []*Neighbor{{
				Direction: d.(directions.Direction),
				Terrain:   t.(domain.Terrain),
			}},
		},
	}, nil
}

func (p *parser) callonStep24() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onStep24(stack["t"], stack["d"])
}

func (c *current) onCommaFound1(f any) (any, error) {
	return f, nil
}

func (p *parser) callonCommaFound1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCommaFound1(stack["f"])
}

func (c *current) onFound2(e any) (any, error) {
	return e, nil
}

func (p *parser) callonFound2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFound2(stack["e"])
}

func (c *current) onFound5() (any, error) {
	return Hex{}, nil
}

func (p *parser) callonFound5() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFound5()
}

func (c *current) onHex1() (any, error) {
	// sad, but true, we have input like "SE-GH, \\..."
	return Hex{}, nil
}

func (p *parser) callonHex1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onHex1()
}

func (c *current) onEdges1(et, d, edi any) (any, error) {
	kind := et.(domain.Edge)
	edges := []*Edge{&Edge{Direction: d.(directions.Direction), Edge: kind}}
	for _, ed := range toAnySlice(edi) {
		switch v := ed.(type) {
		case directions.Direction:
			edges = append(edges, &Edge{Direction: v, Edge: kind})
		default:
			panic(fmt.Errorf("unexpected type %T", v))
		}
	}
	return edges, nil
}

func (p *parser) callonEdges1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onEdges1(stack["et"], stack["d"], stack["edi"])
}

func (c *current) onEdgeType2() (any, error) {
	return domain.EFord, nil
}

func (p *parser) callonEdgeType2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onEdgeType2()
}

func (c *current) onEdgeType4() (any, error) {
	return domain.EPass, nil
}

func (p *parser) callonEdgeType4() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onEdgeType4()
}

func (c *current) onEdgeType6() (any, error) {
	return domain.ERiver, nil
}

func (p *parser) callonEdgeType6() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onEdgeType6()
}

func (c *current) onSpaceDirection1(d any) (any, error) {
	return d, nil
}

func (p *parser) callonSpaceDirection1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSpaceDirection1(stack["d"])
}

func (c *current) onSlashStep1(s any) (any, error) {
	return s, nil
}

func (p *parser) callonSlashStep1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSlashStep1(stack["s"])
}

func (c *current) onBlockedType2() (any, error) {
	return domain.TLake, nil
}

func (p *parser) callonBlockedType2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBlockedType2()
}

func (c *current) onBlockedType4() (any, error) {
	return domain.TOcean, nil
}

func (p *parser) callonBlockedType4() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBlockedType4()
}

func (c *current) onDIRECTION2() (any, error) {
	return directions.DNorthEast, nil
}

func (p *parser) callonDIRECTION2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDIRECTION2()
}

func (c *current) onDIRECTION4() (any, error) {
	return directions.DSouthEast, nil
}

func (p *parser) callonDIRECTION4() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDIRECTION4()
}

func (c *current) onDIRECTION6() (any, error) {
	return directions.DSouthWest, nil
}

func (p *parser) callonDIRECTION6() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDIRECTION6()
}

func (c *current) onDIRECTION8() (any, error) {
	return directions.DNorthWest, nil
}

func (p *parser) callonDIRECTION8() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDIRECTION8()
}

func (c *current) onDIRECTION10() (any, error) {
	return directions.DNorth, nil
}

func (p *parser) callonDIRECTION10() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDIRECTION10()
}

func (c *current) onDIRECTION12() (any, error) {
	return directions.DSouth, nil
}

func (p *parser) callonDIRECTION12() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDIRECTION12()
}

func (c *current) onTERRAIN2() (any, error) {
	return domain.TConiferHills, nil
}

func (p *parser) callonTERRAIN2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTERRAIN2()
}

func (c *current) onTERRAIN4() (any, error) {
	return domain.TGrassyHills, nil
}

func (p *parser) callonTERRAIN4() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTERRAIN4()
}

func (c *current) onTERRAIN6() (any, error) {
	return domain.TPrairie, nil
}

func (p *parser) callonTERRAIN6() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTERRAIN6()
}

func (c *current) onTERRAIN8() (any, error) {
	return domain.TRockyHills, nil
}

func (p *parser) callonTERRAIN8() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTERRAIN8()
}

func (c *current) onTERRAIN10() (any, error) {
	return domain.TSwamp, nil
}

func (p *parser) callonTERRAIN10() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTERRAIN10()
}

func (c *current) onTERRAIN12() (any, error) {
	return domain.TLake, nil
}

func (p *parser) callonTERRAIN12() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTERRAIN12()
}

func (c *current) onTERRAIN14() (any, error) {
	return domain.TOcean, nil
}

func (p *parser) callonTERRAIN14() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTERRAIN14()
}

func (c *current) onTERRAIN16() (any, error) {
	return domain.TConiferHills, nil
}

func (p *parser) callonTERRAIN16() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTERRAIN16()
}

func (c *current) onTERRAIN18() (any, error) {
	return domain.TGrassyHills, nil
}

func (p *parser) callonTERRAIN18() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTERRAIN18()
}

func (c *current) onTERRAIN20() (any, error) {
	return domain.TPrairie, nil
}

func (p *parser) callonTERRAIN20() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTERRAIN20()
}

func (c *current) onTERRAIN22() (any, error) {
	return domain.TRockyHills, nil
}

func (p *parser) callonTERRAIN22() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTERRAIN22()
}

func (c *current) onTERRAIN24() (any, error) {
	return domain.TSwamp, nil
}

func (p *parser) callonTERRAIN24() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTERRAIN24()
}

func (c *current) onTERRAIN26() (any, error) {
	return domain.TLake, nil
}

func (p *parser) callonTERRAIN26() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTERRAIN26()
}

func (c *current) onTERRAIN28() (any, error) {
	return domain.TOcean, nil
}

func (p *parser) callonTERRAIN28() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTERRAIN28()
}

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEntrypoint is returned when the specified entrypoint rule
	// does not exit.
	errInvalidEntrypoint = errors.New("invalid entrypoint")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errMaxExprCnt is used to signal that the maximum number of
	// expressions have been parsed.
	errMaxExprCnt = errors.New("max number of expresssions parsed")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// MaxExpressions creates an Option to stop parsing after the provided
// number of expressions have been parsed, if the value is 0 then the parser will
// parse for as many steps as needed (possibly an infinite number).
//
// The default for maxExprCnt is 0.
func MaxExpressions(maxExprCnt uint64) Option {
	return func(p *parser) Option {
		oldMaxExprCnt := p.maxExprCnt
		p.maxExprCnt = maxExprCnt
		return MaxExpressions(oldMaxExprCnt)
	}
}

// Entrypoint creates an Option to set the rule name to use as entrypoint.
// The rule name must have been specified in the -alternate-entrypoints
// if generating the parser with the -optimize-grammar flag, otherwise
// it may have been optimized out. Passing an empty string sets the
// entrypoint to the first rule in the grammar.
//
// The default is to start parsing at the first rule in the grammar.
func Entrypoint(ruleName string) Option {
	return func(p *parser) Option {
		oldEntrypoint := p.entrypoint
		p.entrypoint = ruleName
		if ruleName == "" {
			p.entrypoint = g.rules[0].name
		}
		return Entrypoint(oldEntrypoint)
	}
}

// Statistics adds a user provided Stats struct to the parser to allow
// the user to process the results after the parsing has finished.
// Also the key for the "no match" counter is set.
//
// Example usage:
//
//	input := "input"
//	stats := Stats{}
//	_, err := Parse("input-file", []byte(input), Statistics(&stats, "no match"))
//	if err != nil {
//	    log.Panicln(err)
//	}
//	b, err := json.MarshalIndent(stats.ChoiceAltCnt, "", "  ")
//	if err != nil {
//	    log.Panicln(err)
//	}
//	fmt.Println(string(b))
func Statistics(stats *Stats, choiceNoMatch string) Option {
	return func(p *parser) Option {
		oldStats := p.Stats
		p.Stats = stats
		oldChoiceNoMatch := p.choiceNoMatch
		p.choiceNoMatch = choiceNoMatch
		if p.Stats.ChoiceAltCnt == nil {
			p.Stats.ChoiceAltCnt = make(map[string]map[string]int)
		}
		return Statistics(oldStats, oldChoiceNoMatch)
	}
}

// Debug creates an Option to set the debug flag to b. When set to true,
// debugging information is printed to stdout while parsing.
//
// The default is false.
func Debug(b bool) Option {
	return func(p *parser) Option {
		old := p.debug
		p.debug = b
		return Debug(old)
	}
}

// Memoize creates an Option to set the memoize flag to b. When set to true,
// the parser will cache all results so each expression is evaluated only
// once. This guarantees linear parsing time even for pathological cases,
// at the expense of more memory and slower times for typical cases.
//
// The default is false.
func Memoize(b bool) Option {
	return func(p *parser) Option {
		old := p.memoize
		p.memoize = b
		return Memoize(old)
	}
}

// AllowInvalidUTF8 creates an Option to allow invalid UTF-8 bytes.
// Every invalid UTF-8 byte is treated as a utf8.RuneError (U+FFFD)
// by character class matchers and is matched by the any matcher.
// The returned matched value, c.text and c.offset are NOT affected.
//
// The default is false.
func AllowInvalidUTF8(b bool) Option {
	return func(p *parser) Option {
		old := p.allowInvalidUTF8
		p.allowInvalidUTF8 = b
		return AllowInvalidUTF8(old)
	}
}

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option {
	return func(p *parser) Option {
		old := p.recover
		p.recover = b
		return Recover(old)
	}
}

// GlobalStore creates an Option to set a key to a certain value in
// the globalStore.
func GlobalStore(key string, value any) Option {
	return func(p *parser) Option {
		old := p.cur.globalStore[key]
		p.cur.globalStore[key] = value
		return GlobalStore(key, old)
	}
}

// InitState creates an Option to set a key to a certain value in
// the global "state" store.
func InitState(key string, value any) Option {
	return func(p *parser) Option {
		old := p.cur.state[key]
		p.cur.state[key] = value
		return InitState(key, old)
	}
}

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (i any, err error) {
	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer func() {
		if closeErr := f.Close(); closeErr != nil {
			err = closeErr
		}
	}()
	return ParseReader(filename, f, opts...)
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (any, error) {
	b, err := io.ReadAll(r)
	if err != nil {
		return nil, err
	}

	return Parse(filename, b, opts...)
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (any, error) {
	return newParser(filename, b, opts...).parse(g)
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string {
	return strconv.Itoa(p.line) + ":" + strconv.Itoa(p.col) + " [" + strconv.Itoa(p.offset) + "]"
}

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match

	// state is a store for arbitrary key,value pairs that the user wants to be
	// tied to the backtracking of the parser.
	// This is always rolled back if a parsing rule fails.
	state storeDict

	// globalStore is a general store for the user to store arbitrary key-value
	// pairs that they need to manage and that they do not want tied to the
	// backtracking of the parser. This is only modified by the user and never
	// rolled back by the parser. It is always up to the user to keep this in a
	// consistent state.
	globalStore storeDict
}

type storeDict map[string]any

// the AST types...

type grammar struct {
	pos   position
	rules []*rule
}

type rule struct {
	pos         position
	name        string
	displayName string
	expr        any
}

type choiceExpr struct {
	pos          position
	alternatives []any
}

type actionExpr struct {
	pos  position
	expr any
	run  func(*parser) (any, error)
}

type recoveryExpr struct {
	pos          position
	expr         any
	recoverExpr  any
	failureLabel []string
}

type seqExpr struct {
	pos   position
	exprs []any
}

type throwExpr struct {
	pos   position
	label string
}

type labeledExpr struct {
	pos   position
	label string
	expr  any
}

type expr struct {
	pos  position
	expr any
}

type (
	andExpr        expr
	notExpr        expr
	zeroOrOneExpr  expr
	zeroOrMoreExpr expr
	oneOrMoreExpr  expr
)

type ruleRefExpr struct {
	pos  position
	name string
}

type stateCodeExpr struct {
	pos position
	run func(*parser) error
}

type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
	want       string
}

type charClassMatcher struct {
	pos             position
	val             string
	basicLatinChars [128]bool
	chars           []rune
	ranges          []rune
	classes         []*unicode.RangeTable
	ignoreCase      bool
	inverted        bool
}

type anyMatcher position

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) {
	*e = append(*e, err)
}

func (e errList) err() error {
	if len(e) == 0 {
		return nil
	}
	e.dedupe()
	return e
}

func (e *errList) dedupe() {
	var cleaned []error
	set := make(map[string]bool)
	for _, err := range *e {
		if msg := err.Error(); !set[msg] {
			set[msg] = true
			cleaned = append(cleaned, err)
		}
	}
	*e = cleaned
}

func (e errList) Error() string {
	switch len(e) {
	case 0:
		return ""
	case 1:
		return e[0].Error()
	default:
		var buf bytes.Buffer

		for i, err := range e {
			if i > 0 {
				buf.WriteRune('\n')
			}
			buf.WriteString(err.Error())
		}
		return buf.String()
	}
}

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner    error
	pos      position
	prefix   string
	expected []string
}

// Error returns the error message.
func (p *parserError) Error() string {
	return p.prefix + ": " + p.Inner.Error()
}

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	stats := Stats{
		ChoiceAltCnt: make(map[string]map[string]int),
	}

	p := &parser{
		filename: filename,
		errs:     new(errList),
		data:     b,
		pt:       savepoint{position: position{line: 1}},
		recover:  true,
		cur: current{
			state:       make(storeDict),
			globalStore: make(storeDict),
		},
		maxFailPos:      position{col: 1, line: 1},
		maxFailExpected: make([]string, 0, 20),
		Stats:           &stats,
		// start rule is rule [0] unless an alternate entrypoint is specified
		entrypoint: g.rules[0].name,
	}
	p.setOptions(opts)

	if p.maxExprCnt == 0 {
		p.maxExprCnt = math.MaxUint64
	}

	return p
}

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) {
	for _, opt := range opts {
		opt(p)
	}
}

type resultTuple struct {
	v   any
	b   bool
	end savepoint
}

const choiceNoMatch = -1

// Stats stores some statistics, gathered during parsing
type Stats struct {
	// ExprCnt counts the number of expressions processed during parsing
	// This value is compared to the maximum number of expressions allowed
	// (set by the MaxExpressions option).
	ExprCnt uint64

	// ChoiceAltCnt is used to count for each ordered choice expression,
	// which alternative is used how may times.
	// These numbers allow to optimize the order of the ordered choice expression
	// to increase the performance of the parser
	//
	// The outer key of ChoiceAltCnt is composed of the name of the rule as well
	// as the line and the column of the ordered choice.
	// The inner key of ChoiceAltCnt is the number (one-based) of the matching alternative.
	// For each alternative the number of matches are counted. If an ordered choice does not
	// match, a special counter is incremented. The name of this counter is set with
	// the parser option Statistics.
	// For an alternative to be included in ChoiceAltCnt, it has to match at least once.
	ChoiceAltCnt map[string]map[string]int
}

type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	depth   int
	recover bool
	debug   bool

	memoize bool
	// memoization table for the packrat algorithm:
	// map[offset in source] map[expression or rule] {value, match}
	memo map[int]map[any]resultTuple

	// rules table, maps the rule identifier to the rule node
	rules map[string]*rule
	// variables stack, map of label to value
	vstack []map[string]any
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// parse fail
	maxFailPos            position
	maxFailExpected       []string
	maxFailInvertExpected bool

	// max number of expressions to be parsed
	maxExprCnt uint64
	// entrypoint for the parser
	entrypoint string

	allowInvalidUTF8 bool

	*Stats

	choiceNoMatch string
	// recovery expression stack, keeps track of the currently available recovery expression, these are traversed in reverse
	recoveryStack []map[string]any
}

// push a variable set on the vstack.
func (p *parser) pushV() {
	if cap(p.vstack) == len(p.vstack) {
		// create new empty slot in the stack
		p.vstack = append(p.vstack, nil)
	} else {
		// slice to 1 more
		p.vstack = p.vstack[:len(p.vstack)+1]
	}

	// get the last args set
	m := p.vstack[len(p.vstack)-1]
	if m != nil && len(m) == 0 {
		// empty map, all good
		return
	}

	m = make(map[string]any)
	p.vstack[len(p.vstack)-1] = m
}

// pop a variable set from the vstack.
func (p *parser) popV() {
	// if the map is not empty, clear it
	m := p.vstack[len(p.vstack)-1]
	if len(m) > 0 {
		// GC that map
		p.vstack[len(p.vstack)-1] = nil
	}
	p.vstack = p.vstack[:len(p.vstack)-1]
}

// push a recovery expression with its labels to the recoveryStack
func (p *parser) pushRecovery(labels []string, expr any) {
	if cap(p.recoveryStack) == len(p.recoveryStack) {
		// create new empty slot in the stack
		p.recoveryStack = append(p.recoveryStack, nil)
	} else {
		// slice to 1 more
		p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)+1]
	}

	m := make(map[string]any, len(labels))
	for _, fl := range labels {
		m[fl] = expr
	}
	p.recoveryStack[len(p.recoveryStack)-1] = m
}

// pop a recovery expression from the recoveryStack
func (p *parser) popRecovery() {
	// GC that map
	p.recoveryStack[len(p.recoveryStack)-1] = nil

	p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)-1]
}

func (p *parser) print(prefix, s string) string {
	if !p.debug {
		return s
	}

	fmt.Printf("%s %d:%d:%d: %s [%#U]\n",
		prefix, p.pt.line, p.pt.col, p.pt.offset, s, p.pt.rn)
	return s
}

func (p *parser) printIndent(mark string, s string) string {
	return p.print(strings.Repeat(" ", p.depth)+mark, s)
}

func (p *parser) in(s string) string {
	res := p.printIndent(">", s)
	p.depth++
	return res
}

func (p *parser) out(s string) string {
	p.depth--
	return p.printIndent("<", s)
}

func (p *parser) addErr(err error) {
	p.addErrAt(err, p.pt.position, []string{})
}

func (p *parser) addErrAt(err error, pos position, expected []string) {
	var buf bytes.Buffer
	if p.filename != "" {
		buf.WriteString(p.filename)
	}
	if buf.Len() > 0 {
		buf.WriteString(":")
	}
	buf.WriteString(fmt.Sprintf("%d:%d (%d)", pos.line, pos.col, pos.offset))
	if len(p.rstack) > 0 {
		if buf.Len() > 0 {
			buf.WriteString(": ")
		}
		rule := p.rstack[len(p.rstack)-1]
		if rule.displayName != "" {
			buf.WriteString("rule " + rule.displayName)
		} else {
			buf.WriteString("rule " + rule.name)
		}
	}
	pe := &parserError{Inner: err, pos: pos, prefix: buf.String(), expected: expected}
	p.errs.add(pe)
}

func (p *parser) failAt(fail bool, pos position, want string) {
	// process fail if parsing fails and not inverted or parsing succeeds and invert is set
	if fail == p.maxFailInvertExpected {
		if pos.offset < p.maxFailPos.offset {
			return
		}

		if pos.offset > p.maxFailPos.offset {
			p.maxFailPos = pos
			p.maxFailExpected = p.maxFailExpected[:0]
		}

		if p.maxFailInvertExpected {
			want = "!" + want
		}
		p.maxFailExpected = append(p.maxFailExpected, want)
	}
}

// read advances the parser to the next rune.
func (p *parser) read() {
	p.pt.offset += p.pt.w
	rn, n := utf8.DecodeRune(p.data[p.pt.offset:])
	p.pt.rn = rn
	p.pt.w = n
	p.pt.col++
	if rn == '\n' {
		p.pt.line++
		p.pt.col = 0
	}

	if rn == utf8.RuneError && n == 1 { // see utf8.DecodeRune
		if !p.allowInvalidUTF8 {
			p.addErr(errInvalidEncoding)
		}
	}
}

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) {
	if p.debug {
		defer p.out(p.in("restore"))
	}
	if pt.offset == p.pt.offset {
		return
	}
	p.pt = pt
}

// Cloner is implemented by any value that has a Clone method, which returns a
// copy of the value. This is mainly used for types which are not passed by
// value (e.g map, slice, chan) or structs that contain such types.
//
// This is used in conjunction with the global state feature to create proper
// copies of the state to allow the parser to properly restore the state in
// the case of backtracking.
type Cloner interface {
	Clone() any
}

var statePool = &sync.Pool{
	New: func() any { return make(storeDict) },
}

func (sd storeDict) Discard() {
	for k := range sd {
		delete(sd, k)
	}
	statePool.Put(sd)
}

// clone and return parser current state.
func (p *parser) cloneState() storeDict {
	if p.debug {
		defer p.out(p.in("cloneState"))
	}

	state := statePool.Get().(storeDict)
	for k, v := range p.cur.state {
		if c, ok := v.(Cloner); ok {
			state[k] = c.Clone()
		} else {
			state[k] = v
		}
	}
	return state
}

// restore parser current state to the state storeDict.
// every restoreState should applied only one time for every cloned state
func (p *parser) restoreState(state storeDict) {
	if p.debug {
		defer p.out(p.in("restoreState"))
	}
	p.cur.state.Discard()
	p.cur.state = state
}

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte {
	return p.data[start.position.offset:p.pt.position.offset]
}

func (p *parser) getMemoized(node any) (resultTuple, bool) {
	if len(p.memo) == 0 {
		return resultTuple{}, false
	}
	m := p.memo[p.pt.offset]
	if len(m) == 0 {
		return resultTuple{}, false
	}
	res, ok := m[node]
	return res, ok
}

func (p *parser) setMemoized(pt savepoint, node any, tuple resultTuple) {
	if p.memo == nil {
		p.memo = make(map[int]map[any]resultTuple)
	}
	m := p.memo[pt.offset]
	if m == nil {
		m = make(map[any]resultTuple)
		p.memo[pt.offset] = m
	}
	m[node] = tuple
}

func (p *parser) buildRulesTable(g *grammar) {
	p.rules = make(map[string]*rule, len(g.rules))
	for _, r := range g.rules {
		p.rules[r.name] = r
	}
}

func (p *parser) parse(g *grammar) (val any, err error) {
	if len(g.rules) == 0 {
		p.addErr(errNoRule)
		return nil, p.errs.err()
	}

	// TODO : not super critical but this could be generated
	p.buildRulesTable(g)

	if p.recover {
		// panic can be used in action code to stop parsing immediately
		// and return the panic as an error.
		defer func() {
			if e := recover(); e != nil {
				if p.debug {
					defer p.out(p.in("panic handler"))
				}
				val = nil
				switch e := e.(type) {
				case error:
					p.addErr(e)
				default:
					p.addErr(fmt.Errorf("%v", e))
				}
				err = p.errs.err()
			}
		}()
	}

	startRule, ok := p.rules[p.entrypoint]
	if !ok {
		p.addErr(errInvalidEntrypoint)
		return nil, p.errs.err()
	}

	p.read() // advance to first rune
	val, ok = p.parseRuleWrap(startRule)
	if !ok {
		if len(*p.errs) == 0 {
			// If parsing fails, but no errors have been recorded, the expected values
			// for the farthest parser position are returned as error.
			maxFailExpectedMap := make(map[string]struct{}, len(p.maxFailExpected))
			for _, v := range p.maxFailExpected {
				maxFailExpectedMap[v] = struct{}{}
			}
			expected := make([]string, 0, len(maxFailExpectedMap))
			eof := false
			if _, ok := maxFailExpectedMap["!."]; ok {
				delete(maxFailExpectedMap, "!.")
				eof = true
			}
			for k := range maxFailExpectedMap {
				expected = append(expected, k)
			}
			sort.Strings(expected)
			if eof {
				expected = append(expected, "EOF")
			}
			p.addErrAt(errors.New("no match found, expected: "+listJoin(expected, ", ", "or")), p.maxFailPos, expected)
		}

		return nil, p.errs.err()
	}
	return val, p.errs.err()
}

func listJoin(list []string, sep string, lastSep string) string {
	switch len(list) {
	case 0:
		return ""
	case 1:
		return list[0]
	default:
		return strings.Join(list[:len(list)-1], sep) + " " + lastSep + " " + list[len(list)-1]
	}
}

func (p *parser) parseRuleMemoize(rule *rule) (any, bool) {
	res, ok := p.getMemoized(rule)
	if ok {
		p.restore(res.end)
		return res.v, res.b
	}

	startMark := p.pt
	val, ok := p.parseRule(rule)
	p.setMemoized(startMark, rule, resultTuple{val, ok, p.pt})

	return val, ok
}

func (p *parser) parseRuleWrap(rule *rule) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRule " + rule.name))
	}
	var (
		val       any
		ok        bool
		startMark = p.pt
	)

	if p.memoize {
		val, ok = p.parseRuleMemoize(rule)
	} else {
		val, ok = p.parseRule(rule)
	}

	if ok && p.debug {
		p.printIndent("MATCH", string(p.sliceFrom(startMark)))
	}
	return val, ok
}

func (p *parser) parseRule(rule *rule) (any, bool) {
	p.rstack = append(p.rstack, rule)
	p.pushV()
	val, ok := p.parseExprWrap(rule.expr)
	p.popV()
	p.rstack = p.rstack[:len(p.rstack)-1]
	return val, ok
}

func (p *parser) parseExprWrap(expr any) (any, bool) {
	var pt savepoint

	if p.memoize {
		res, ok := p.getMemoized(expr)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
		pt = p.pt
	}

	val, ok := p.parseExpr(expr)

	if p.memoize {
		p.setMemoized(pt, expr, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseExpr(expr any) (any, bool) {
	p.ExprCnt++
	if p.ExprCnt > p.maxExprCnt {
		panic(errMaxExprCnt)
	}

	var val any
	var ok bool
	switch expr := expr.(type) {
	case *actionExpr:
		val, ok = p.parseActionExpr(expr)
	case *andCodeExpr:
		val, ok = p.parseAndCodeExpr(expr)
	case *andExpr:
		val, ok = p.parseAndExpr(expr)
	case *anyMatcher:
		val, ok = p.parseAnyMatcher(expr)
	case *charClassMatcher:
		val, ok = p.parseCharClassMatcher(expr)
	case *choiceExpr:
		val, ok = p.parseChoiceExpr(expr)
	case *labeledExpr:
		val, ok = p.parseLabeledExpr(expr)
	case *litMatcher:
		val, ok = p.parseLitMatcher(expr)
	case *notCodeExpr:
		val, ok = p.parseNotCodeExpr(expr)
	case *notExpr:
		val, ok = p.parseNotExpr(expr)
	case *oneOrMoreExpr:
		val, ok = p.parseOneOrMoreExpr(expr)
	case *recoveryExpr:
		val, ok = p.parseRecoveryExpr(expr)
	case *ruleRefExpr:
		val, ok = p.parseRuleRefExpr(expr)
	case *seqExpr:
		val, ok = p.parseSeqExpr(expr)
	case *stateCodeExpr:
		val, ok = p.parseStateCodeExpr(expr)
	case *throwExpr:
		val, ok = p.parseThrowExpr(expr)
	case *zeroOrMoreExpr:
		val, ok = p.parseZeroOrMoreExpr(expr)
	case *zeroOrOneExpr:
		val, ok = p.parseZeroOrOneExpr(expr)
	default:
		panic(fmt.Sprintf("unknown expression type %T", expr))
	}
	return val, ok
}

func (p *parser) parseActionExpr(act *actionExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseActionExpr"))
	}

	start := p.pt
	val, ok := p.parseExprWrap(act.expr)
	if ok {
		p.cur.pos = start.position
		p.cur.text = p.sliceFrom(start)
		state := p.cloneState()
		actVal, err := act.run(p)
		if err != nil {
			p.addErrAt(err, start.position, []string{})
		}
		p.restoreState(state)

		val = actVal
	}
	if ok && p.debug {
		p.printIndent("MATCH", string(p.sliceFrom(start)))
	}
	return val, ok
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAndCodeExpr"))
	}

	state := p.cloneState()

	ok, err := and.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, ok
}

func (p *parser) parseAndExpr(and *andExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAndExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	_, ok := p.parseExprWrap(and.expr)
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, ok
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAnyMatcher"))
	}

	if p.pt.rn == utf8.RuneError && p.pt.w == 0 {
		// EOF - see utf8.DecodeRune
		p.failAt(false, p.pt.position, ".")
		return nil, false
	}
	start := p.pt
	p.read()
	p.failAt(true, start.position, ".")
	return p.sliceFrom(start), true
}

func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseCharClassMatcher"))
	}

	cur := p.pt.rn
	start := p.pt

	// can't match EOF
	if cur == utf8.RuneError && p.pt.w == 0 { // see utf8.DecodeRune
		p.failAt(false, start.position, chr.val)
		return nil, false
	}

	if chr.ignoreCase {
		cur = unicode.ToLower(cur)
	}

	// try to match in the list of available chars
	for _, rn := range chr.chars {
		if rn == cur {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of ranges
	for i := 0; i < len(chr.ranges); i += 2 {
		if cur >= chr.ranges[i] && cur <= chr.ranges[i+1] {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of Unicode classes
	for _, cl := range chr.classes {
		if unicode.Is(cl, cur) {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	if chr.inverted {
		p.read()
		p.failAt(true, start.position, chr.val)
		return p.sliceFrom(start), true
	}
	p.failAt(false, start.position, chr.val)
	return nil, false
}

func (p *parser) incChoiceAltCnt(ch *choiceExpr, altI int) {
	choiceIdent := fmt.Sprintf("%s %d:%d", p.rstack[len(p.rstack)-1].name, ch.pos.line, ch.pos.col)
	m := p.ChoiceAltCnt[choiceIdent]
	if m == nil {
		m = make(map[string]int)
		p.ChoiceAltCnt[choiceIdent] = m
	}
	// We increment altI by 1, so the keys do not start at 0
	alt := strconv.Itoa(altI + 1)
	if altI == choiceNoMatch {
		alt = p.choiceNoMatch
	}
	m[alt]++
}

func (p *parser) parseChoiceExpr(ch *choiceExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseChoiceExpr"))
	}

	for altI, alt := range ch.alternatives {
		// dummy assignment to prevent compile error if optimized
		_ = altI

		state := p.cloneState()

		p.pushV()
		val, ok := p.parseExprWrap(alt)
		p.popV()
		if ok {
			p.incChoiceAltCnt(ch, altI)
			return val, ok
		}
		p.restoreState(state)
	}
	p.incChoiceAltCnt(ch, choiceNoMatch)
	return nil, false
}

func (p *parser) parseLabeledExpr(lab *labeledExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseLabeledExpr"))
	}

	p.pushV()
	val, ok := p.parseExprWrap(lab.expr)
	p.popV()
	if ok && lab.label != "" {
		m := p.vstack[len(p.vstack)-1]
		m[lab.label] = val
	}
	return val, ok
}

func (p *parser) parseLitMatcher(lit *litMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseLitMatcher"))
	}

	start := p.pt
	for _, want := range lit.val {
		cur := p.pt.rn
		if lit.ignoreCase {
			cur = unicode.ToLower(cur)
		}
		if cur != want {
			p.failAt(false, start.position, lit.want)
			p.restore(start)
			return nil, false
		}
		p.read()
	}
	p.failAt(true, start.position, lit.want)
	return p.sliceFrom(start), true
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseNotCodeExpr"))
	}

	state := p.cloneState()

	ok, err := not.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, !ok
}

func (p *parser) parseNotExpr(not *notExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseNotExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	_, ok := p.parseExprWrap(not.expr)
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, !ok
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseOneOrMoreExpr"))
	}

	var vals []any

	for {
		p.pushV()
		val, ok := p.parseExprWrap(expr.expr)
		p.popV()
		if !ok {
			if len(vals) == 0 {
				// did not match once, no match
				return nil, false
			}
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseRecoveryExpr(recover *recoveryExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRecoveryExpr (" + strings.Join(recover.failureLabel, ",") + ")"))
	}

	p.pushRecovery(recover.failureLabel, recover.recoverExpr)
	val, ok := p.parseExprWrap(recover.expr)
	p.popRecovery()

	return val, ok
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRuleRefExpr " + ref.name))
	}

	if ref.name == "" {
		panic(fmt.Sprintf("%s: invalid rule: missing name", ref.pos))
	}

	rule := p.rules[ref.name]
	if rule == nil {
		p.addErr(fmt.Errorf("undefined rule: %s", ref.name))
		return nil, false
	}
	return p.parseRuleWrap(rule)
}

func (p *parser) parseSeqExpr(seq *seqExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseSeqExpr"))
	}

	vals := make([]any, 0, len(seq.exprs))

	pt := p.pt
	state := p.cloneState()
	for _, expr := range seq.exprs {
		val, ok := p.parseExprWrap(expr)
		if !ok {
			p.restoreState(state)
			p.restore(pt)
			return nil, false
		}
		vals = append(vals, val)
	}
	return vals, true
}

func (p *parser) parseStateCodeExpr(state *stateCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseStateCodeExpr"))
	}

	err := state.run(p)
	if err != nil {
		p.addErr(err)
	}
	return nil, true
}

func (p *parser) parseThrowExpr(expr *throwExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseThrowExpr"))
	}

	for i := len(p.recoveryStack) - 1; i >= 0; i-- {
		if recoverExpr, ok := p.recoveryStack[i][expr.label]; ok {
			if val, ok := p.parseExprWrap(recoverExpr); ok {
				return val, ok
			}
		}
	}

	return nil, false
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrMoreExpr"))
	}

	var vals []any

	for {
		p.pushV()
		val, ok := p.parseExprWrap(expr.expr)
		p.popV()
		if !ok {
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrOneExpr"))
	}

	p.pushV()
	val, _ := p.parseExprWrap(expr.expr)
	p.popV()
	// whether it matched or not, consider it a match
	return val, true
}
